// Generated by scripts/figure/guides.mjs. Do not edit by hand.

/** Width and height of each figure in public/guide/, in CSS pixels. */
export const GUIDE_FIGURES: Record<string, [width: number, height: number]> = {
	'high_school-math': [226, 216],
	'high_school-physics': [224, 155],
	'high_school-chemistry': [315, 135],
	'high_school-computer-science': [262, 237],
	'middle_school-math': [327, 141],
	'middle_school-science': [291, 181],
	'middle_school-technology': [205, 174],
	'university-analisi-1': [250, 231],
	'university-analisi-2': [198, 190],
	'university-fisica-1': [290, 144],
	'university-fisica-2': [215, 166],
	'university-fondamenti-informatica': [301, 99]
};
