/** The exercises of one lesson: its generator (an id under v2/generators) and the levels the page offers, easiest first. */
export interface LessonExercises {
	generator: string;
	levels: number[];
}

/**
 * Exercises by lesson, keyed by the lesson's database path. A lesson can offer a subset of its generator's
 * levels: MCD e MCM leaves criteria and factorisation to Divisibilità. The page picks the level from the
 * student's attempts (vault/Decisioni/2026-09-24 Il livello degli esercizi lo sceglie la pagina.md).
 */
export const configs: Record<string, LessonExercises> = {
	'high_school/math/insiemi-e-logica/prime-definizioni': { generator: 'prime-definizioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/insiemi-e-logica/insiemi-rappresentazione': { generator: 'insiemi-rappresentazione', levels: [1, 2, 3, 4, 5] },
	'high_school/math/insiemi-e-logica/sottoinsiemi-ugualianza': { generator: 'sottoinsiemi-ugualianza', levels: [1, 2, 3, 4, 5] },
	'high_school/math/insiemi-e-logica/insiemi-unione': { generator: 'insiemi-unione', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/insiemi-e-logica/insiemi-operazioni': { generator: 'insiemi-operazioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-naturali/numeri-naturali-operazioni': { generator: 'numeri-naturali-operazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-naturali/numeri-naturali-mcm-mcd': { generator: 'numeri-naturali-mcm-mcd', levels: [3, 4, 5, 6] },
	'high_school/math/numeri-naturali/numeri-naturali-potenze': { generator: 'numeri-naturali-potenze', levels: [1, 2, 3, 4, 5] },
	'high_school/math/numeri-razionali/numeri-razionali-confronto-frazioni': { generator: 'numeri-razionali-confronto-frazioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-razionali/numeri-razionali-potenze': { generator: 'numeri-razionali-potenze', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-razionali/numeri-razionali-conversione': { generator: 'numeri-razionali-conversione', levels: [1, 2, 3, 4, 5] },
	'high_school/math/monomi-polinomi/monomi-grado': { generator: 'monomi-grado', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/monomi-polinomi/monomi-operazioni': { generator: 'monomi-operazioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/monomi-polinomi/monomi-mcm-mcd': { generator: 'monomi-mcm-mcd', levels: [1, 2, 3, 4, 5] },
	'high_school/math/monomi-polinomi/monomi-espressioni': { generator: 'monomi-espressioni', levels: [1, 2, 3, 4, 5] },
	'high_school/math/equazioni-sistemi/equazioni-primo-grado': { generator: 'equazioni-primo-grado', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/equazioni-di-secondo-grado/equazioni-secondo-grado': { generator: 'equazioni-secondo-grado', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/funzioni/funzioni-iniettive-suriettive-biettive': { generator: 'funzioni-iniettive-suriettive-biettive', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-naturali/numeri-naturali-divisibilita': { generator: 'numeri-naturali-divisibilita', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-interi/numeri-interi-valore-assoluto': { generator: 'numeri-interi-valore-assoluto', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-interi/numeri-interi-operazioni': { generator: 'numeri-interi-operazioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-interi/numeri-interi-potenze': { generator: 'numeri-interi-potenze', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-razionali/numeri-razionali-frazioni': { generator: 'numeri-razionali-frazioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-razionali/numeri-razionali-operazioni': { generator: 'numeri-razionali-operazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-razionali/numeri-razionali-espressioni': { generator: 'numeri-razionali-espressioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-razionali/numeri-razionali-proporzioni': { generator: 'numeri-razionali-proporzioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/monomi-polinomi/monomi': { generator: 'monomi', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/monomi-polinomi/polinomi': { generator: 'polinomi', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/monomi-polinomi/polinomi-operazioni': { generator: 'polinomi-operazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/monomi-polinomi/polinomi-prodotti-notevoli': { generator: 'polinomi-prodotti-notevoli', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/monomi-polinomi/polinomi-espressioni': { generator: 'polinomi-espressioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/monomi-polinomi/polinomi-divisione': { generator: 'polinomi-divisione', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/monomi-polinomi/polinomi-ruffini': { generator: 'polinomi-ruffini', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/scomposizione/scomposizione-raccoglimento': { generator: 'scomposizione-raccoglimento', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/scomposizione/scomposizione-prodotti-notevoli': { generator: 'scomposizione-prodotti-notevoli', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/scomposizione/scomposizione-trinomio': { generator: 'scomposizione-trinomio', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/scomposizione/scomposizione-ruffini': { generator: 'scomposizione-ruffini', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/scomposizione/polinomi-mcd-mcm': { generator: 'polinomi-mcd-mcm', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/insiemi-e-logica/insiemi-prodotto-cartesiano': { generator: 'insiemi-prodotto-cartesiano', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/funzioni/relazioni-binarie': { generator: 'relazioni-binarie', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/funzioni/relazioni-equivalenza-ordine': { generator: 'relazioni-equivalenza-ordine', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/funzioni/definizione-funzione': { generator: 'definizione-funzione', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/funzioni/dominio-codominio-immagine': { generator: 'dominio-codominio-immagine', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/funzioni/composizione-di-funzioni': { generator: 'composizione-di-funzioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/funzioni/funzioni-lineari': { generator: 'funzioni-lineari', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/frazioni-algebriche/frazioni-algebriche-esistenza': { generator: 'frazioni-algebriche-esistenza', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/frazioni-algebriche/frazioni-algebriche-semplificazione': { generator: 'frazioni-algebriche-semplificazione', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/frazioni-algebriche/frazioni-algebriche-operazioni': { generator: 'frazioni-algebriche-operazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/equazioni-sistemi/equazioni-fratte': { generator: 'equazioni-fratte', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/equazioni-sistemi/equazioni-letterali': { generator: 'equazioni-letterali', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/equazioni-sistemi/equazioni-problemi': { generator: 'equazioni-problemi', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/disequazioni-lineari/disequazioni-primo-grado': { generator: 'disequazioni-primo-grado', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/disequazioni-lineari/sistemi-di-disequazioni': { generator: 'sistemi-di-disequazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/disequazioni-lineari/disequazioni-razionali': { generator: 'disequazioni-razionali', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/statistica/statistica-dati': { generator: 'statistica-dati', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/statistica/statistica-medie': { generator: 'statistica-medie', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/statistica/statistica-variabilita': { generator: 'statistica-variabilita', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-piano-triangoli/geometria-enti': { generator: 'geometria-enti', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-piano-triangoli/angoli-e-lati-dei-triangoli': { generator: 'angoli-e-lati-dei-triangoli', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-piano-triangoli/geometria-perpendicolari-parallele': { generator: 'geometria-perpendicolari-parallele', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-piano-triangoli/geometria-punti-notevoli': { generator: 'geometria-punti-notevoli', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-piano-triangoli/geometria-quadrilateri': { generator: 'geometria-quadrilateri', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/insiemi-e-logica/insiemi-intersezione': { generator: 'insiemi-intersezione', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/insiemi-e-logica/insiemi-differenza': { generator: 'insiemi-differenza', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/insiemi-e-logica/logica-proposizioni': { generator: 'logica-proposizioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/insiemi-e-logica/logica-implicazione': { generator: 'logica-implicazione', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/insiemi-e-logica/logica-quantificatori': { generator: 'logica-quantificatori', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/sistemi-lineari/sistemi-di-equazioni': { generator: 'sistemi-di-equazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/sistemi-lineari/sistemi-cramer': { generator: 'sistemi-cramer', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/sistemi-lineari/sistemi-problemi': { generator: 'sistemi-problemi', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-reali/numeri-reali-irrazionali': { generator: 'numeri-reali-irrazionali', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-reali/numeri-reali-radici': { generator: 'numeri-reali-radici', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-reali/radicali-operazioni': { generator: 'radicali-operazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-reali/radicali-razionalizzazione': { generator: 'radicali-razionalizzazione', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-reali/numeri-reali-espressioni': { generator: 'numeri-reali-espressioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-reali/radicali-esponente-razionale': { generator: 'radicali-esponente-razionale', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/equazioni-di-secondo-grado/equazioni-secondo-grado-relazioni': { generator: 'equazioni-secondo-grado-relazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/equazioni-di-secondo-grado/equazioni-parametriche': { generator: 'equazioni-parametriche', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/equazioni-di-secondo-grado/equazioni-secondo-grado-problemi': { generator: 'equazioni-secondo-grado-problemi', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-analitica/il-piano-cartesiano': { generator: 'il-piano-cartesiano', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-analitica/equazione-di-una-retta': { generator: 'equazione-di-una-retta', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-analitica/il-coefficiente-angolare': { generator: 'il-coefficiente-angolare', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-analitica/rette-parallele-tra-loro': { generator: 'rette-parallele-tra-loro', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-analitica/intersezione-tra-due-rette': { generator: 'intersezione-tra-due-rette', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/geometria-analitica/distanza-punto-retta': { generator: 'distanza-punto-retta', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/geometria-analitica/retta-fasci': { generator: 'retta-fasci', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/parabola-disequazioni/funzioni-quadratiche': { generator: 'funzioni-quadratiche', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/parabola-disequazioni/disequazioni-secondo-grado': { generator: 'disequazioni-secondo-grado', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/parabola-disequazioni/disequazioni-secondo-grado-fratte': { generator: 'disequazioni-secondo-grado-fratte', levels: [1, 2, 3, 4, 5, 6, 7] },
	// Chemistry: pools drawn and verified in Python (src/lib/exercises/chimica/pool.ts).
	'high_school/chemistry/chim-quantita-sostanza/mole-massa-molare': { generator: 'mole-massa-molare', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-forma-molecole/geometria-molecolare-vsepr': { generator: 'geometria-molecolare-vsepr', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-idrocarburi/alcani-nomenclatura': { generator: 'alcani-nomenclatura', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chimica-organica/isomeria': { generator: 'isomeria', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chimica-organica/gruppi-funzionali': { generator: 'gruppi-funzionali', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/biochimica/amminoacidi-legame-peptidico': { generator: 'amminoacidi-legame-peptidico', levels: [1, 2, 3, 4, 5] }
};

/** Questions in one exercise session; the start card and the paywall preview say the same. */
export const SESSION_LENGTH = 10;

/** About a minute and a half per question, never under five minutes. */
export const estimatedTime = (questions: number) => `${Math.max(5, Math.ceil(questions * 1.5))} min`;
