/** The exercises of one lesson: its generator (an id under v2/generators) and the levels the page offers, easiest first. */
export interface LessonExercises {
	generator: string;
	levels: number[];
}

/**
 * Exercises by lesson, keyed by the lesson's database path. A lesson can offer a subset of its generator's
 * levels: MCD e MCM leaves criteria and factorisation to Divisibilità. The page picks the level from the
 * student's attempts (vault/Decisioni/2026-09-24 Il livello degli esercizi lo sceglie la pagina.md).
 */
export const configs: Record<string, LessonExercises> = {
	'high_school/math/insiemi-e-logica/prime-definizioni': { generator: 'prime-definizioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/insiemi-e-logica/insiemi-rappresentazione': { generator: 'insiemi-rappresentazione', levels: [1, 2, 3, 4, 5] },
	'high_school/math/insiemi-e-logica/sottoinsiemi-ugualianza': { generator: 'sottoinsiemi-ugualianza', levels: [1, 2, 3, 4, 5] },
	'high_school/math/insiemi-e-logica/insiemi-unione': { generator: 'insiemi-unione', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/insiemi-e-logica/insiemi-operazioni': { generator: 'insiemi-operazioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-naturali/numeri-naturali-operazioni': { generator: 'numeri-naturali-operazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-naturali/numeri-naturali-mcm-mcd': { generator: 'numeri-naturali-mcm-mcd', levels: [3, 4, 5, 6] },
	'high_school/math/numeri-naturali/numeri-naturali-potenze': { generator: 'numeri-naturali-potenze', levels: [1, 2, 3, 4, 5] },
	'high_school/math/numeri-razionali/numeri-razionali-confronto-frazioni': { generator: 'numeri-razionali-confronto-frazioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-razionali/numeri-razionali-potenze': { generator: 'numeri-razionali-potenze', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-razionali/numeri-razionali-conversione': { generator: 'numeri-razionali-conversione', levels: [1, 2, 3, 4, 5] },
	'high_school/math/monomi-polinomi/monomi-grado': { generator: 'monomi-grado', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/monomi-polinomi/monomi-operazioni': { generator: 'monomi-operazioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/monomi-polinomi/monomi-mcm-mcd': { generator: 'monomi-mcm-mcd', levels: [1, 2, 3, 4, 5] },
	'high_school/math/monomi-polinomi/monomi-espressioni': { generator: 'monomi-espressioni', levels: [1, 2, 3, 4, 5] },
	'high_school/math/equazioni-sistemi/equazioni-primo-grado': { generator: 'equazioni-primo-grado', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/equazioni-di-secondo-grado/equazioni-secondo-grado': { generator: 'equazioni-secondo-grado', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/funzioni/funzioni-iniettive-suriettive-biettive': { generator: 'funzioni-iniettive-suriettive-biettive', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-naturali/numeri-naturali-divisibilita': { generator: 'numeri-naturali-divisibilita', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-interi/numeri-interi-valore-assoluto': { generator: 'numeri-interi-valore-assoluto', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-interi/numeri-interi-operazioni': { generator: 'numeri-interi-operazioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-interi/numeri-interi-potenze': { generator: 'numeri-interi-potenze', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-razionali/numeri-razionali-frazioni': { generator: 'numeri-razionali-frazioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-razionali/numeri-razionali-operazioni': { generator: 'numeri-razionali-operazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-razionali/numeri-razionali-espressioni': { generator: 'numeri-razionali-espressioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/numeri-razionali/numeri-razionali-proporzioni': { generator: 'numeri-razionali-proporzioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/monomi-polinomi/monomi': { generator: 'monomi', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/monomi-polinomi/polinomi': { generator: 'polinomi', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/monomi-polinomi/polinomi-operazioni': { generator: 'polinomi-operazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/monomi-polinomi/polinomi-prodotti-notevoli': { generator: 'polinomi-prodotti-notevoli', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/monomi-polinomi/polinomi-espressioni': { generator: 'polinomi-espressioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/monomi-polinomi/polinomi-divisione': { generator: 'polinomi-divisione', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/monomi-polinomi/polinomi-ruffini': { generator: 'polinomi-ruffini', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/scomposizione/scomposizione-raccoglimento': { generator: 'scomposizione-raccoglimento', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/scomposizione/scomposizione-prodotti-notevoli': { generator: 'scomposizione-prodotti-notevoli', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/scomposizione/scomposizione-trinomio': { generator: 'scomposizione-trinomio', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/scomposizione/scomposizione-ruffini': { generator: 'scomposizione-ruffini', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/scomposizione/polinomi-mcd-mcm': { generator: 'polinomi-mcd-mcm', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/insiemi-e-logica/insiemi-prodotto-cartesiano': { generator: 'insiemi-prodotto-cartesiano', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/funzioni/relazioni-binarie': { generator: 'relazioni-binarie', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/funzioni/relazioni-equivalenza-ordine': { generator: 'relazioni-equivalenza-ordine', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/funzioni/definizione-funzione': { generator: 'definizione-funzione', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/funzioni/dominio-codominio-immagine': { generator: 'dominio-codominio-immagine', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/funzioni/composizione-di-funzioni': { generator: 'composizione-di-funzioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/funzioni/funzioni-lineari': { generator: 'funzioni-lineari', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/frazioni-algebriche/frazioni-algebriche-esistenza': { generator: 'frazioni-algebriche-esistenza', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/frazioni-algebriche/frazioni-algebriche-semplificazione': { generator: 'frazioni-algebriche-semplificazione', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/frazioni-algebriche/frazioni-algebriche-operazioni': { generator: 'frazioni-algebriche-operazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/equazioni-sistemi/equazioni-fratte': { generator: 'equazioni-fratte', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/equazioni-sistemi/equazioni-letterali': { generator: 'equazioni-letterali', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/equazioni-sistemi/equazioni-problemi': { generator: 'equazioni-problemi', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/disequazioni-lineari/disequazioni-primo-grado': { generator: 'disequazioni-primo-grado', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/disequazioni-lineari/sistemi-di-disequazioni': { generator: 'sistemi-di-disequazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/disequazioni-lineari/disequazioni-razionali': { generator: 'disequazioni-razionali', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/statistica/statistica-dati': { generator: 'statistica-dati', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/statistica/statistica-medie': { generator: 'statistica-medie', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/statistica/statistica-variabilita': { generator: 'statistica-variabilita', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-piano-triangoli/geometria-enti': { generator: 'geometria-enti', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-piano-triangoli/angoli-e-lati-dei-triangoli': { generator: 'angoli-e-lati-dei-triangoli', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-piano-triangoli/geometria-perpendicolari-parallele': { generator: 'geometria-perpendicolari-parallele', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-piano-triangoli/geometria-punti-notevoli': { generator: 'geometria-punti-notevoli', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-piano-triangoli/geometria-quadrilateri': { generator: 'geometria-quadrilateri', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/insiemi-e-logica/insiemi-intersezione': { generator: 'insiemi-intersezione', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/insiemi-e-logica/insiemi-differenza': { generator: 'insiemi-differenza', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/insiemi-e-logica/logica-proposizioni': { generator: 'logica-proposizioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/insiemi-e-logica/logica-implicazione': { generator: 'logica-implicazione', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/insiemi-e-logica/logica-quantificatori': { generator: 'logica-quantificatori', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/sistemi-lineari/sistemi-di-equazioni': { generator: 'sistemi-di-equazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/sistemi-lineari/sistemi-cramer': { generator: 'sistemi-cramer', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/sistemi-lineari/sistemi-problemi': { generator: 'sistemi-problemi', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-reali/numeri-reali-irrazionali': { generator: 'numeri-reali-irrazionali', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-reali/numeri-reali-radici': { generator: 'numeri-reali-radici', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-reali/radicali-operazioni': { generator: 'radicali-operazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-reali/radicali-razionalizzazione': { generator: 'radicali-razionalizzazione', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-reali/numeri-reali-espressioni': { generator: 'numeri-reali-espressioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/numeri-reali/radicali-esponente-razionale': { generator: 'radicali-esponente-razionale', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/equazioni-di-secondo-grado/equazioni-secondo-grado-relazioni': { generator: 'equazioni-secondo-grado-relazioni', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/equazioni-di-secondo-grado/equazioni-parametriche': { generator: 'equazioni-parametriche', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/equazioni-di-secondo-grado/equazioni-secondo-grado-problemi': { generator: 'equazioni-secondo-grado-problemi', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-analitica/il-piano-cartesiano': { generator: 'il-piano-cartesiano', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-analitica/equazione-di-una-retta': { generator: 'equazione-di-una-retta', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-analitica/il-coefficiente-angolare': { generator: 'il-coefficiente-angolare', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-analitica/rette-parallele-tra-loro': { generator: 'rette-parallele-tra-loro', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-analitica/intersezione-tra-due-rette': { generator: 'intersezione-tra-due-rette', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/geometria-analitica/distanza-punto-retta': { generator: 'distanza-punto-retta', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/geometria-analitica/retta-fasci': { generator: 'retta-fasci', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/parabola-disequazioni/funzioni-quadratiche': { generator: 'funzioni-quadratiche', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/parabola-disequazioni/disequazioni-secondo-grado': { generator: 'disequazioni-secondo-grado', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/parabola-disequazioni/disequazioni-secondo-grado-fratte': { generator: 'disequazioni-secondo-grado-fratte', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/probabilita/concetti-probabilita': { generator: 'concetti-probabilita', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/probabilita/leggi-probabilita': { generator: 'leggi-probabilita', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/grado-superiore/equazioni-binomie-trinomie': { generator: 'equazioni-binomie-trinomie', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/grado-superiore/valore-assoluto-equazioni': { generator: 'valore-assoluto-equazioni', levels: [1, 2, 3, 4, 5, 6, 7, 8, 9] },
	'high_school/math/grado-superiore/equazioni-irrazionali': { generator: 'equazioni-irrazionali', levels: [1, 2, 3, 4, 5, 6, 7, 8, 9] },
	'high_school/math/grado-superiore/sistemi-secondo-grado': { generator: 'sistemi-secondo-grado', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/geometria-piano-circonferenza/circonferenza-cerchio': { generator: 'circonferenza-cerchio', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-piano-circonferenza/poligoni-inscritti': { generator: 'poligoni-inscritti', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-piano-circonferenza/equivalenza-aree': { generator: 'equivalenza-aree', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/math/geometria-piano-circonferenza/circonferenza-lunghezza-area': { generator: 'circonferenza-lunghezza-area', levels: [1, 2, 3, 4, 5, 6, 7, 8] },
	'high_school/math/geometria-piano-circonferenza/teorema-di-pitagora': { generator: 'teorema-di-pitagora', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-piano-circonferenza/teorema-di-talete': { generator: 'teorema-di-talete', levels: [1, 2, 3, 4, 5, 6, 7, 8] },
	'high_school/math/geometria-piano-circonferenza/similitudine': { generator: 'similitudine', levels: [1, 2, 3, 4, 5, 6, 7, 8] },
	'high_school/math/geometria-piano-circonferenza/triangolo-rettangolo-trigonometria': { generator: 'triangolo-rettangolo-trigonometria', levels: [1, 2, 3, 4, 5, 6, 7] },
	'high_school/math/geometria-piano-circonferenza/trasformazioni-geometriche': { generator: 'trasformazioni-geometriche', levels: [1, 2, 3, 4, 5, 6, 7] },
	// Physics, first year: generators in TypeScript like the maths ones (docs/lezioni/fisica/README.md).
	'high_school/physics/fis-grandezze/fis-metodo-sperimentale': { generator: 'fis-metodo-sperimentale', levels: [1, 2, 3, 4] },
	'high_school/physics/fis-grandezze/fis-grandezze-si': { generator: 'fis-grandezze-si', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-grandezze/fis-grandezze-derivate': { generator: 'fis-grandezze-derivate', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-grandezze/fis-strumenti-misura': { generator: 'fis-strumenti-misura', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-grandezze/fis-errori-misura': { generator: 'fis-errori-misura', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-grandezze/fis-valore-medio': { generator: 'fis-valore-medio', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-grandezze/fis-incertezza-relativa': { generator: 'fis-incertezza-relativa', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-grandezze/fis-cifre-significative': { generator: 'fis-cifre-significative', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-grandezze/fis-relazione-laboratorio': { generator: 'fis-relazione-laboratorio', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-relazioni-grafici/fis-tabelle-grafici': { generator: 'fis-tabelle-grafici', levels: [1, 2, 3, 4] },
	'high_school/physics/fis-relazioni-grafici/fis-proporzionalita-diretta': { generator: 'fis-proporzionalita-diretta', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-relazioni-grafici/fis-proporzionalita-inversa': { generator: 'fis-proporzionalita-inversa', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-vettori-forze/fis-scalari-vettori': { generator: 'fis-scalari-vettori', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-vettori-forze/fis-operazioni-vettori': { generator: 'fis-operazioni-vettori', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-vettori-forze/fis-seno-coseno': { generator: 'fis-seno-coseno', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-vettori-forze/forze': { generator: 'forze', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-vettori-forze/fis-forza-peso': { generator: 'fis-forza-peso', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-vettori-forze/fis-forza-elastica': { generator: 'fis-forza-elastica', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-vettori-forze/fis-attrito': { generator: 'fis-attrito', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-equilibrio-solidi/fis-equilibrio-punto': { generator: 'fis-equilibrio-punto', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-equilibrio-solidi/fis-equilibrio-piano-inclinato': { generator: 'fis-equilibrio-piano-inclinato', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-equilibrio-solidi/fis-momento-forza': { generator: 'fis-momento-forza', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-equilibrio-solidi/fis-equilibrio-corpo-rigido': { generator: 'fis-equilibrio-corpo-rigido', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-equilibrio-solidi/fis-leve': { generator: 'fis-leve', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-equilibrio-solidi/fis-baricentro': { generator: 'fis-baricentro', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-equilibrio-fluidi/fis-pressione': { generator: 'fis-pressione', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-equilibrio-fluidi/fis-legge-pascal': { generator: 'fis-legge-pascal', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-equilibrio-fluidi/fis-legge-stevino': { generator: 'fis-legge-stevino', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-equilibrio-fluidi/fis-pressione-atmosferica': { generator: 'fis-pressione-atmosferica', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-equilibrio-fluidi/fis-archimede': { generator: 'fis-archimede', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/ottica/ottica-geometrica': { generator: 'ottica-geometrica', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/ottica/riflessione': { generator: 'riflessione', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/ottica/fis-specchi-sferici': { generator: 'fis-specchi-sferici', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/ottica/fis-rifrazione': { generator: 'fis-rifrazione', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/ottica/fis-dispersione': { generator: 'fis-dispersione', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/ottica/fis-lenti': { generator: 'fis-lenti', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/ottica/fis-strumenti-ottici': { generator: 'fis-strumenti-ottici', levels: [1, 2, 3, 4, 5, 6] },
	// Physics, second year.
	'high_school/physics/cinematica/fis-punto-materiale': { generator: 'fis-punto-materiale', levels: [1, 2, 3, 4] },
	'high_school/physics/cinematica/velocita': { generator: 'velocita', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/cinematica/fis-moto-rettilineo-uniforme': { generator: 'fis-moto-rettilineo-uniforme', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/cinematica/fis-accelerazione': { generator: 'fis-accelerazione', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/cinematica/moto-uniforme-accelerato': { generator: 'moto-uniforme-accelerato', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/cinematica/fis-grafico-velocita-tempo': { generator: 'fis-grafico-velocita-tempo', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/cinematica/fis-caduta-libera': { generator: 'fis-caduta-libera', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-moti-piano/fis-spostamento-velocita-piano': { generator: 'fis-spostamento-velocita-piano', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-moti-piano/fis-composizione-moti': { generator: 'fis-composizione-moti', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-moti-piano/fis-moto-circolare-uniforme': { generator: 'fis-moto-circolare-uniforme', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-moti-piano/fis-accelerazione-centripeta': { generator: 'fis-accelerazione-centripeta', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-moti-piano/fis-moto-armonico': { generator: 'fis-moto-armonico', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/dinamica/fis-primo-principio': { generator: 'fis-primo-principio', levels: [1, 2, 3, 4] },
	'high_school/physics/dinamica/leggi-newton': { generator: 'leggi-newton', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/dinamica/fis-terzo-principio': { generator: 'fis-terzo-principio', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/dinamica/fis-diagramma-corpo-libero': { generator: 'fis-diagramma-corpo-libero', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-forze-movimento/fis-piano-inclinato': { generator: 'fis-piano-inclinato', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-forze-movimento/fis-corpi-collegati': { generator: 'fis-corpi-collegati', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-forze-movimento/fis-moto-proiettili': { generator: 'fis-moto-proiettili', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-forze-movimento/fis-forza-centripeta': { generator: 'fis-forza-centripeta', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-forze-movimento/fis-pendolo-molla': { generator: 'fis-pendolo-molla', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/lavoro-energia/lavoro': { generator: 'lavoro', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/lavoro-energia/fis-potenza': { generator: 'fis-potenza', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/lavoro-energia/fis-energia-cinetica': { generator: 'fis-energia-cinetica', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/lavoro-energia/fis-energia-potenziale': { generator: 'fis-energia-potenziale', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/lavoro-energia/energia': { generator: 'energia', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/lavoro-energia/fis-energia-totale': { generator: 'fis-energia-totale', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-temperatura-calore/fis-temperatura': { generator: 'fis-temperatura', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-temperatura-calore/fis-dilatazione-termica': { generator: 'fis-dilatazione-termica', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-temperatura-calore/calore': { generator: 'calore', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-temperatura-calore/fis-equilibrio-termico': { generator: 'fis-equilibrio-termico', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/physics/fis-temperatura-calore/fis-propagazione-calore': { generator: 'fis-propagazione-calore', levels: [1, 2, 3, 4, 5] },
	'high_school/physics/fis-temperatura-calore/fis-passaggi-stato': { generator: 'fis-passaggi-stato', levels: [1, 2, 3, 4, 5, 6] },
	// Chemistry, first two years: generators in TypeScript (docs/lezioni/chimica/README.md, "Il biennio").
	'high_school/chemistry/chim-misure/chim-grandezze-si': { generator: 'chim-grandezze-si', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/chemistry/chim-misure/chim-massa-volume-densita': { generator: 'chim-massa-volume-densita', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/chemistry/chim-misure/chim-temperatura-calore': { generator: 'chim-temperatura-calore', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/chemistry/chim-misure/chim-errori-cifre-significative': { generator: 'chim-errori-cifre-significative', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/chemistry/chim-materia/chim-stati-aggregazione': { generator: 'chim-stati-aggregazione', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-materia/chim-modello-particellare': { generator: 'chim-modello-particellare', levels: [1, 2, 3, 4] },
	'high_school/chemistry/chim-materia/chim-sostanze-miscugli': { generator: 'chim-sostanze-miscugli', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-materia/chim-soluzioni-percentuale': { generator: 'chim-soluzioni-percentuale', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/chemistry/chim-materia/chim-separazione-miscugli': { generator: 'chim-separazione-miscugli', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-materia/chim-passaggi-stato': { generator: 'chim-passaggi-stato', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-materia/chim-curve-riscaldamento': { generator: 'chim-curve-riscaldamento', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/chemistry/chim-trasformazioni-chimiche/chim-trasformazioni-fisiche-chimiche': { generator: 'chim-trasformazioni-fisiche-chimiche', levels: [1, 2, 3, 4] },
	'high_school/chemistry/chim-trasformazioni-chimiche/chim-elementi-composti': { generator: 'chim-elementi-composti', levels: [1, 2, 3, 4] },
	'high_school/chemistry/chim-trasformazioni-chimiche/chim-legge-lavoisier': { generator: 'chim-legge-lavoisier', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-trasformazioni-chimiche/chim-legge-proust': { generator: 'chim-legge-proust', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-trasformazioni-chimiche/chim-legge-proporzioni-multiple': { generator: 'chim-legge-proporzioni-multiple', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-trasformazioni-chimiche/chim-teoria-atomica-dalton': { generator: 'chim-teoria-atomica-dalton', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-trasformazioni-chimiche/chim-atomi-molecole-ioni': { generator: 'chim-atomi-molecole-ioni', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-trasformazioni-chimiche/chim-formula-chimica': { generator: 'chim-formula-chimica', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/chemistry/chim-gas/chim-teoria-cinetica': { generator: 'chim-teoria-cinetica', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-gas/chim-pressione-gas': { generator: 'chim-pressione-gas', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-gas/chim-legge-boyle': { generator: 'chim-legge-boyle', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/chemistry/chim-gas/chim-legge-charles-gay-lussac': { generator: 'chim-legge-charles-gay-lussac', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-gas/chim-equazione-generale-gas': { generator: 'chim-equazione-generale-gas', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-gas/chim-principio-avogadro': { generator: 'chim-principio-avogadro', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-quantita-sostanza/chim-formula-minima': { generator: 'chim-formula-minima', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-quantita-sostanza/chim-volume-molare': { generator: 'chim-volume-molare', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-quantita-sostanza/gas-ideali': { generator: 'gas-ideali', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/chemistry/chim-quantita-sostanza/chim-pressioni-parziali': { generator: 'chim-pressioni-parziali', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/atomo-struttura/chim-natura-elettrica': { generator: 'chim-natura-elettrica', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/atomo-struttura/particelle-fondamentali': { generator: 'particelle-fondamentali', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/atomo-struttura/chim-thomson-rutherford': { generator: 'chim-thomson-rutherford', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/atomo-struttura/numero-massa': { generator: 'numero-massa', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/chemistry/atomo-struttura/chim-tavola-mendeleev': { generator: 'chim-tavola-mendeleev', levels: [1, 2, 3, 4] },
	'high_school/chemistry/chim-struttura-elettronica/chim-orbitali-numeri-quantici': { generator: 'chim-orbitali-numeri-quantici', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-acqua/chim-acqua-molecola': { generator: 'chim-acqua-molecola', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-acqua/chim-acqua-proprieta': { generator: 'chim-acqua-proprieta', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-acqua/chim-acqua-solvente': { generator: 'chim-acqua-solvente', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/chemistry/chim-acqua/chim-acqua-acidi-basi': { generator: 'chim-acqua-acidi-basi', levels: [1, 2, 3, 4, 5, 6] },
	// Chemistry: pools drawn and verified in Python (src/lib/exercises/chimica/pool.ts).

	'high_school/chemistry/chim-quantita-sostanza/mole-massa-molare': { generator: 'mole-massa-molare', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-forma-molecole/geometria-molecolare-vsepr': { generator: 'geometria-molecolare-vsepr', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chim-idrocarburi/alcani-nomenclatura': { generator: 'alcani-nomenclatura', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chimica-organica/isomeria': { generator: 'isomeria', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/chimica-organica/gruppi-funzionali': { generator: 'gruppi-funzionali', levels: [1, 2, 3, 4, 5] },
	'high_school/chemistry/biochimica/amminoacidi-legame-peptidico': { generator: 'amminoacidi-legame-peptidico', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/informatica/inf-informazione-dati': { generator: 'inf-informazione-dati', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/informatica/hardware-software': { generator: 'hardware-software', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/informatica/inf-bit-byte': { generator: 'inf-bit-byte', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-sistemi-numerazione/inf-sistemi-posizionali': { generator: 'inf-sistemi-posizionali', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/inf-sistemi-numerazione/inf-binario-decimale': { generator: 'inf-binario-decimale', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/inf-sistemi-numerazione/inf-esadecimale': { generator: 'inf-esadecimale', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-sistemi-numerazione/inf-aritmetica-binaria': { generator: 'inf-aritmetica-binaria', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/inf-codifica/inf-interi-segno': { generator: 'inf-interi-segno', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/inf-codifica/inf-virgola-mobile': { generator: 'inf-virgola-mobile', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/inf-codifica/inf-codifica-caratteri': { generator: 'inf-codifica-caratteri', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-codifica/inf-codifica-immagini': { generator: 'inf-codifica-immagini', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-codifica/inf-codifica-suoni': { generator: 'inf-codifica-suoni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-architettura/inf-von-neumann': { generator: 'inf-von-neumann', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/inf-architettura/inf-cpu': { generator: 'inf-cpu', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-architettura/memoria-storage': { generator: 'memoria-storage', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/inf-architettura/inf-bus-periferiche': { generator: 'inf-bus-periferiche', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/inf-architettura/inf-tipi-computer': { generator: 'inf-tipi-computer', levels: [1, 2, 3, 4] },
	'high_school/computer-science/sistemi-operativi/inf-funzioni-so': { generator: 'inf-funzioni-so', levels: [1, 2, 3, 4] },
	'high_school/computer-science/sistemi-operativi/inf-avvio-interfacce': { generator: 'inf-avvio-interfacce', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/sistemi-operativi/processi-thread': { generator: 'processi-thread', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/sistemi-operativi/inf-gestione-memoria': { generator: 'inf-gestione-memoria', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/sistemi-operativi/inf-file-system': { generator: 'inf-file-system', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/office/excel': { generator: 'excel', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/office/inf-riferimenti-celle': { generator: 'inf-riferimenti-celle', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/office/inf-funzioni-foglio': { generator: 'inf-funzioni-foglio', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/office/inf-funzioni-logiche': { generator: 'inf-funzioni-logiche', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/office/inf-grafici-dati': { generator: 'inf-grafici-dati', levels: [1, 2, 3, 4] },
	'high_school/computer-science/office/inf-analisi-dati': { generator: 'inf-analisi-dati', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/presentazioni/word': { generator: 'word', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/presentazioni/inf-stili-indici': { generator: 'inf-stili-indici', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/presentazioni/powerpoint': { generator: 'powerpoint', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/presentazioni/creare-slide': { generator: 'creare-slide', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/internet-web/internet': { generator: 'internet', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/internet-web/inf-client-server': { generator: 'inf-client-server', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/internet-web/inf-indirizzi-domini': { generator: 'inf-indirizzi-domini', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/internet-web/http-html': { generator: 'http-html', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/internet-web/inf-servizi-internet': { generator: 'inf-servizi-internet', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/internet-web/inf-ricerca-informazioni': { generator: 'inf-ricerca-informazioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/internet-web/cloud': { generator: 'cloud', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/sicurezza/virus-malware': { generator: 'virus-malware', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/sicurezza/password-sicure': { generator: 'password-sicure', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/sicurezza/inf-phishing': { generator: 'inf-phishing', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/sicurezza/inf-privacy': { generator: 'inf-privacy', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/sicurezza/inf-diritto-autore': { generator: 'inf-diritto-autore', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/programmazione-visiva/algoritmi': { generator: 'algoritmi', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/programmazione-visiva/inf-problema-algoritmo': { generator: 'inf-problema-algoritmo', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/programmazione-visiva/diagrammi-flusso': { generator: 'diagrammi-flusso', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/programmazione-visiva/inf-pseudocodice': { generator: 'inf-pseudocodice', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/programmazione-visiva/inf-bohm-jacopini': { generator: 'inf-bohm-jacopini', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/programmazione-visiva/scratch': { generator: 'scratch', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/inf-primi-programmi/inf-linguaggi-programmazione': { generator: 'inf-linguaggi-programmazione', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/inf-primi-programmi/inf-input-output': { generator: 'inf-input-output', levels: [1, 2, 3, 4, 5] },
	'high_school/computer-science/inf-primi-programmi/inf-variabili-tipi': { generator: 'inf-variabili-tipi', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-primi-programmi/inf-espressioni': { generator: 'inf-espressioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-primi-programmi/inf-errori-debug': { generator: 'inf-errori-debug', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-selezione/inf-condizioni': { generator: 'inf-condizioni', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-selezione/inf-selezione-due-vie': { generator: 'inf-selezione-due-vie', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-selezione/inf-operatori-logici': { generator: 'inf-operatori-logici', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-selezione/inf-selezione-multipla': { generator: 'inf-selezione-multipla', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-iterazione/inf-ciclo-while': { generator: 'inf-ciclo-while', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-iterazione/inf-ciclo-for': { generator: 'inf-ciclo-for', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-iterazione/inf-contatori-accumulatori': { generator: 'inf-contatori-accumulatori', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-iterazione/inf-cicli-annidati': { generator: 'inf-cicli-annidati', levels: [1, 2, 3, 4, 5, 6] },
	'high_school/computer-science/inf-iterazione/inf-massimo-minimo-media': { generator: 'inf-massimo-minimo-media', levels: [1, 2, 3, 4, 5, 6] }
};

/** Questions in one exercise session; the start card and the paywall preview say the same. */
export const SESSION_LENGTH = 10;

/** About a minute and a half per question, never under five minutes. */
export const estimatedTime = (questions: number) => `${Math.max(5, Math.ceil(questions * 1.5))} min`;
