import type { Generator } from './v2/types';

/**
 * Exercise generators by id. Each module is loaded only when its lesson's
 * exercises are asked for, so the generators never ship with the rest.
 */
export const generators: Record<string, () => Promise<Generator>> = {
	'prime-definizioni': () => import('./v2/generators/prime-definizioni').then((m) => m.default),
	'insiemi-rappresentazione': () => import('./v2/generators/insiemi-rappresentazione').then((m) => m.default),
	'sottoinsiemi-ugualianza': () => import('./v2/generators/sottoinsiemi-ugualianza').then((m) => m.default),
	'insiemi-unione': () => import('./v2/generators/insiemi-unione').then((m) => m.default),
	'insiemi-operazioni': () => import('./v2/generators/insiemi-operazioni').then((m) => m.default),
	'numeri-naturali-operazioni': () => import('./v2/generators/numeri-naturali-operazioni').then((m) => m.default),
	'numeri-naturali-mcm-mcd': () => import('./v2/generators/numeri-naturali-mcm-mcd').then((m) => m.default),
	'numeri-naturali-potenze': () => import('./v2/generators/numeri-naturali-potenze').then((m) => m.default),
	'numeri-razionali-confronto-frazioni': () => import('./v2/generators/numeri-razionali-confronto-frazioni').then((m) => m.default),
	'numeri-razionali-potenze': () => import('./v2/generators/numeri-razionali-potenze').then((m) => m.default),
	'numeri-razionali-conversione': () => import('./v2/generators/numeri-razionali-conversione').then((m) => m.default),
	'monomi-grado': () => import('./v2/generators/monomi-grado').then((m) => m.default),
	'monomi-operazioni': () => import('./v2/generators/monomi-operazioni').then((m) => m.default),
	'monomi-mcm-mcd': () => import('./v2/generators/monomi-mcm-mcd').then((m) => m.default),
	'monomi-espressioni': () => import('./v2/generators/monomi-espressioni').then((m) => m.default),
	'equazioni-primo-grado': () => import('./v2/generators/equazioni-primo-grado').then((m) => m.default),
	'equazioni-secondo-grado': () => import('./v2/generators/equazioni-secondo-grado').then((m) => m.default),
	'funzioni-iniettive-suriettive-biettive': () => import('./v2/generators/funzioni-iniettive-suriettive-biettive').then((m) => m.default),
	'numeri-naturali-divisibilita': () => import('./v2/generators/numeri-naturali-divisibilita').then((m) => m.default),
	'numeri-interi-valore-assoluto': () => import('./v2/generators/numeri-interi-valore-assoluto').then((m) => m.default),
	'numeri-interi-operazioni': () => import('./v2/generators/numeri-interi-operazioni').then((m) => m.default),
	'numeri-interi-potenze': () => import('./v2/generators/numeri-interi-potenze').then((m) => m.default),
	'numeri-razionali-frazioni': () => import('./v2/generators/numeri-razionali-frazioni').then((m) => m.default),
	'numeri-razionali-operazioni': () => import('./v2/generators/numeri-razionali-operazioni').then((m) => m.default),
	'numeri-razionali-espressioni': () => import('./v2/generators/numeri-razionali-espressioni').then((m) => m.default),
	'numeri-razionali-proporzioni': () => import('./v2/generators/numeri-razionali-proporzioni').then((m) => m.default),
	'monomi': () => import('./v2/generators/monomi').then((m) => m.default),
	'polinomi': () => import('./v2/generators/polinomi').then((m) => m.default),
	'polinomi-operazioni': () => import('./v2/generators/polinomi-operazioni').then((m) => m.default),
	'polinomi-prodotti-notevoli': () => import('./v2/generators/polinomi-prodotti-notevoli').then((m) => m.default),
	'polinomi-espressioni': () => import('./v2/generators/polinomi-espressioni').then((m) => m.default),
	'polinomi-divisione': () => import('./v2/generators/polinomi-divisione').then((m) => m.default),
	'polinomi-ruffini': () => import('./v2/generators/polinomi-ruffini').then((m) => m.default),
	'scomposizione-raccoglimento': () => import('./v2/generators/scomposizione-raccoglimento').then((m) => m.default),
	'scomposizione-prodotti-notevoli': () => import('./v2/generators/scomposizione-prodotti-notevoli').then((m) => m.default),
	'scomposizione-trinomio': () => import('./v2/generators/scomposizione-trinomio').then((m) => m.default),
	'scomposizione-ruffini': () => import('./v2/generators/scomposizione-ruffini').then((m) => m.default),
	'polinomi-mcd-mcm': () => import('./v2/generators/polinomi-mcd-mcm').then((m) => m.default),
	'insiemi-prodotto-cartesiano': () => import('./v2/generators/insiemi-prodotto-cartesiano').then((m) => m.default),
	'relazioni-binarie': () => import('./v2/generators/relazioni-binarie').then((m) => m.default),
	'relazioni-equivalenza-ordine': () => import('./v2/generators/relazioni-equivalenza-ordine').then((m) => m.default),
	'definizione-funzione': () => import('./v2/generators/definizione-funzione').then((m) => m.default),
	'dominio-codominio-immagine': () => import('./v2/generators/dominio-codominio-immagine').then((m) => m.default),
	'composizione-di-funzioni': () => import('./v2/generators/composizione-di-funzioni').then((m) => m.default),
	'funzioni-lineari': () => import('./v2/generators/funzioni-lineari').then((m) => m.default),
	'frazioni-algebriche-esistenza': () => import('./v2/generators/frazioni-algebriche-esistenza').then((m) => m.default),
	'frazioni-algebriche-semplificazione': () => import('./v2/generators/frazioni-algebriche-semplificazione').then((m) => m.default),
	'frazioni-algebriche-operazioni': () => import('./v2/generators/frazioni-algebriche-operazioni').then((m) => m.default),
	'equazioni-fratte': () => import('./v2/generators/equazioni-fratte').then((m) => m.default),
	'equazioni-letterali': () => import('./v2/generators/equazioni-letterali').then((m) => m.default),
	'equazioni-problemi': () => import('./v2/generators/equazioni-problemi').then((m) => m.default),
	'disequazioni-primo-grado': () => import('./v2/generators/disequazioni-primo-grado').then((m) => m.default),
	'sistemi-di-disequazioni': () => import('./v2/generators/sistemi-di-disequazioni').then((m) => m.default),
	'disequazioni-razionali': () => import('./v2/generators/disequazioni-razionali').then((m) => m.default),
	'statistica-dati': () => import('./v2/generators/statistica-dati').then((m) => m.default),
	'statistica-medie': () => import('./v2/generators/statistica-medie').then((m) => m.default),
	'statistica-variabilita': () => import('./v2/generators/statistica-variabilita').then((m) => m.default),
	'geometria-enti': () => import('./v2/generators/geometria-enti').then((m) => m.default),
	'angoli-e-lati-dei-triangoli': () => import('./v2/generators/angoli-e-lati-dei-triangoli').then((m) => m.default),
	'geometria-perpendicolari-parallele': () => import('./v2/generators/geometria-perpendicolari-parallele').then((m) => m.default),
	'geometria-punti-notevoli': () => import('./v2/generators/geometria-punti-notevoli').then((m) => m.default),
	'geometria-quadrilateri': () => import('./v2/generators/geometria-quadrilateri').then((m) => m.default),
	'insiemi-intersezione': () => import('./v2/generators/insiemi-intersezione').then((m) => m.default),
	'insiemi-differenza': () => import('./v2/generators/insiemi-differenza').then((m) => m.default),
	'logica-proposizioni': () => import('./v2/generators/logica-proposizioni').then((m) => m.default),
	'logica-implicazione': () => import('./v2/generators/logica-implicazione').then((m) => m.default),
	'logica-quantificatori': () => import('./v2/generators/logica-quantificatori').then((m) => m.default),
	// Chemistry: pools pregenerated in Python (chimica/pool.ts).
	'mole-massa-molare': () => import('./chimica/mole-massa-molare').then((m) => m.default),
	'geometria-molecolare-vsepr': () => import('./chimica/geometria-molecolare-vsepr').then((m) => m.default),
	'alcani-nomenclatura': () => import('./chimica/alcani-nomenclatura').then((m) => m.default),
	'isomeria': () => import('./chimica/isomeria').then((m) => m.default),
	'gruppi-funzionali': () => import('./chimica/gruppi-funzionali').then((m) => m.default),
	'amminoacidi-legame-peptidico': () => import('./chimica/amminoacidi-legame-peptidico').then((m) => m.default)
};
