/**
 * What each exercise level adds, in the student's words: the names of the nodes on a lesson's exercise path.
 * Written from specs/exercises/*.md; keyed by generator id, then by level.
 */
export const levelNames: Record<string, Record<number, string>> = {
	'prime-definizioni': {
		1: 'Riconoscere un insieme',
		2: 'Appartiene o no: ∈ e ∉',
		3: 'Appartiene a ℕ, a ℤ o a ℚ',
		4: "Trovare l'insieme vuoto",
		5: "Quanti elementi ha l'insieme",
		6: 'Finito o infinito',
	},
	'insiemi-rappresentazione': {
		1: "Dalla proprietà all'elenco",
		2: 'Pari, multipli, divisori e lo zero',
		3: 'Numeri negativi: in ℕ o in ℤ',
		4: 'Condizioni con un calcolo',
		5: "Dall'elenco alla proprietà",
	},
	'sottoinsiemi-ugualianza': {
		1: 'Vero o falso: A ⊆ B',
		2: 'Appartenenza o inclusione: ∈ e ⊆',
		3: 'Inclusione stretta: ⊂ e ⊆',
		4: 'Sottoinsiemi propri e quanti sono',
		5: 'Quando due insiemi sono uguali',
	},
	'insiemi-unione': {
		1: 'Unione di due insiemi',
		2: 'Insiemi descritti a parole',
		3: 'Unione di tre insiemi',
		4: "Le proprietà dell'unione",
		5: "Contare gli elementi dell'unione",
		6: 'Problemi con due gruppi',
	},
	'insiemi-operazioni': {
		1: "L'intersezione: gli elementi comuni",
		2: "La differenza, dove conta l'ordine",
		3: 'Il complementare in U',
		4: 'Il prodotto cartesiano',
		5: 'Espressioni e leggi di De Morgan',
		6: 'Problemi con il diagramma',
	},
	'numeri-naturali-operazioni': {
		1: 'Quale proprietà è stata usata',
		2: 'Lo zero e la divisione con resto',
		3: 'Espressioni senza parentesi',
		4: 'Con le parentesi tonde',
		5: 'Con tonde e quadre',
		6: 'Con tonde, quadre e graffe',
		7: 'Problemi con le quattro operazioni',
	},
	'numeri-naturali-mcm-mcd': {
		1: 'I criteri di divisibilità',
		2: 'Scomporre in fattori primi',
		3: 'MCD e MCM di due numeri',
		4: 'MCD e MCM di tre numeri',
		5: "L'algoritmo di Euclide",
		6: 'Problemi con MCD e MCM',
	},
	'numeri-naturali-potenze': {
		1: 'Il valore di una potenza',
		2: 'Proprietà con la stessa base',
		3: 'Proprietà con lo stesso esponente',
		4: 'Riportare alla stessa base',
		5: 'Espressioni con le potenze',
	},
	'numeri-naturali-divisibilita': {
		1: 'Divisibile o no: fai la divisione',
		2: 'Un criterio alla volta',
		3: 'Tutti i criteri su un numero',
		4: 'Primo o composto',
		5: 'Scomporre in fattori primi',
		6: 'Divisori dalla scomposizione',
	},
	'numeri-interi-valore-assoluto': {
		1: 'Segno e appartenenza a ℕ e ℤ',
		2: 'Opposto e valore assoluto',
		3: 'Confrontare due interi',
		4: 'Ordinare gli interi',
		5: 'Ordinare opposti e valori assoluti',
		6: 'Gli interi tra due estremi',
	},
	'numeri-interi-operazioni': {
		1: 'Addizione di due interi',
		2: 'Sottrazione di due interi',
		3: 'Somma algebrica con più termini',
		4: 'Togliere le parentesi',
		5: 'La regola dei segni',
		6: 'Espressioni con tutte le operazioni',
	},
	'numeri-interi-potenze': {
		1: 'Potenze con base negativa',
		2: 'Il meno fuori e le potenze di −1',
		3: 'Una proprietà con base negativa',
		4: 'Basi opposte o stesso esponente',
		5: 'Espressioni con le potenze',
		6: 'Espressioni con le parentesi',
	},
	'numeri-razionali-frazioni': {
		1: 'La frazione di un numero',
		2: "Dalla parte all'intero",
		3: 'Propria, impropria o apparente',
		4: 'Frazioni equivalenti',
		5: 'Ridurre ai minimi termini',
		6: 'Ridurre con il segno meno',
	},
	'numeri-razionali-confronto-frazioni': {
		1: 'Frazioni equivalenti',
		2: 'Con lo stesso denominatore',
		3: 'Con lo stesso numeratore',
		4: 'Con il denominatore comune',
		5: 'Con le frazioni negative',
		6: 'Ordinare più frazioni',
	},
	'numeri-razionali-operazioni': {
		1: 'Somme con lo stesso denominatore',
		2: 'Somme con denominatori diversi',
		3: 'Frazioni negative e numeri interi',
		4: 'Il prodotto di due frazioni',
		5: 'La divisione tra frazioni',
		6: 'Due operazioni insieme',
		7: 'Problemi con le frazioni',
	},
	'numeri-razionali-potenze': {
		1: 'La potenza di una frazione',
		2: 'Base negativa e meno davanti',
		3: 'Esponente 0 ed esponente 1',
		4: "L'esponente negativo",
		5: 'Le proprietà delle potenze',
		6: 'Espressioni con le potenze',
	},
	'numeri-razionali-conversione': {
		1: 'Da decimale limitato a frazione',
		2: 'Da periodico semplice a frazione',
		3: 'Da periodico misto a frazione',
		4: 'Prevedere il tipo di decimale',
		5: 'Da frazione a decimale',
	},
	'numeri-razionali-espressioni': {
		1: "L'ordine delle operazioni",
		2: 'Una parentesi e i segni meno',
		3: 'Potenze con esponenti negativi',
		4: 'Frazioni di frazioni',
		5: 'Frazioni di frazioni con decimali',
		6: 'Tonde, quadre e graffe',
	},
	'numeri-razionali-proporzioni': {
		1: 'Il rapporto tra due numeri',
		2: 'Trovare la x con numeri interi',
		3: 'Con frazioni, decimali o negativi',
		4: 'Parte, percentuale e totale',
		5: 'Aumenti e sconti',
		6: "Variazioni una dopo l'altra",
		7: 'Problemi con le proporzioni',
	},
	'monomi-grado': {
		1: 'Grado rispetto a una lettera',
		2: 'Il grado complessivo',
		3: 'Quando il grado è zero',
		4: 'Una potenza nel coefficiente',
		5: 'Prima ridurre a forma normale',
		6: "Il grado dopo un'operazione",
	},
	'monomi-operazioni': {
		1: 'Sommare monomi simili',
		2: 'Somme con coefficienti frazionari',
		3: 'Somme con monomi non simili',
		4: 'Il prodotto di monomi',
		5: 'Il quoziente di monomi',
		6: 'La potenza di un monomio',
	},
	'monomi-mcm-mcd': {
		1: 'Due monomi con le stesse lettere',
		2: 'Lettere non in comune',
		3: 'Coefficienti negativi',
		4: 'Con tre monomi',
		5: 'Coefficienti frazionari',
	},
	'monomi-espressioni': {
		1: 'Prima moltiplica o dividi, poi somma',
		2: 'Prodotti e quozienti in fila',
		3: 'Con le potenze',
		4: 'Una parentesi con una somma',
		5: 'Tonde, quadre e graffe',
	},
	'equazioni-primo-grado': {
		1: 'Un solo termine con la x',
		2: 'La x in tutti e due i membri',
		3: 'Con le parentesi',
		4: 'La soluzione è una frazione',
		5: 'Con i denominatori',
		6: 'Impossibili e indeterminate',
		7: "Dal problema all'equazione",
	},
	'equazioni-secondo-grado': {
		1: 'Equazioni pure e spurie',
		2: 'Coefficiente di x² uguale a 1',
		3: 'Coefficiente di x² diverso da 1',
		4: 'Il delta non è un quadrato',
		5: 'Termini in tutti e due i membri',
		6: 'Il delta è zero o negativo',
	},
	'funzioni-iniettive-suriettive-biettive': {
		1: "L'immagine di una funzione",
		2: 'Funzioni date elemento per elemento',
		3: 'Funzioni date con una formula',
		4: 'Funzioni su ℝ e su [0, +∞)',
		5: 'Funzioni su ℤ, ℚ, ℕ e ℝ ∖ {0}',
		6: 'La funzione inversa',
	},
	// Physics, first year: from the "Nomi dei livelli" of specs/exercises/<id>.md.
	'fis-metodo-sperimentale': {
		1: 'Le fasi del metodo',
		2: 'Le variabili',
		3: 'Le prove da confrontare',
		4: "I dati e l'ipotesi",
	},
	'fis-grandezze-si': {
		1: 'Unità e prefissi',
		2: "Un prefisso e l'unità",
		3: 'Notazione scientifica',
		4: 'Tra due prefissi',
		5: 'Ore, minuti e km/h',
		6: 'Ordine di grandezza',
	},
	'fis-grandezze-derivate': {
		1: 'Unità di area e volume',
		2: 'Il volume dai dati',
		3: 'La densità',
		4: 'Densità e unità',
		5: 'Massa e volume dalla densità',
		6: 'Riconoscere il materiale',
	},
	'fis-strumenti-misura': {
		1: 'Portata e sensibilità',
		2: 'Scrivere e scegliere',
		3: 'Righello e cilindro',
		4: 'Calibro decimale',
		5: 'Calibro ventesimale',
	},
	'fis-errori-misura': {
		1: 'Casuale o sistematico',
		2: 'Correggere lo zero',
		3: 'Il bersaglio',
		4: 'Precisione e accuratezza',
		5: 'Come rimediare',
	},
	'fis-valore-medio': {
		1: 'Il valore medio',
		2: 'La semidispersione',
		3: 'Scrivere il risultato',
		4: 'Incertezza e sensibilità',
		5: 'Una misura da scartare',
		6: 'Misure compatibili',
	},
	'fis-incertezza-relativa': {
		1: 'Incertezza relativa',
		2: "Dalla relativa all'assoluta",
		3: 'Somme e differenze',
		4: 'Prodotti e quozienti',
		5: 'Potenze e numeri esatti',
		6: 'Formule con più passaggi',
	},
	'fis-cifre-significative': {
		1: 'Contare le cifre',
		2: 'Arrotondare',
		3: 'Somme e differenze',
		4: 'Prodotti e quozienti',
		5: 'Numeri esatti e più passaggi',
	},
	'fis-relazione-laboratorio': {
		1: 'Le parti della relazione',
		2: 'La tabella dei dati',
		3: 'Confronto con il valore atteso',
		4: 'Quale misura migliorare',
		5: "Cercare l'errore sistematico",
	},
	'fis-tabelle-grafici': {
		1: 'Leggere un punto del grafico',
		2: 'Scegliere la scala di un asse',
		3: 'Leggere tra i punti sulla retta',
		4: 'La misura da rifare',
	},
	'fis-proporzionalita-diretta': {
		1: 'La costante con la sua unità',
		2: 'Prevedere un valore',
		3: 'La pendenza dal grafico',
		4: 'Riconoscere il legame',
		5: 'Il termine noto',
	},
	'fis-proporzionalita-inversa': {
		1: 'La costante inversa con la sua unità',
		2: 'Prevedere con la proporzionalità inversa',
		3: 'Prevedere con la proporzionalità quadratica',
		4: 'Riconoscere la legge dalla tabella',
		5: 'Riconoscere la legge dal grafico',
	},
	'fis-scalari-vettori': {
		1: 'Scalare o vettoriale',
		2: 'Vettori uguali e opposti',
		3: 'La scala di un disegno',
		4: 'Distanza e spostamento su una retta',
		5: 'Lo spostamento sulla griglia',
	},
	'fis-operazioni-vettori': {
		1: 'Vettori sulla stessa retta',
		2: 'Il prodotto per un numero',
		3: 'Vettori perpendicolari',
		4: 'La somma sulla griglia',
		5: 'La differenza sulla griglia',
		6: 'Tre forze sulla griglia',
	},
	'fis-seno-coseno': {
		1: "Le componenti con l'angolo dall'asse x",
		2: "L'angolo dall'asse y",
		3: 'I segni nei quattro quadranti',
		4: 'Dalle componenti al vettore',
		5: "L'angolo negli altri quadranti",
		6: 'La somma per componenti',
	},
	'forze': {
		1: 'Leggere il dinamometro',
		2: 'Portata e sensibilità',
		3: 'Forze sulla stessa retta',
		4: 'Forze perpendicolari',
		5: 'Più forze su due direzioni',
	},
	'fis-forza-peso': {
		1: 'Il peso dalla massa',
		2: 'La massa dal dinamometro',
		3: 'La massa in grammi',
		4: 'Il peso su un altro corpo celeste',
		5: 'Da un corpo celeste a un altro',
	},
	'fis-forza-elastica': {
		1: 'La forza dalla legge di Hooke',
		2: "L'allungamento dalla forza",
		3: 'Centimetri e metri',
		4: 'Lunghezza e allungamento',
		5: 'La costante da una tabella',
		6: 'Una massa appesa',
	},
	'fis-attrito': {
		1: "L'attrito dinamico",
		2: 'Il coefficiente di attrito',
		3: "Quanto vale l'attrito",
		4: 'La forza premente non è il peso',
		5: 'Un libro contro la parete',
	},
	'fis-equilibrio-punto': {
		1: "La reazione del piano d'appoggio",
		2: 'La forza equilibrante',
		3: 'Due fili con lo stesso angolo',
		4: 'Un filo orizzontale e uno inclinato',
		5: 'Due fili con angoli diversi',
		6: 'Quanto si può tendere un filo',
	},
	'fis-equilibrio-piano-inclinato': {
		1: 'Le componenti del peso',
		2: 'Altezza e lunghezza',
		3: "L'inclinazione dalla forza",
		4: "L'angolo limite",
		5: 'Fermo o scivola',
	},
	'fis-momento-forza': {
		1: 'Il momento con il braccio',
		2: 'Dal momento alla forza o al braccio',
		3: 'Il momento di una forza obliqua',
		4: 'Il momento totale con il segno',
		5: 'Il momento di una coppia',
	},
	'fis-equilibrio-corpo-rigido': {
		1: "L'asta sul fulcro",
		2: 'La reazione del fulcro',
		3: "L'asta con il suo peso",
		4: 'La trave su due appoggi',
		5: 'La trave con il suo peso',
	},
	'fis-leve': {
		1: 'Il genere della leva',
		2: 'Vantaggiosa o svantaggiosa',
		3: 'La forza motrice',
		4: 'Il braccio e il fulcro',
		5: 'Le carrucole',
	},
	'fis-baricentro': {
		1: 'Il baricentro di due corpi',
		2: 'Il baricentro di tre corpi',
		3: 'Stabile, instabile o indifferente',
		4: "L'angolo di ribaltamento",
		5: 'Quanto può sporgere',
	},
	'fis-pressione': {
		1: "La pressione dalla forza e dall'area",
		2: "L'area in centimetri quadrati",
		3: 'Il peso come forza premente',
		4: "La forza o l'area dalla pressione",
		5: 'Il blocco appoggiato su una faccia',
	},
	'fis-legge-pascal': {
		1: 'La pressione trasmessa',
		2: 'La forza sul pistone grande',
		3: 'La forza per reggere un carico',
		4: 'I diametri dei pistoni',
		5: 'Gli spostamenti dei pistoni',
	},
	'fis-legge-stevino': {
		1: 'La pressione idrostatica',
		2: 'Profondità in centimetri',
		3: 'La pressione totale',
		4: 'La profondità dalla superficie',
		5: 'La profondità dalla pressione',
		6: 'Il tubo a U',
	},
	'fis-pressione-atmosferica': {
		1: 'Le unità della pressione',
		2: 'Millimetri di mercurio ed ettopascal',
		3: "La forza dell'aria su una superficie",
		4: 'La colonna di un barometro',
		5: 'La ventosa e gli emisferi',
	},
	'fis-archimede': {
		1: 'La spinta su un corpo immerso',
		2: 'Il peso apparente',
		3: 'Dalle letture dei due dinamometri',
		4: 'La parte immersa di un corpo che galleggia',
		5: 'La densità dalla linea di galleggiamento',
		6: 'Il carico massimo',
	},
	'ottica-geometrica': {
		1: 'Il tempo della luce',
		2: 'Chilometri e minuti',
		3: "L'anno luce",
		4: "L'ombra di un cartoncino",
		5: 'La camera oscura',
		6: "L'ombra al contrario",
	},
	'riflessione': {
		1: "L'angolo tra i due raggi",
		2: "Dall'angolo con lo specchio",
		3: "L'immagine nello specchio piano",
		4: 'Lo specchio per vedersi per intero',
		5: 'Due specchi ad angolo',
	},
	'fis-specchi-sferici': {
		1: 'Il fuoco e il raggio di curvatura',
		2: "L'immagine reale di uno specchio concavo",
		3: "Altezza e verso dell'immagine",
		4: "L'immagine virtuale dello specchio concavo",
		5: 'Lo specchio convesso',
		6: "La distanza focale dall'immagine",
	},
	'fis-rifrazione': {
		1: "L'indice e la velocità della luce",
		2: "L'angolo di rifrazione",
		3: "L'indice dagli angoli",
		4: 'Verso un mezzo meno rifrangente',
		5: "L'angolo limite",
		6: 'Esce o si riflette tutto?',
	},
	'fis-dispersione': {
		1: 'I colori nel prisma',
		2: 'Il colore dei corpi in luce colorata',
		3: 'La sintesi additiva',
		4: 'La sintesi sottrattiva',
		5: 'Corpi gialli, ciano e magenta',
		6: 'Di quanto si separano i colori',
	},
	'fis-lenti': {
		1: 'Il potere diottrico',
		2: "L'immagine reale",
		3: "L'ingrandimento",
		4: "L'immagine virtuale",
		5: 'La lente divergente',
		6: 'Dalle distanze alla distanza focale',
	},
	'fis-strumenti-ottici': {
		1: 'Cannocchiale e microscopio',
		2: 'Le lenti per la miopia',
		3: "Le lenti per l'ipermetropia",
		4: 'La macchina fotografica',
		5: "La lente d'ingrandimento",
		6: "Il potere dell'occhio",
	},
	// Physics, second year.
	'fis-punto-materiale': {
		1: 'Lo spostamento',
		2: "L'intervallo di tempo",
		3: 'Andata e ritorno',
		4: 'La tabella della legge oraria',
	},
	'velocita': {
		1: 'La velocità media',
		2: "Chilometri all'ora e metri al secondo",
		3: 'Distanza e tempo',
		4: 'Velocità media e velocità scalare media',
		5: 'Un viaggio in due tratti',
	},
	'fis-moto-rettilineo-uniforme': {
		1: 'La legge oraria',
		2: "L'istante di arrivo",
		3: 'Il grafico spazio-tempo',
		4: "L'area sotto il grafico velocità-tempo",
		5: "L'incontro",
	},
	'fis-accelerazione': {
		1: "L'accelerazione media",
		2: "Con i chilometri all'ora",
		3: 'La frenata',
		4: 'Velocità finale e tempo',
		5: "Il segno dell'accelerazione",
	},
	'moto-uniforme-accelerato': {
		1: 'La velocità dopo un tempo',
		2: 'Partenza da fermo',
		3: 'La legge oraria',
		4: 'Senza il tempo',
		5: 'La frenata',
		6: 'Lo spazio di arresto',
	},
	'fis-grafico-velocita-tempo': {
		1: "L'accelerazione dalla pendenza",
		2: "Lo spostamento dall'area",
		3: 'Un viaggio a tratti',
		4: 'Le aree con il segno',
		5: 'La velocità media',
	},
	'fis-caduta-libera': {
		1: 'Dal tempo di caduta',
		2: 'Il tempo di caduta',
		3: "La velocità d'arrivo",
		4: "Il lancio verso l'alto",
		5: 'La velocità con il segno',
		6: 'Il lancio da un balcone',
	},
	'fis-spostamento-velocita-piano': {
		1: 'Lo spostamento dalle coordinate',
		2: 'La velocità media',
		3: 'Velocità media e velocità scalare media',
		4: 'Le componenti della velocità',
		5: 'Lo spostamento in un intervallo',
	},
	'fis-composizione-moti': {
		1: 'Velocità nella stessa direzione',
		2: 'Con la corrente e contro',
		3: 'Velocità perpendicolari',
		4: 'Attraversare il fiume',
		5: 'La prua controcorrente',
	},
	'fis-moto-circolare-uniforme': {
		1: 'Periodo e frequenza',
		2: 'La velocità tangenziale',
		3: 'La velocità angolare',
		4: 'Velocità tangenziale e angolare',
		5: 'Due punti sulla stessa ruota',
	},
	'fis-accelerazione-centripeta': {
		1: 'Dalla velocità e dal raggio',
		2: 'Con la velocità in km/h',
		3: 'Dal periodo',
		4: 'La velocità massima in curva',
		5: "Come cambia l'accelerazione",
	},
	'fis-moto-armonico': {
		1: 'Ampiezza e periodo',
		2: 'La posizione a un istante',
		3: 'La velocità massima',
		4: "L'accelerazione massima",
		5: "Dalla velocità e dall'accelerazione massime",
	},
	'fis-primo-principio': {
		1: 'Velocità costante in verticale',
		2: "L'attrito a velocità costante",
		3: 'La maniglia inclinata',
		4: 'Due funi perpendicolari',
	},
	'leggi-newton': {
		1: "L'accelerazione",
		2: 'La forza o la massa',
		3: 'Due forze opposte',
		4: 'Due forze perpendicolari',
		5: "Con l'attrito",
		6: 'Forza e velocità',
	},
	'fis-terzo-principio': {
		1: 'Azione e reazione',
		2: 'Stessa forza, accelerazioni diverse',
		3: "Dall'accelerazione di uno a quella dell'altro",
		4: "L'accelerazione della Terra",
		5: 'Il razzo',
	},
	'fis-diagramma-corpo-libero': {
		1: 'Quante forze',
		2: 'La fune inclinata',
		3: 'La reazione del pavimento',
		4: "La fune inclinata con l'attrito",
		5: 'Quanto segna la bilancia',
		6: "L'accelerazione dell'ascensore",
	},
	'fis-piano-inclinato': {
		1: "L'accelerazione senza attrito",
		2: 'Tempo e velocità in fondo',
		3: "L'accelerazione con l'attrito",
		4: 'Il lancio in salita',
		5: "In salita con l'attrito",
	},
	'fis-corpi-collegati': {
		1: "L'accelerazione di due carrelli",
		2: 'La tensione tra i carrelli',
		3: 'Il pesetto e la carrucola',
		4: 'La tensione del filo appeso',
		5: "Con l'attrito sul tavolo",
		6: 'La macchina di Atwood',
	},
	'fis-moto-proiettili': {
		1: 'Il tempo di volo',
		2: 'La gittata',
		3: 'Il problema inverso',
		4: "La velocità all'arrivo",
		5: "L'angolo all'arrivo",
	},
	'fis-forza-centripeta': {
		1: 'La forza centripeta',
		2: 'Dal periodo',
		3: "L'auto in curva",
		4: 'Il disco e il pesetto',
		5: 'In cima al giro',
	},
	'fis-pendolo-molla': {
		1: 'Il periodo della molla',
		2: 'Il periodo del pendolo',
		3: 'Che cosa cambia il periodo',
		4: 'Dal periodo alla molla o al filo',
		5: 'Misurare g',
	},
	'lavoro': {
		1: 'Forza e spostamento paralleli',
		2: 'La forza inclinata',
		3: 'Il segno del lavoro',
		4: 'Il lavoro totale',
		5: "La fune inclinata con l'attrito",
		6: "L'area sotto il grafico",
	},
	'fis-potenza': {
		1: 'Lavoro e tempo',
		2: 'Sollevare un carico',
		3: 'Potenza e velocità',
		4: 'La velocità in km/h',
		5: 'Il kilowattora',
	},
	'fis-energia-cinetica': {
		1: "L'energia cinetica",
		2: 'La velocità in km/h',
		3: "La velocità dall'energia",
		4: "Il teorema dell'energia cinetica",
		5: 'Lo spazio di frenata',
	},
	'fis-energia-potenziale': {
		1: "L'energia potenziale gravitazionale",
		2: 'Il livello di riferimento',
		3: 'Il lavoro del peso',
		4: "L'energia potenziale elastica",
		5: "La deformazione dall'energia",
	},
	'energia': {
		1: 'La caduta libera',
		2: "L'altezza massima",
		3: "Da un punto all'altro della pista",
		4: 'La molla che lancia un blocco',
		5: 'La molla e la salita',
	},
	'fis-energia-totale': {
		1: "Il lavoro dell'attrito",
		2: 'La velocità dopo un tratto con attrito',
		3: "L'energia dissipata",
		4: "La rampa con l'attrito",
		5: 'Il rendimento',
		6: "L'energia spesa",
	},
	'fis-temperatura': {
		1: 'Celsius e kelvin',
		2: 'Le differenze di temperatura',
		3: 'Da Celsius a Fahrenheit',
		4: 'Da Fahrenheit a Celsius',
		5: 'La taratura del termometro',
	},
	'fis-dilatazione-termica': {
		1: "L'allungamento",
		2: 'La temperatura finale',
		3: 'Il coefficiente di dilatazione',
		4: 'Un liquido che trabocca',
		5: 'Il volume di un solido',
	},
	'calore': {
		1: "Scaldare l'acqua",
		2: 'Altre sostanze, anche che si raffreddano',
		3: 'La temperatura finale',
		4: 'Il calore specifico da una misura',
		5: "La pentola e l'acqua",
		6: 'Le calorie',
	},
	'fis-equilibrio-termico': {
		1: 'Il calore scambiato',
		2: 'Acqua calda e acqua fredda',
		3: "Un metallo nell'acqua",
		4: 'Il dato mancante',
		5: 'Il calore specifico',
		6: "L'equivalente in acqua",
	},
	'fis-propagazione-calore': {
		1: 'Il calore che passa ogni secondo',
		2: 'Le unità da convertire',
		3: 'Il calore in un tempo',
		4: 'Lo spessore o la conducibilità',
		5: 'Due strati a confronto',
	},
	'fis-passaggi-stato': {
		1: 'Il calore latente',
		2: 'La massa dal calore',
		3: 'Due tappe',
		4: 'Tre tappe',
		5: 'Il grafico temperatura-calore',
		6: "Ghiaccio nell'acqua",
	},
	// Physics, third year (docs/lezioni/fisica/brief-terzo-anno.md).
	'fis-prodotto-scalare-vettoriale': {
		1: 'Il prodotto scalare con un angolo acuto',
		2: "L'angolo ottuso e il segno",
		3: 'Il prodotto scalare dalle componenti',
		4: "L'angolo tra due vettori",
		5: 'Il modulo del prodotto vettoriale',
		6: 'Il prodotto vettoriale nel piano: esce o entra',
		7: 'Le componenti nello spazio',
	},
	'fis-sistemi-non-inerziali': {
		1: 'Inerziale o no',
		2: "Il pallone visto dall'autobus",
		3: 'Il tempo per arrivare alla parete',
		4: 'Il pendolo nel veicolo che accelera',
		5: 'La caduta in ascensore',
	},
	'fis-trasformazioni-galileo': {
		1: "Da un sistema all'altro: la posizione",
		2: 'La velocità di un veicolo vista da un altro',
		3: 'Raggiungersi e incontrarsi',
		4: "La pioggia vista dall'auto",
		5: 'Velocità per componenti',
		6: 'La palla lanciata sul treno',
	},
	'fis-principio-relativita-galileo': {
		1: 'La stessa accelerazione',
		2: 'La stessa forza',
		3: 'Lo stesso esperimento sul treno',
		4: 'Invariante o relativa',
		5: "Il sasso dall'albero visto dalla riva",
		6: "L'energia cinetica vista da terra",
	},
	'fis-forze-apparenti': {
		1: 'La forza apparente',
		2: 'La valigia che scivola',
		3: 'Il pacco in ascensore',
		4: 'La forza centrifuga',
		5: 'La centrifuga dal periodo o dai giri al minuto',
		6: 'La moneta sul piatto che ruota',
		7: 'Da che parte devia la forza di Coriolis',
	},
	'fis-lancio-obliquo': {
		1: 'Le componenti della velocità iniziale',
		2: "L'altezza massima",
		3: 'Il tempo di volo',
		4: 'La gittata',
		5: 'La velocità dalla gittata',
		6: 'Il lancio da una quota',
	},
	'fis-lavoro-forza-variabile': {
		1: "L'area sotto il grafico",
		2: "Le aree sotto l'asse",
		3: 'La forza media',
		4: 'Il lavoro della forza elastica',
		5: 'La velocità dal grafico',
		6: 'La molla che ferma il carrello',
	},
	'fis-forze-conservative-energia': {
		1: "L'attrito lungo due cammini",
		2: 'Il lavoro al ritorno',
		3: "Dal lavoro all'energia potenziale",
		4: 'Il lavoro di una molla',
		5: "L'energia cinetica dal grafico",
		6: 'La forza dal grafico',
	},
	'fis-bilancio-energia': {
		1: 'Il bilancio con i lavori dati',
		2: 'Discesa liscia e tratto con attrito',
		3: 'La molla e il pavimento con attrito',
		4: 'La rampa con attrito e la molla',
		5: 'La cassa tirata in salita',
		6: 'La forza media di una resistenza',
	},
	'fis-quantita-moto-def': {
		1: 'La quantità di moto di un corpo',
		2: 'Con le unità da convertire',
		3: 'La stessa quantità di moto',
		4: 'La variazione in un rimbalzo',
		5: 'La quantità di moto totale su una retta',
		6: 'La quantità di moto totale nel piano',
		7: 'La forza dalla variazione della quantità di moto',
	},
	'fis-impulso': {
		1: "L'impulso di una forza costante",
		2: 'La velocità dopo una spinta',
		3: 'La forza media che ferma un corpo',
		4: 'La forza media in un rimbalzo',
		5: "L'impulso dal grafico",
		6: 'La velocità dal grafico',
		7: 'La forza del suolo in un atterraggio',
	},
	'fis-conservazione-quantita-moto': {
		1: 'Due corpi fermi che si spingono',
		2: 'Il rinculo di un fucile',
		3: 'Un sistema già in moto che si separa',
		4: 'Tre frammenti nel piano',
	},
	'fis-urti-anelastici': {
		1: 'I due corpi restano attaccati',
		2: 'Urto frontale con i corpi attaccati',
		3: "L'energia dissipata",
		4: "I corpi si separano dopo l'urto",
		5: 'Il pendolo balistico',
		6: 'Urto ad angolo retto',
	},
	'fis-urti-elastici': {
		1: 'La velocità del corpo colpito',
		2: 'Il primo corpo prosegue o torna indietro',
		3: 'Due corpi che si vengono incontro',
		4: 'Le direzioni dopo un colpo di striscio',
		5: 'Le velocità dopo un colpo di striscio',
	},
	'fis-centro-massa': {
		1: 'Il centro di massa di due corpi',
		2: 'Tre corpi su una retta',
		3: 'Tre corpi nel piano',
		4: 'La velocità del centro di massa',
		5: 'Camminare su una barca',
	},
	'fis-cinematica-rotazionale': {
		1: 'Accelerazione angolare media',
		2: 'Dai giri al minuto ai radianti al secondo',
		3: 'Velocità angolare nel tempo',
		4: 'Angolo descritto',
		5: 'Quanti giri fa',
		6: 'Senza il tempo',
		7: 'Accelerazione tangenziale e centripeta',
	},
	'fis-momento-inerzia': {
		1: 'Una massa che gira',
		2: 'Più masse attorno a un asse',
		3: 'Lo stesso corpo, un altro asse',
		4: 'Dischi, anelli, sfere e aste',
		5: 'Asse spostato: Huygens-Steiner',
		6: 'Corpi fatti di più parti',
	},
	'fis-dinamica-rotazionale': {
		1: "Momento, momento d'inerzia e accelerazione angolare",
		2: 'Una forza tangente a un disco',
		3: 'Una forza obliqua',
		4: 'Frenare e avviare una ruota',
		5: 'Il secchio appeso alla carrucola',
		6: 'La macchina di Atwood con la carrucola pesante',
	},
	'fis-energia-rotazionale': {
		1: "L'energia di un corpo che ruota",
		2: "L'energia di rotazione dalla forma del corpo",
		3: "L'energia di un corpo che rotola",
		4: 'La velocità in fondo alla discesa',
		5: "L'accelerazione lungo il piano inclinato",
		6: "L'altezza raggiunta in salita",
	},
	'fis-momento-angolare-def': {
		1: 'Una particella in moto circolare',
		2: "Con l'angolo tra posizione e velocità",
		3: 'Un corpo rigido che ruota',
		4: 'Il momento angolare dalla forma del corpo',
		5: 'Il momento che fa accelerare',
		6: 'Il tempo di frenata',
	},
	'fis-conservazione-momento-angolare': {
		1: 'Un corpo che cambia forma',
		2: "Due masse che si avvicinano all'asse",
		3: 'Un disco cade su un altro',
		4: 'Un salto sulla giostra',
		5: "Dal perielio all'afelio",
		6: "L'energia cinetica dopo il cambio di forma",
	},
	'fis-sistemi-cosmologici': {
		1: "Avanti o indietro sull'epiciclo",
		2: 'Le velocità da raggi e periodi',
		3: "La distanza dall'elongazione",
		4: 'Il periodo di un pianeta esterno',
		5: 'Il periodo di un pianeta interno',
	},
	'fis-leggi-keplero': {
		1: 'Il semiasse maggiore',
		2: "L'eccentricità",
		3: 'Più veloce al perielio',
		4: 'Il periodo dal semiasse',
		5: 'Il semiasse dal periodo',
		6: 'Le lune di un pianeta',
	},
	'fis-gravitazione-universale': {
		1: 'La forza tra due corpi',
		2: 'Se cambia la distanza',
		3: 'Tra corpi celesti',
		4: 'Un satellite a una certa quota',
		5: 'La gravità su un altro pianeta',
		6: 'Tre corpi allineati',
	},
	'fis-campo-gravitazionale': {
		1: 'Il campo dalla forza su una massa',
		2: 'Il campo alla superficie di un pianeta',
		3: 'Il campo a una certa quota',
		4: 'Ragionare con i rapporti',
		5: 'Il campo di due corpi',
	},
	'fis-satelliti': {
		1: 'La velocità orbitale dal raggio',
		2: 'La velocità orbitale dalla quota',
		3: "Il periodo dell'orbita",
		4: 'Due orbite a confronto',
		5: 'La massa del corpo centrale',
		6: "Il raggio dell'orbita dal periodo",
	},
	'fis-energia-gravitazionale': {
		1: "L'energia potenziale, con il segno",
		2: 'Dalla superficie a una quota',
		3: 'Fin dove arriva un proiettile',
		4: "L'energia di un satellite in orbita",
		5: 'La velocità di fuga',
	},
	'fis-portata-continuita': {
		1: 'La portata da volume e tempo',
		2: 'La portata da sezione e velocità',
		3: 'Il tubo che cambia sezione',
		4: 'Il tubo con i diametri',
		5: 'I litri al minuto di un tubo',
		6: 'Il tubo che si divide',
	},
	'fis-bernoulli': {
		1: 'Il calo di pressione nella strozzatura',
		2: 'La pressione nella strozzatura',
		3: 'Il tubo che sale',
		4: 'La strozzatura con i diametri',
		5: 'Più in alto e più stretto',
	},
	'fis-torricelli-venturi': {
		1: 'La velocità di uscita dal foro',
		2: 'La profondità del foro',
		3: 'Dove arriva il getto',
		4: 'Il tubo di Venturi',
		5: 'Il tubo di Pitot',
		6: 'La portanza',
	},
	'fis-viscosita': {
		1: 'La forza di Stokes',
		2: 'La velocità limite dalla massa',
		3: 'La gocciolina nella nebbia',
		4: 'La velocità limite con Archimede',
		5: 'La viscosità dalla velocità limite',
	},
	'fis-legge-boyle': {
		1: 'La pressione sotto il pistone',
		2: 'La pressione finale',
		3: 'Dove si ferma il pistone',
		4: 'Sulla stessa isoterma',
		5: 'La bolla nel lago',
	},
	'fis-leggi-gay-lussac': {
		1: 'Il volume partendo da 0 °C',
		2: 'La temperatura dalla pressione',
		3: 'Il volume con i kelvin',
		4: 'La temperatura finale della bombola',
		5: 'Di quanto sale il pistone',
	},
	'fis-gas-perfetto': {
		1: "Da uno stato all'altro",
		2: 'Le moli di gas',
		3: 'La pressione, con litri e gradi Celsius',
		4: 'Il numero di molecole',
		5: 'Il gas uscito dalla bombola',
	},
	'fis-teoria-cinetica': {
		1: 'Quante molecole ci sono',
		2: 'La massa di una molecola',
		3: 'La velocità quadratica media di poche molecole',
		4: 'La pressione dal modello',
		5: 'La velocità dalla pressione e dalla densità',
		6: 'Come cambia la pressione',
	},
	'fis-temperatura-microscopica': {
		1: "L'energia cinetica media",
		2: 'Dai gradi Celsius',
		3: "La temperatura dall'energia cinetica media",
		4: 'La velocità quadratica media',
		5: 'Il rapporto tra due velocità',
		6: 'La temperatura dalla velocità',
	},
	'fis-sistemi-termodinamici': {
		1: 'Aperto, chiuso o isolato',
		2: 'Lo stato nel piano pressione-volume',
		3: 'Due gas e una parete',
		4: 'Il principio zero',
		5: 'Dove si ferma il pistone',
	},
	'fis-energia-interna': {
		1: "L'energia interna di un gas",
		2: 'Di quanto cambia',
		3: 'Dalla pressione e dal volume',
		4: 'Da uno stato a un altro',
		5: "La temperatura dall'energia interna",
		6: 'Due gas in un recipiente isolato',
	},
	'fis-lavoro-termodinamico': {
		1: 'Il lavoro a pressione costante',
		2: 'Litri, kilopascal e atmosfere',
		3: 'Una compressione: il segno del lavoro',
		4: 'Il lavoro dal grafico: un segmento',
		5: 'Il lavoro dal grafico: due tratti',
		6: 'Il lavoro di un ciclo',
	},
	'principi-termo': {
		1: 'Calore assorbito e lavoro compiuto',
		2: 'I segni di calore e lavoro',
		3: 'Trovare il calore o il lavoro',
		4: 'Il lavoro va calcolato',
		5: 'La variazione di temperatura',
		6: 'Cicli, recipienti rigidi, nessuno scambio di calore',
	},
	'fis-trasformazioni-termodinamiche': {
		1: 'Il calore a volume costante',
		2: 'Il lavoro a pressione costante',
		3: 'Calore ed energia interna a pressione costante',
		4: "Il lavoro di un'espansione isoterma",
		5: 'La compressione isoterma',
		6: 'Un ciclo con tre trasformazioni',
	},
	'fis-calori-molari': {
		1: 'Il calore a volume costante',
		2: 'Il calore a pressione costante',
		3: 'I gas biatomici',
		4: "L'aumento di temperatura",
		5: 'Lavoro ed energia interna',
		6: 'Dai grammi alle moli',
	},
	'fis-trasformazione-adiabatica': {
		1: 'Il lavoro dalla temperatura',
		2: 'La pressione finale',
		3: 'La temperatura finale',
		4: 'Il volume finale',
		5: 'Temperature in gradi Celsius',
		6: 'Il lavoro da pressioni e volumi',
	},
	'fis-macchine-termiche': {
		1: 'Il bilancio di un ciclo',
		2: 'Il rendimento dal lavoro',
		3: 'Il rendimento dai due calori',
		4: 'Dal rendimento ai calori',
		5: 'La potenza del motore',
		6: 'Il ciclo rettangolare',
	},
	'fis-enunciati-kelvin-clausius': {
		1: 'Il verso del calore',
		2: 'Tutto il calore in lavoro?',
		3: 'Che cosa viola un dispositivo',
		4: 'Se fosse falso Clausius',
		5: 'Se fosse falso Kelvin',
	},
	'fis-ciclo-carnot': {
		1: 'Il rendimento con le temperature in kelvin',
		2: 'Le temperature in gradi Celsius',
		3: 'Lavoro e calore ceduto',
		4: 'La temperatura di una sorgente',
		5: 'La macchina può esistere?',
		6: 'Il lavoro di un ciclo di Carnot',
	},
	'fis-frigoriferi': {
		1: 'Il coefficiente di un frigorifero',
		2: 'Dal calore ceduto',
		3: 'La pompa di calore',
		4: 'Il coefficiente massimo',
		5: 'Il lavoro per raffreddare',
		6: 'Fare il ghiaccio',
	},
	'fis-entropia': {
		1: 'Una sorgente che scambia calore',
		2: "L'entropia in un passaggio di stato",
		3: 'Un gas a temperatura costante',
		4: 'Un corpo che si scalda o si raffredda',
		5: "L'entropia dell'universo",
		6: 'Una macchina reale',
	},
	'fis-entropia-disordine': {
		1: 'Contare i microstati',
		2: 'La probabilità di un macrostato',
		3: 'Il macrostato più probabile',
		4: "L'entropia dai microstati",
		5: "L'espansione libera",
	},
	// Chemistry, first two years: generators in TypeScript (docs/lezioni/chimica/README.md, "Il biennio").
	'chim-grandezze-si': {
		1: 'Unità e simboli',
		2: "Un prefisso e l'unità",
		3: 'Notazione scientifica',
		4: 'Tra due prefissi',
		5: 'I volumi',
		6: 'Densità e concentrazioni',
	},
	'chim-massa-volume-densita': {
		1: 'La densità',
		2: 'Massa o volume',
		3: 'Unità diverse',
		4: 'La pesata per differenza',
		5: 'Il volume per immersione',
		6: 'Galleggia o affonda',
	},
	'chim-temperatura-calore': {
		1: 'Celsius e kelvin',
		2: 'Differenze di temperatura',
		3: 'Il calore',
		4: 'La temperatura finale',
		5: 'Il calorimetro',
		6: "L'equilibrio termico",
	},
	'chim-errori-cifre-significative': {
		1: 'Contare le cifre',
		2: 'Arrotondare',
		3: 'Valore medio e incertezza',
		4: 'Somme e differenze',
		5: 'Prodotti e quozienti',
		6: "L'incertezza relativa",
	},
	'chim-stati-aggregazione': {
		1: 'Le proprietà dei tre stati',
		2: 'Lo stato a una temperatura',
		3: 'La temperatura in kelvin',
		4: 'Quale sostanza',
		5: 'Il volume cambia con lo stato',
	},
	'chim-modello-particellare': {
		1: 'Le particelle nei tre stati',
		2: 'Spiegare un fenomeno',
		3: 'Dai gradi Celsius ai kelvin',
		4: 'Chi si agita di più',
	},
	'chim-sostanze-miscugli': {
		1: 'Sostanza pura o miscuglio',
		2: 'Omogeneo o eterogeneo',
		3: 'Le particelle',
		4: 'La prova della fusione',
		5: 'Fasi e componenti',
	},
	'chim-soluzioni-percentuale': {
		1: 'La percentuale in massa',
		2: 'Soluto e solvente',
		3: 'Massa su volume',
		4: 'La percentuale in volume',
		5: 'Quanto soluto serve',
		6: 'La solubilità',
	},
	'chim-separazione-miscugli': {
		1: 'Il metodo giusto',
		2: 'La proprietà sfruttata',
		3: 'La distillazione',
		4: 'Il fattore di ritenzione',
		5: 'Separare in più passi',
	},
	'chim-passaggi-stato': {
		1: 'Il nome del passaggio',
		2: 'Assorbire o cedere calore',
		3: 'Lo stato a una temperatura',
		4: "Da una temperatura a un'altra",
		5: 'Evaporazione, ebollizione e pressione',
	},
	'chim-curve-riscaldamento': {
		1: 'Le soste termiche',
		2: "Che cosa c'è nel recipiente",
		3: 'Sostanza pura o miscuglio',
		4: 'Riconoscere la sostanza',
		5: 'La curva di raffreddamento',
		6: 'La durata della sosta',
	},
	'chim-trasformazioni-fisiche-chimiche': {
		1: 'Fisica o chimica',
		2: 'Reagenti e prodotti',
		3: 'Gli indizi',
		4: "L'indizio non basta",
	},
	'chim-elementi-composti': {
		1: 'I simboli chimici',
		2: 'Elemento o composto',
		3: 'Elemento, composto o miscuglio',
		4: 'Gli elementi di una formula',
	},
	'chim-legge-lavoisier': {
		1: 'Reagenti e prodotto',
		2: 'La massa mancante',
		3: 'Il recipiente aperto',
		4: 'Il becher e il vetrino',
		5: 'Il reagente che avanza',
	},
	'chim-legge-proust': {
		1: 'Il rapporto di combinazione',
		2: 'La massa che si combina',
		3: 'La composizione percentuale',
		4: 'Il reagente in eccesso',
		5: 'Il composto con un reagente in eccesso',
	},
	'chim-legge-proporzioni-multiple': {
		1: 'La stessa massa',
		2: 'Masse diverse',
		3: 'Dalla massa del composto',
		4: 'Dalle percentuali',
		5: 'La formula del secondo',
	},
	'chim-teoria-atomica-dalton': {
		1: 'I postulati',
		2: 'Quale legge',
		3: 'Che cosa resta oggi',
		4: 'Contare gli atomi',
		5: 'Le masse relative',
	},
	'chim-atomi-molecole-ioni': {
		1: 'Atomo, molecola o ione',
		2: "Dall'atomo allo ione",
		3: 'Gli elettroni di uno ione',
		4: 'Il nome dello ione',
		5: 'Di che particelle è fatta',
	},
	'chim-formula-chimica': {
		1: 'Leggere gli indici',
		2: 'Tutti gli atomi',
		3: 'Il coefficiente',
		4: 'Le parentesi',
		5: 'Gli idrati',
		6: 'La formula dagli ioni',
	},
	'chim-teoria-cinetica': {
		1: 'Celsius e kelvin',
		2: 'Le ipotesi del modello',
		3: 'Temperatura ed energia',
		4: 'Particelle leggere e pesanti',
		5: 'Quale campione',
	},
	'chim-pressione-gas': {
		1: "Da un'unità all'altra",
		2: 'Millimetri di mercurio e kilopascal',
		3: 'Forza e pressione sul pistone',
		4: 'Il manometro a tubo aperto',
		5: 'Pressione assoluta e relativa',
	},
	'chim-legge-boyle': {
		1: 'La pressione finale',
		2: 'Il volume finale',
		3: 'Unità diverse',
		4: 'Dal grafico pressione-volume',
		5: 'La bolla del sub',
		6: 'Di quanto per cento',
	},
	'chim-legge-charles-gay-lussac': {
		1: 'Charles, in kelvin',
		2: 'Charles, in gradi Celsius',
		3: 'Gay-Lussac',
		4: 'La temperatura finale',
		5: 'Dal grafico volume-temperatura',
	},
	'chim-equazione-generale-gas': {
		1: 'Quale legge',
		2: 'Cambia tutto',
		3: 'Gradi Celsius e millilitri',
		4: 'La temperatura finale',
		5: 'Le condizioni normali',
	},
	'chim-principio-avogadro': {
		1: 'I volumi nelle reazioni',
		2: 'Stesso volume, stesse particelle',
		3: 'La massa delle molecole',
		4: 'Quale gas è',
		5: 'La formula dai volumi',
	},
	'chim-formula-minima': {
		1: 'Dalla formula molecolare',
		2: 'La percentuale in massa',
		3: 'Dalla composizione alla formula minima',
		4: 'Quando serve moltiplicare',
		5: 'La formula molecolare',
	},
	'chim-volume-molare': {
		1: 'Moli e volume',
		2: 'Massa e volume',
		3: 'Molecole e atomi in un volume',
		4: 'La densità di un gas',
		5: 'La formula di un gas',
	},
	'gas-ideali': {
		1: 'Il volume di un gas',
		2: 'La pressione da una massa',
		3: 'Con le unità del SI',
		4: 'La temperatura',
		5: 'La massa molare',
		6: 'La densità di un gas',
	},
	'chim-pressioni-parziali': {
		1: 'La legge di Dalton',
		2: 'La frazione molare',
		3: "Con l'equazione di stato",
		4: 'Una miscela in grammi',
		5: "Un gas raccolto sopra l'acqua",
	},
	'chim-natura-elettrica': {
		1: 'Attrazione e repulsione',
		2: 'Conduttori e isolanti',
		3: 'Lo strofinio',
		4: 'Contare gli elettroni',
		5: 'Due sfere a contatto',
	},
	'particelle-fondamentali': {
		1: 'Le tre particelle',
		2: 'Chi e quando',
		3: 'La carica di un gruppo di particelle',
		4: 'Le masse',
		5: 'Le gocce di Millikan',
	},
	'chim-thomson-rutherford': {
		1: 'I modelli atomici',
		2: "La lamina d'oro",
		3: 'Atomo e nucleo',
		4: 'Il modello in scala',
		5: 'Il volume del nucleo',
	},
	'numero-massa': {
		1: "Le particelle dell'atomo",
		2: 'Il simbolo',
		3: 'Gli ioni',
		4: 'Gli isotopi',
		5: 'La massa atomica media',
		6: "L'abbondanza di un isotopo",
	},
	'chim-tavola-mendeleev': {
		1: 'Storia e struttura della tavola',
		2: 'Una massa che manca',
		3: 'Massa e numero atomico',
		4: 'Formule per analogia',
	},
	'chim-orbitali-numeri-quantici': {
		1: 'Livelli, sottolivelli e nomi',
		2: 'Quanti orbitali',
		3: 'Terne che esistono',
		4: 'I nodi di un orbitale',
		5: 'Quanti elettroni',
	},
	'chim-luce-spettri': {
		1: 'Onde e regioni dello spettro',
		2: "Lunghezza d'onda e frequenza",
		3: "L'energia di un fotone",
		4: 'Una mole di fotoni',
		5: "L'effetto fotoelettrico",
		6: 'Spettri continui e a righe',
	},
	'chim-modello-bohr': {
		1: 'Orbite e stati',
		2: "L'energia di un livello",
		3: "L'energia di un salto",
		4: "La lunghezza d'onda di una riga",
		5: 'Dalla riga al livello',
	},
	'chim-livelli-energia': {
		1: 'Il salto nelle energie di ionizzazione',
		2: "Dalle energie all'elemento",
		3: 'Quanti elettroni in un livello',
		4: 'Sottolivelli e ordine di energia',
		5: 'Gli elettroni nei livelli',
	},
	'chim-onda-particella': {
		1: 'La relazione di de Broglie, senza conti',
		2: "La lunghezza d'onda di una particella",
		3: 'Con le unità da convertire',
		4: "Dalla lunghezza d'onda alla velocità",
		5: 'Il principio di indeterminazione',
		6: 'Orbita e orbitale',
	},
	'chim-configurazione-elettronica': {
		1: 'Gli elettroni di una configurazione',
		2: 'La configurazione fino al 3p',
		3: 'Dopo il 3p: il 4s e il 3d',
		4: 'Gli elettroni spaiati',
		5: 'La configurazione abbreviata',
		6: 'Gli ioni',
	},
	'chim-radioattivita': {
		1: 'Il decadimento alfa',
		2: 'Il decadimento beta meno',
		3: 'Beta più e cattura elettronica',
		4: 'La particella emessa',
		5: 'Prevedere il decadimento',
		6: 'Le famiglie radioattive',
	},
	'chim-tempo-dimezzamento': {
		1: 'Quanto resta',
		2: 'Quanto tempo serve',
		3: 'Il tempo di dimezzamento',
		4: 'Rimasto e decaduto',
		5: 'Un tempo qualunque',
		6: 'Il tempo dal logaritmo',
	},
	'chim-fissione-fusione': {
		1: 'Il difetto di massa',
		2: "L'energia di legame",
		3: "L'energia di legame per nucleone",
		4: 'Il nucleo più stabile',
		5: "L'energia di una reazione",
		6: "L'energia di una massa di combustibile",
	},
	'gruppi-periodi': {
		1: 'Periodi, gruppi e blocchi',
		2: 'La configurazione esterna di un gruppo',
		3: 'Dalla configurazione alla posizione: blocchi s e p',
		4: 'Dalla configurazione alla posizione: blocco d',
		5: 'Dalla posizione alla configurazione',
	},
	'chim-simboli-lewis': {
		1: 'Elettroni di valenza dalla configurazione',
		2: 'Con un sottolivello d pieno',
		3: 'Elettroni di valenza dal gruppo',
		4: 'I puntini del simbolo di Lewis',
		5: 'Lo ione di un elemento',
		6: 'Lo ione e il suo gas nobile',
	},
	'proprieta-periodiche': {
		1: 'La carica nucleare efficace',
		2: 'Il raggio atomico nella tavola',
		3: 'Il raggio degli ioni',
		4: "L'energia di ionizzazione nella tavola",
		5: 'Le due eccezioni',
		6: 'Le energie di ionizzazione successive',
	},
	'chim-affinita-elettronegativita': {
		1: 'Che cosa misurano',
		2: "L'affinità elettronica nella tavola",
		3: "L'elettronegatività nella tavola",
		4: 'La carica parziale in un legame',
		5: 'La differenza di elettronegatività',
		6: 'Legami a confronto',
	},
	'chim-metalli-non-metalli': {
		1: 'Metallo, semimetallo o non metallo',
		2: 'Le proprietà delle tre classi',
		3: 'Il carattere metallico',
		4: 'Le famiglie',
		5: 'Lo ione dal gruppo',
		6: 'La formula dai due ioni',
	},
	'chim-regola-ottetto': {
		1: 'Energia e stabilità',
		2: 'Confrontare i legami in tabella',
		3: "L'energia per rompere i legami",
		4: 'Il bilancio di energia di una reazione',
		5: "Quanti elettroni per l'ottetto",
		6: 'Lo ione e il gas nobile',
	},
	'legame-covalente': {
		1: "Che cos'è il legame covalente",
		2: 'Quanti legami forma un atomo',
		3: 'Contare gli elettroni di una molecola',
		4: 'Legami doppi e tripli',
		5: 'Ordine, lunghezza ed energia',
	},
	'chim-legame-covalente-polare': {
		1: 'La differenza di elettronegatività',
		2: 'Il tipo di legame',
		3: 'Le cariche parziali',
		4: 'Il legame più polare',
		5: 'Il legame dativo',
	},
	'legame-ionico': {
		1: 'Quale coppia forma un legame ionico',
		2: 'Lo ione dal gruppo',
		3: 'La formula dai due ioni',
		4: 'Gli ioni in una massa di composto',
		5: 'Energie reticolari a confronto',
		6: 'Le proprietà dei composti ionici',
	},
	'chim-legame-metallico': {
		1: 'Il modello del mare di elettroni',
		2: 'Gli elettroni messi in comune',
		3: 'Gli elettroni del mare in una massa di metallo',
		4: 'Quale metallo fonde più in alto',
		5: 'Le proprietà spiegate dal modello',
		6: 'Le leghe e i carati',
	},
	'chim-formule-lewis': {
		1: 'Gli elettroni di valenza di una molecola',
		2: "Le coppie solitarie dell'atomo centrale",
		3: 'Le coppie di legame',
		4: 'Gli elettroni di valenza di uno ione',
		5: 'La carica formale',
		6: "Le eccezioni all'ottetto",
	},
	'chim-polarita-molecole': {
		1: 'Il dipolo di un legame',
		2: 'Molecole con atomi legati uguali',
		3: 'Atomi diversi attorno al centro',
		4: 'La somma di due dipoli',
		5: 'Solubilità e bacchetta elettrizzata',
	},
	'chim-legame-valenza': {
		1: 'Quali orbitali si sovrappongono',
		2: 'Legame sigma e legame pi greco',
		3: 'Singolo, doppio e triplo',
		4: 'Contare i legami pi greco',
		5: 'Contare i legami sigma',
		6: 'Sigma e pi greco insieme',
	},
	'chim-ibridazione': {
		1: 'I tre tipi di orbitali ibridi',
		2: "Dai domini all'ibridazione",
		3: "L'atomo centrale con legami singoli",
		4: "L'atomo centrale con legami multipli",
		5: 'I carboni di una catena',
		6: 'Quali orbitali formano il legame',
	},
	'chim-forze-dipolo-london': {
		1: 'Quali forze agiscono',
		2: 'Gli elettroni di una molecola',
		3: 'London in una famiglia',
		4: 'Stessi elettroni, polarità diversa',
		5: 'La forza ione-dipolo',
		6: 'Forma, polarizzabilità e quando vince London',
	},
	'chim-legame-idrogeno': {
		1: 'Quale sostanza forma legami a idrogeno',
		2: 'Idrogeni che contano e coppie solitarie',
		3: 'Tra due molecole diverse',
		4: 'Chi bolle più in alto, e perché',
		5: 'I legami a idrogeno nel DNA',
	},
	'chim-stato-liquido': {
		1: 'Viscosità, tensione superficiale, capillarità',
		2: 'Evaporazione e tensione di vapore',
		3: 'Il più volatile',
		4: 'Leggere la tabella della tensione di vapore',
		5: 'Con le atmosfere',
		6: 'Bolle o non bolle',
	},
	'chim-stato-solido': {
		1: 'Cristallini e amorfi, reticolo e cella',
		2: 'Dalla formula al tipo di solido',
		3: 'Dalle proprietà al tipo di solido',
		4: 'Quante particelle nella cella',
		5: 'Ordinare le temperature di fusione',
		6: 'Le forme del carbonio',
	},
	'numero-ossidazione': {
		1: 'Elementi liberi e ioni di un solo atomo',
		2: 'Composti di due elementi',
		3: 'Composti di tre elementi',
		4: 'Ioni poliatomici',
		5: 'Idruri, perossidi e altri casi',
		6: 'Dai numeri di ossidazione alla formula',
	},
	'chim-ossidi': {
		1: 'Che tipo di ossido è',
		2: 'Ossidi basici: dalla formula al nome',
		3: 'Ossidi basici: dal nome alla formula',
		4: 'Anidridi: dalla formula al nome',
		5: 'Anidridi: dal nome alla formula',
		6: 'Perossidi e ossidi particolari',
	},
	'chim-idruri-idracidi': {
		1: 'Idruro metallico, idruro covalente o idracido',
		2: 'I numeri di ossidazione',
		3: 'Idruri: dalla formula al nome',
		4: 'Idruri: dal nome alla formula',
		5: 'Idracidi: nomi e formule',
	},
	'chim-idrossidi': {
		1: 'Il numero di ossidazione del metallo',
		2: 'Dal metallo alla formula',
		3: 'Dalla formula al nome',
		4: 'Dal nome alla formula',
		5: "Dall'ossido basico all'idrossido",
	},
	'chim-ossiacidi': {
		1: 'Il numero di ossidazione del non metallo',
		2: 'Dalla formula al nome tradizionale',
		3: 'Dal nome tradizionale alla formula',
		4: 'Il nome IUPAC',
		5: 'Meta, piro e orto',
	},
	'chim-sali-binari': {
		1: 'Gli ioni e i loro nomi',
		2: 'Dagli ioni alla formula',
		3: 'Dalla formula al nome, con un solo numero di ossidazione',
		4: 'Dalla formula al nome, con due numeri di ossidazione',
		5: 'Dal nome alla formula',
	},
	'chim-sali-ternari': {
		1: "Dall'acido all'anione",
		2: 'Dagli ioni alla formula',
		3: 'Dalla formula al nome tradizionale e di Stock',
		4: 'Il nome IUPAC',
		5: 'I sali acidi',
		6: 'I sali idrati',
	},
	'chim-acqua-molecola': {
		1: 'La composizione',
		2: "L'acqua dal suo elemento",
		3: 'Forma e polarità',
		4: 'Chi forma legami a idrogeno',
		5: 'Che cosa si rompe',
	},
	'chim-acqua-proprieta': {
		1: 'La proprietà giusta',
		2: 'Il volume del ghiaccio',
		3: 'Il ghiaccio che galleggia',
		4: "Scaldare l'acqua",
		5: 'Lo stesso calore',
	},
	'chim-acqua-solvente': {
		1: "Che cosa succede nell'acqua",
		2: 'Gli ioni di un sale',
		3: 'Le moli di ioni',
		4: 'Quanto se ne scioglie',
		5: 'La cristallizzazione',
		6: "La durezza dell'acqua",
	},
	'chim-acqua-acidi-basi': {
		1: 'Che cosa dice la prova',
		2: 'Acidi e basi secondo Arrhenius',
		3: 'La scala del pH',
		4: 'Dieci volte per unità',
		5: 'La diluizione',
		6: 'Gli indicatori',
	},
	// Chemistry: the names of the Python generators' levels (scripts/chimica/esercizi/).

	'mole-massa-molare': {
		1: 'La formula dal disegno',
		2: 'La massa molare',
		3: 'Dalla massa alle moli',
		4: 'Molecole e atomi',
		5: 'Composizione percentuale',
	},
	'geometria-molecolare-vsepr': {
		1: 'Senza coppie solitarie',
		2: 'Con coppie solitarie',
		3: 'Legami doppi e tripli',
		4: "L'angolo di legame",
		5: 'Polare o apolare',
	},
	'alcani-nomenclatura': {
		1: 'Un solo metile',
		2: 'Più metili',
		3: 'Sostituenti diversi',
		4: 'La catena nascosta',
		5: 'Tutto insieme',
	},
	'isomeria': {
		1: 'Isomeri o no',
		2: "Che relazione c'è",
		3: 'Carboni chirali',
		4: 'E o Z',
		5: 'R o S',
	},
	'gruppi-funzionali': {
		1: 'Un gruppo solo',
		2: 'Trova il gruppo',
		3: 'I gruppi che si confondono',
		4: 'Molecole vere',
		5: 'Tutti i gruppi',
	},
	'amminoacidi-legame-peptidico': {
		1: 'Le parti di un amminoacido',
		2: 'Le catene laterali',
		3: 'Il dipeptide giusto',
		4: 'Contare i legami peptidici',
		5: 'La forma a pH 7',
	},
	'monomi': {
		1: 'Coefficiente e parte letterale',
		2: 'Monomio o no',
		3: 'Forma normale con gli interi',
		4: 'Forma normale con frazioni e potenze',
		5: 'Valore numerico con gli interi',
		6: 'Valore numerico con le frazioni',
	},
	'polinomi': {
		1: 'Ridurre in una lettera',
		2: 'Ridurre in due lettere',
		3: 'Ridurre con le frazioni',
		4: 'Il grado di un polinomio',
		5: 'Il grado dopo la riduzione',
		6: 'Ordinato, completo, omogeneo',
		7: 'Valore numerico',
	},
	'polinomi-operazioni': {
		1: 'Somma di due polinomi',
		2: 'Differenza di due polinomi',
		3: 'Somme con le frazioni',
		4: 'Monomio per polinomio',
		5: 'Binomio per binomio',
		6: 'Polinomio per polinomio',
		7: 'Polinomio diviso un monomio',
	},
	'polinomi-prodotti-notevoli': {
		1: 'Somma per differenza con un numero',
		2: 'Somma per differenza con i monomi',
		3: 'Quadrato di un binomio con un numero',
		4: 'Quadrato di un binomio con i monomi',
		5: 'Quadrato di un trinomio',
		6: 'Cubo di un binomio',
		7: 'Il triangolo di Tartaglia',
	},
	'polinomi-espressioni': {
		1: 'Prodotti e somme',
		2: 'Prodotti notevoli con un segno davanti',
		3: 'Due lettere o gradi più alti',
		4: 'Con le frazioni',
		5: 'Cubi e potenze nei prodotti',
		6: 'Prodotti notevoli da riconoscere',
		7: 'Tonde, quadre e graffe',
	},
	'polinomi-divisione': {
		1: 'Divisore di primo grado',
		2: 'Dividendo di terzo grado',
		3: 'Dividendo incompleto',
		4: 'Divisore di secondo grado',
		5: 'Quoziente con le frazioni',
		6: 'Divisore incompleto',
	},
	'polinomi-ruffini': {
		1: 'Ruffini con x − a',
		2: 'Dividendo incompleto',
		3: 'Ruffini con x + a',
		4: 'Ruffini con le frazioni',
		5: 'Il teorema del resto',
		6: 'Divisibile o no',
		7: 'Trovare il parametro k',
	},
	'scomposizione-raccoglimento': {
		1: 'Raccogliere un numero o una lettera',
		2: 'Raccogliere un monomio',
		3: 'Raccogliere il segno meno',
		4: 'Raccogliere una parentesi',
		5: 'Raccoglimento parziale',
		6: 'Riordinare prima di raccogliere',
	},
	'scomposizione-prodotti-notevoli': {
		1: 'Differenza di quadrati',
		2: 'Quadrato di un binomio',
		3: 'Somma e differenza di cubi',
		4: 'Cubo o quadrato di un trinomio',
		5: 'Prima raccogli, poi il prodotto notevole',
		6: 'Scomposizioni in più passi',
	},
	'scomposizione-trinomio': {
		1: 'Somma e prodotto positivi',
		2: 'Somma e prodotto con i segni',
		3: 'Prima raccogli, poi scomponi',
		4: 'Si scompone o no',
		5: 'Primo coefficiente diverso da 1',
		6: 'Trinomi in due lettere',
		7: 'Trinomi di quarto grado',
	},
	'scomposizione-ruffini': {
		1: 'Trovare uno zero',
		2: 'Zero 1 o −1, poi il trinomio',
		3: 'Una potenza mancante',
		4: 'Uno zero frazionario',
		5: 'Quarto grado, due volte Ruffini',
		6: 'Raccoglimento, Ruffini e trinomio',
	},
	'polinomi-mcd-mcm': {
		1: 'Due polinomi',
		2: 'Esponenti diversi',
		3: 'Tre polinomi',
		4: 'Fattori opposti',
		5: 'Due lettere',
		6: 'Cubi e falso quadrato',
		7: 'Con le frazioni',
	},
	'insiemi-prodotto-cartesiano': {
		1: 'Coppie ordinate uguali o no',
		2: 'Elencare le coppie del prodotto',
		3: 'Quante coppie ha il prodotto',
		4: 'Dalla tabella e dalle coppie agli insiemi',
		5: 'Insiemi descritti con una proprietà',
		6: 'Coppie con una condizione',
	},
	'dominio-codominio-immagine': {
		1: 'Trovare le controimmagini',
		2: "L'insieme immagine",
		3: 'Immagine e controimmagine con una formula',
		4: 'Il dominio: polinomi e frazioni',
		5: 'Denominatori da scomporre',
		6: 'I casi scomodi del dominio',
	},
	'relazioni-binarie': {
		1: 'Dalla proprietà alle coppie',
		2: 'La coppia sta nella relazione?',
		3: 'Leggere la tabella a doppia entrata',
		4: 'Dalle coppie alla proprietà',
		5: 'Relazione in un insieme: i cappi',
		6: 'La relazione inversa',
	},
	'definizione-funzione': {
		1: 'È una funzione? Guarda le coppie',
		2: 'Il valore in un numero intero',
		3: 'Con il quadrato di un negativo',
		4: 'Il valore in una frazione',
		5: 'Completare la tabella di valori',
		6: 'Al posto di x una lettera',
	},
	'equazioni-problemi': {
		1: 'Numeri ed età: anni fa',
		2: 'Aree e lati che cambiano',
		3: 'Sconti e percentuali sul resto',
		4: 'Incontri e inseguimenti',
		5: 'Miscele e diluizioni',
		6: 'Lavorare insieme: ore e minuti',
		7: 'La soluzione è accettabile?',
	},
	'equazioni-fratte': {
		1: 'Una frazione per membro',
		2: 'Denominatori con la x e numeri',
		3: 'Un denominatore da scomporre',
		4: 'Denominatori opposti',
		5: 'Quando x² si cancella',
		6: 'Soluzioni escluse, impossibili e indeterminate',
	},
	'composizione-di-funzioni': {
		1: 'Comporre seguendo le frecce',
		2: 'La composta in un numero',
		3: 'La formula con due funzioni lineari',
		4: 'La formula con un quadrato',
		5: "Trovare l'inversa",
		6: "L'inversa con le frazioni",
		7: "Quando c'è l'inversa e il suo grafico",
	},
	'frazioni-algebriche-semplificazione': {
		1: 'Denominatore monomio',
		2: 'Un fattore comune sopra e sotto',
		3: 'Quando resta 1 o un polinomio',
		4: 'Fattori opposti: 2 − x e x − 2',
		5: 'Due lettere e raccoglimento parziale',
		6: 'Cubi e regola di Ruffini',
	},
	'frazioni-algebriche-esistenza': {
		1: 'Il valore di una frazione, se esiste',
		2: 'C.E. con un denominatore di primo grado',
		3: 'C.E. con un monomio o un raccoglimento',
		4: 'C.E. con differenza di quadrati o quadrato',
		5: 'C.E. con un trinomio',
		6: 'C.E. in più passi e fattori mai nulli',
		7: 'C.E. di più frazioni insieme',
	},
	'relazioni-equivalenza-ordine': {
		1: 'Una proprietà alla volta',
		2: 'Le quattro proprietà insieme',
		3: 'Relazioni in ℕ e ℤ a parole',
		4: 'Classi e insieme quoziente',
		5: 'Stesso resto nella divisione',
		6: 'Ordine largo o stretto, totale o parziale',
		7: 'Le coppie da aggiungere',
	},
	'funzioni-lineari': {
		1: 'Diretta, inversa o lineare?',
		2: 'Il valore che manca nella tabella',
		3: 'La formula da una tabella',
		4: 'Il tipo da una tabella',
		5: 'Trovare m e q',
		6: 'Problemi diretti e inversi',
		7: 'Problemi in due tempi e col quadrato',
	},
	'equazioni-letterali': {
		1: 'Coefficiente numerico, niente da discutere',
		2: 'Il parametro nel coefficiente: a = 0',
		3: 'Raccogliere la x: il caso indeterminato',
		4: 'Tre casi: determinata, impossibile, indeterminata',
		5: 'Denominatori e coefficiente con il meno',
		6: 'Formule inverse',
		7: 'Formule inverse con i numeri',
	},
	'frazioni-algebriche-operazioni': {
		1: 'Stesso denominatore',
		2: 'Denominatori di primo grado',
		3: 'Denominatori da scomporre',
		4: 'Il prodotto',
		5: 'Il quoziente e le sue C.E.',
		6: 'Una parentesi divisa per una frazione',
		7: 'Potenza, quoziente e somma',
	},
	'geometria-enti': {
		1: 'Segmenti e punto medio',
		2: 'Che tipo di angolo è',
		3: 'Gradi e primi',
		4: 'Complementare e supplementare',
		5: 'Complementare e supplementare con i primi',
		6: 'Opposti al vertice e bisettrici',
		7: "Problemi con un'equazione",
	},
	'statistica-variabilita': {
		1: 'Il campo di variazione',
		2: 'Gli scarti dalla media',
		3: 'Lo scarto semplice medio',
		4: 'Scarto quadratico medio esatto',
		5: 'Arrotondare σ al centesimo',
		6: 'Da una tabella di frequenze',
		7: 'Chi ha i dati più dispersi',
	},
	'statistica-medie': {
		1: 'Media di una lista di numeri',
		2: 'Media ponderata dei voti',
		3: 'Media da una tabella di frequenze',
		4: 'Mediana di dati non ordinati',
		5: 'Mediana e moda da una tabella',
		6: 'Media o mediana? Valori anomali',
		7: 'Media di dati in classi',
	},
	'statistica-dati': {
		1: 'Popolazione, campione e unità',
		2: 'Che tipo di carattere',
		3: 'Contare le frequenze',
		4: 'Cumulate: al massimo, almeno',
		5: 'Dati in classi e il dato sul confine',
		6: "Gli angoli dell'aerogramma",
		7: 'Dagli angoli alle frequenze',
	},
	'geometria-punti-notevoli': {
		1: 'Riconoscere il punto notevole',
		2: 'Baricentro: la regola del 2 : 1',
		3: 'Dove cadono ortocentro e circocentro',
		4: 'Il triangolo rettangolo',
		5: "L'angolo tra due bisettrici",
		6: "L'angolo tra due altezze",
		7: 'I raggi del triangolo equilatero',
	},
	'geometria-perpendicolari-parallele': {
		1: 'I nomi delle coppie di angoli',
		2: 'Gli otto angoli con due parallele',
		3: 'Parallele o no',
		4: "Le ampiezze con un'equazione",
		5: 'Gli angoli del triangolo',
		6: "L'angolo esterno",
		7: 'Gli angoli dei poligoni',
	},
	'disequazioni-primo-grado': {
		1: 'Leggere gli intervalli',
		2: 'Coefficiente positivo',
		3: 'Quando il verso cambia',
		4: 'Con le parentesi',
		5: 'Con i denominatori',
		6: 'Sempre vere o impossibili',
		7: 'Dal problema alla disequazione',
	},
	'angoli-e-lati-dei-triangoli': {
		1: 'Classificare un triangolo',
		2: 'Lati e angoli corrispondenti',
		3: 'Quale criterio di congruenza',
		4: 'Completare una dimostrazione',
		5: 'Esiste il triangolo?',
		6: 'Il terzo angolo',
		7: 'Gli angoli del triangolo isoscele',
	},
	'disequazioni-razionali': {
		1: 'Prodotto di due fattori',
		2: 'Estremi compresi',
		3: 'Un fattore come 3 − x',
		4: 'Tre fattori',
		5: 'Frazione e zero',
		6: 'Frazione e numero',
		7: 'Due frazioni',
	},
	'sistemi-di-disequazioni': {
		1: 'Disequazioni già quasi risolte',
		2: 'Con un cambio di verso',
		3: 'Tre disequazioni, con i denominatori',
		4: 'Impossibile o con un solo punto',
		5: 'Una disequazione sempre o mai vera',
		6: 'Doppia disequazione, x al centro',
		7: 'Doppia disequazione, x in due membri',
	},
	'geometria-quadrilateri': {
		1: 'Angoli del parallelogramma',
		2: 'Lati, perimetro e diagonali',
		3: 'Angoli con le diagonali',
		4: 'Angoli dei trapezi',
		5: 'Riconoscere il quadrilatero',
		6: 'Vero o falso sulle famiglie',
		7: 'Giustificare un passo',
	},
	'insiemi-differenza': {
		1: 'La differenza di due insiemi',
		2: 'Differenza di insiemi descritti',
		3: 'Contare gli elementi della differenza',
		4: 'Il complementare in U',
		5: 'Le leggi di De Morgan',
		6: 'Problemi con due gruppi',
		7: 'Problemi con tre gruppi',
	},
	'insiemi-intersezione': {
		1: 'Gli elementi in comune',
		2: 'Multipli, divisori e condizioni',
		3: "Le proprietà dell'intersezione",
		4: 'Intersezione di tre insiemi',
		5: 'Contare gli elementi comuni',
		6: 'Il minimo e il massimo',
	},
	'logica-proposizioni': {
		1: 'Riconoscere una proposizione',
		2: 'Un connettivo alla volta',
		3: 'Calcolare su una riga',
		4: 'Tavola con due lettere',
		5: 'Tavola con tre lettere',
		6: 'Tautologie ed equivalenze',
		7: 'Negare con De Morgan',
	},
	'logica-implicazione': {
		1: 'Vero o falso: se… allora',
		2: 'Inversa, contraria, contronominale',
		3: "La tavola dell'implicazione",
		4: 'Ragionamenti ed equivalenze',
		5: 'Necessaria o sufficiente',
		6: 'Implicazione e insiemi di verità',
		7: "Negare un'implicazione",
	},
	'logica-quantificatori': {
		1: 'Enunciato aperto o proposizione',
		2: "L'insieme di verità",
		3: 'Per ogni ed esiste: il controesempio',
		4: 'Vero in ℕ, in ℤ o in ℚ',
		5: 'Dalle parole ai simboli',
		6: 'Negare "tutti" e "qualche"',
		7: "Due quantificatori: conta l'ordine",
	},
	'numeri-reali-irrazionali': {
		1: 'Radici razionali o irrazionali',
		2: 'Irrazionale dal decimale',
		3: 'Approssimare una radice',
		4: 'Approssimare −√n',
		5: 'Confrontare due numeri reali',
		6: 'Mettere in ordine',
		7: 'Conti con le radici: razionale o no',
	},
	'sistemi-cramer': {
		1: 'Il determinante di una matrice 2 × 2',
		2: 'La regola di Cramer',
		3: 'Prima la forma normale',
		4: 'D = 0: impossibile o indeterminato',
		5: 'Sistemi con un parametro k',
		6: 'Il determinante 3 × 3 con Sarrus',
		7: 'Tre equazioni in tre incognite',
	},
	'radicali-esponente-razionale': {
		1: 'Da potenza a radicale e ritorno',
		2: 'Calcolare una potenza con la frazione',
		3: 'Esponente negativo o decimale',
		4: 'Un solo radicale da due',
		5: 'Tre potenze alla stessa base',
		6: 'Lettere e radicali annidati',
		7: 'Radicandi negativi e razionalizzazione',
	},
	'sistemi-di-equazioni': {
		1: 'Quale coppia è la soluzione',
		2: 'Metodo di sostituzione',
		3: 'Metodo del confronto',
		4: 'Metodo di riduzione',
		5: 'Con denominatori e parentesi',
		6: 'Una, nessuna o infinite soluzioni',
		7: 'Sistemi fratti',
	},
	'numeri-reali-radici': {
		1: 'Calcolare una radice',
		2: 'Quando esiste il radicale',
		3: 'La radice di x²: il valore assoluto',
		4: 'Semplificare un radicale',
		5: 'Semplificare con le lettere',
		6: 'Portare allo stesso indice',
		7: 'Qual è il più grande',
	},
	'sistemi-problemi': {
		1: 'Due numeri: somma, differenza, rapporto',
		2: 'Biglietti e monete, anche impossibili',
		3: 'Le età di genitori e figli',
		4: 'Rettangoli e triangoli isosceli',
		5: 'Le cifre di un numero',
		6: 'Sconti e miscele',
		7: 'Barche, aerei e tre incognite',
	},
	'equazioni-parametriche': {
		1: "Quando l'equazione è di primo grado",
		2: 'Soluzioni distinte o coincidenti',
		3: 'Una soluzione è data',
		4: 'Soluzioni opposte, reciproche o nulle',
		5: 'Somma o prodotto dati',
		6: 'Somma dei quadrati',
	},
	'equazioni-secondo-grado-relazioni': {
		1: 'Somma e prodotto dai coefficienti',
		2: "Trovare l'altra soluzione",
		3: "L'equazione con soluzioni date",
		4: 'Due numeri di somma e prodotto dati',
		5: 'Scomporre il trinomio con le soluzioni',
		6: 'Il segno delle soluzioni',
		7: 'Espressioni simmetriche delle soluzioni',
	},
	'radicali-operazioni': {
		1: 'Prodotto e quoziente di radicali',
		2: 'Portare fuori un fattore',
		3: 'Portare fuori con le lettere',
		4: 'Portare dentro e confrontare',
		5: 'Indici diversi, potenze e radici',
		6: 'Sommare radicali simili',
		7: 'Prodotti notevoli con i radicali',
	},
	'equazioni-secondo-grado-problemi': {
		1: 'Problemi sui numeri',
		2: 'Una, due o nessuna risposta',
		3: 'Aree di rettangoli e triangoli',
		4: 'Lati irrazionali o impossibili',
		5: 'Cornici e teorema di Pitagora',
		6: 'Moto e lavoro: equazioni fratte',
		7: 'Due aumenti o due sconti uguali',
	},
	'numeri-reali-espressioni': {
		1: 'Semplificare prima di sommare',
		2: 'Prodotti notevoli con i radicali',
		3: 'Radice al denominatore',
		4: 'Denominatore binomio: il coniugato',
		5: 'Radicali con indici diversi',
		6: 'Equazioni con i radicali',
		7: 'Disequazioni: il segno del coefficiente',
	},
	'radicali-razionalizzazione': {
		1: 'Una radice quadrata sotto',
		2: 'Prima semplifica la radice',
		3: 'Radici cubiche e oltre',
		4: 'Due fattori sotto la radice',
		5: 'Il coniugato',
		6: 'Coniugati con le trappole',
		7: 'Coniugato con le lettere',
	},
	'il-coefficiente-angolare': {
		1: 'La pendenza da due punti',
		2: 'Punti con le frazioni',
		3: 'La pendenza dalla forma implicita',
		4: 'Retta per un punto',
		5: 'Retta per un punto in forma implicita',
		6: 'Retta per due punti',
		7: 'Tre punti allineati',
	},
	'rette-parallele-tra-loro': {
		1: 'Parallele, perpendicolari o incidenti',
		2: "L'antireciproco",
		3: 'Trovare il parametro k',
		4: 'Retta per un punto, parallela o perpendicolare',
		5: 'La retta in forma implicita o parallela a un asse',
		6: "L'asse di un segmento",
		7: 'La proiezione di un punto su una retta',
	},
	'distanza-punto-retta': {
		1: 'Rette parallele agli assi',
		2: 'La formula della distanza',
		3: 'Dalla forma esplicita',
		4: "Coefficienti frazionari e l'origine",
		5: 'Distanza tra due parallele',
		6: 'Altezza e area di un triangolo',
	},
	'intersezione-tra-due-rette': {
		1: 'Due rette in forma esplicita',
		2: 'Forma implicita e rette x = h, y = k',
		3: 'Incidenti, parallele o coincidenti',
		4: 'I vertici di un triangolo',
		5: "L'area con un lato su un asse",
		6: 'Tre rette per lo stesso punto',
	},
	'funzioni-quadratiche': {
		1: 'Concavità e apertura',
		2: "Il vertice e l'asse",
		3: 'Il vertice con le frazioni',
		4: 'Un punto sulla parabola',
		5: "Dove incontra l'asse x",
		6: 'Sopra, sotto o tangente',
		7: 'La parabola per tre punti',
	},
	'retta-fasci': {
		1: 'La retta del fascio per un punto',
		2: 'La parallela per un punto',
		3: 'Il centro di un fascio con k',
		4: 'La retta esclusa',
		5: 'Fascio improprio: il k senza retta',
		6: 'La retta del fascio per un punto dato',
		7: 'Parallela o perpendicolare nel fascio',
	},
	'il-piano-cartesiano': {
		1: 'In quale quadrante sta il punto',
		2: 'Distanza in orizzontale e in verticale',
		3: 'La formula della distanza',
		4: 'Punti di un asse a distanza data',
		5: 'Punto medio ed estremo',
		6: 'Simmetrici e baricentro',
		7: 'Triangoli e parallelogrammi',
	},
	'equazione-di-una-retta': {
		1: 'Parallele agli assi e bisettrici',
		2: "Dalla forma implicita all'esplicita",
		3: 'Forma implicita con coefficienti interi',
		4: 'Il punto sta sulla retta?',
		5: 'Dove la retta taglia gli assi',
		6: 'Rette con a = 0, b = 0 o c = 0',
		7: 'Il parametro k',
	},
	'disequazioni-secondo-grado-fratte': {
		1: 'Un fattore e un trinomio',
		2: 'Trinomio sempre positivo',
		3: 'Con un quadrato',
		4: 'Frazione con un trinomio',
		5: 'Frazione da ridurre',
		6: 'Sistema di secondo grado',
		7: "Problema con un'area",
	},
	'disequazioni-secondo-grado': {
		1: 'Valori interni o esterni',
		2: 'Coefficiente di x² maggiore di 1',
		3: 'a negativo o termini nei due membri',
		4: 'Soluzioni con i radicali',
		5: 'Delta uguale a zero',
		6: 'Delta negativo',
		7: 'Pure e spurie',
	},
	'concetti-probabilita': {
		1: 'Dado e urna numerata',
		2: 'Certo, impossibile, compatibili',
		3: 'Monete: gli esiti in ordine',
		4: 'Urna con più colori',
		5: 'Una carta dal mazzo di 40',
		6: 'La somma di due dadi',
		7: 'Frequenza relativa e stima',
	},
	'leggi-probabilita': {
		1: 'Evento contrario',
		2: 'Almeno uno',
		3: 'Unione di eventi incompatibili',
		4: 'Unione di eventi compatibili',
		5: 'Unione con due dadi',
		6: 'Tabella a doppia entrata',
	},
	'equazioni-binomie-trinomie': {
		1: 'Raccoglimento totale',
		2: 'Raccoglimento parziale',
		3: 'Regola di Ruffini',
		4: 'Equazioni binomie',
		5: 'Equazioni biquadratiche',
		6: 'Trinomie di sesto grado',
		7: 'Disequazioni scomponibili',
	},
	'valore-assoluto-equazioni': {
		1: 'Valore assoluto uguale a un numero',
		2: 'Argomento di secondo grado',
		3: 'Due valori assoluti uguali',
		4: 'Secondo membro con la x',
		5: 'Secondo membro con la x, secondo grado',
		6: 'Più valori assoluti',
		7: 'Disequazioni con un numero',
		8: 'Disequazioni di secondo grado',
		9: 'Disequazioni con la x a secondo membro',
	},
	'equazioni-irrazionali': {
		1: 'Radice uguale a un numero',
		2: "Radice uguale a un'espressione",
		3: 'Prima si isola il radicale',
		4: 'La condizione sul secondo membro',
		5: 'Due radicali',
		6: 'Radici cubiche',
		7: 'Disequazioni con un numero',
		8: "Radice minore di un'espressione",
		9: "Radice maggiore di un'espressione",
	},
	'sistemi-secondo-grado': {
		1: 'Sostituzione con xy = p',
		2: 'Sostituzione con i quadrati',
		3: 'Retta e parabola',
		4: 'Sistemi simmetrici',
		5: 'Somma dei quadrati',
		6: 'Problemi',
	},
	'circonferenza-cerchio': {
		1: 'Punti interni ed esterni',
		2: 'Retta e circonferenza',
		3: 'Due circonferenze',
		4: 'Corda, distanza e raggio',
		5: 'Angolo al centro e alla circonferenza',
		6: 'Le tangenti da un punto esterno',
		7: 'Il triangolo nella semicirconferenza',
	},
	'trasformazioni-geometriche': {
		1: 'Traslazione di un punto',
		2: 'Simmetrici nel piano cartesiano',
		3: 'Omotetia di centro O',
		4: 'Retta traslata',
		5: 'Retta simmetrica od omotetica',
		6: 'Dalle equazioni alla trasformazione',
		7: 'Composizioni',
	},
	'funzioni-reali-di-variabile-reale': {
		1: 'Dominio di una funzione fratta',
		2: 'Dominio di una radice',
		3: 'Radice con radicando di secondo grado',
		4: 'Radice e denominatore insieme',
		5: 'Frazione sotto radice',
		6: 'Zeri di una funzione',
		7: 'Segno di una funzione',
	},
	'funzioni-dispari-pari': {
		1: 'Calcolare f(-x)',
		2: 'Polinomi pari e dispari',
		3: 'Frazioni, radici e valore assoluto',
		4: 'Quando decide il dominio',
		5: 'Valori con la simmetria',
		6: 'Prodotti e somme di funzioni pari e dispari',
	},
	'funzioni-monotone': {
		1: 'La definizione di crescente e decrescente',
		2: 'La retta',
		3: 'La parabola con a positivo',
		4: 'La parabola con a negativo',
		5: 'Il valore assoluto',
		6: 'Crescente in tutto il dominio',
		7: 'Disequazioni con la monotonia',
	},
	'funzioni-periodiche': {
		1: 'Le uguaglianze del periodo',
		2: 'Riportare un numero nel primo periodo',
		3: 'Riportare un numero negativo',
		4: 'Un valore dalla formula su un periodo',
		5: 'Parte intera e parte frazionaria',
		6: 'Il periodo di f(kx)',
		7: 'Gli zeri in un intervallo',
	},
	'grafici-trasformazioni': {
		1: 'Traslazioni di un punto',
		2: 'Vertice di un grafico traslato',
		3: 'Simmetrie',
		4: 'Dilatazioni',
		5: 'Dalla trasformazione alla formula',
		6: 'Valore assoluto fuori e dentro',
		7: 'Più trasformazioni insieme',
	},
	'successioni-numeriche': {
		1: 'Un termine dal termine generale',
		2: 'Segni alterni con (-1)^n',
		3: 'Un termine di una successione ricorsiva',
		4: 'Il posto di un numero',
		5: 'Crescente, decrescente o non monotona',
		6: 'Limitata o no',
	},
	'progressioni-aritmetiche': {
		1: 'La ragione dai primi termini',
		2: 'Un termine da a₁ e d',
		3: 'Il posto di un termine',
		4: 'Il primo termine da due termini',
		5: 'Inserire medi aritmetici',
		6: 'La somma dei primi n termini',
		7: 'Una somma di cui contare i termini',
	},
	'progressioni-geometriche': {
		1: 'La ragione dai primi termini',
		2: 'Un termine da a₁ e q',
		3: 'Crescente, decrescente o a segni alterni',
		4: 'La ragione da due termini',
		5: 'Il posto di un termine',
		6: 'La somma dei primi n termini',
		7: 'Crescita a percentuale costante',
	},
	'principio-induzione': {
		1: 'Da quale n vale una disuguaglianza',
		2: 'Verificare un caso di una formula',
		3: 'Il termine che si aggiunge nel passo induttivo',
		4: 'Il secondo membro della tesi P(k + 1)',
		5: 'Completare un passo induttivo',
		6: "Riconoscere l'errore in una dimostrazione",
	},
	'circonferenza-equazione': {
		1: "Centro e raggio dall'equazione",
		2: 'Punto interno, esterno o sulla circonferenza',
		3: 'Dal centro e dal raggio alla forma generale',
		4: 'Centro e raggio dalla forma generale',
		5: 'Circonferenza, punto o nessun punto',
		6: 'Coefficienti da dividere',
		7: 'Equazione da condizioni',
	},
	'circonferenza-rette': {
		1: 'Posizione di una retta con la distanza',
		2: 'Punti di intersezione',
		3: 'Lunghezza della corda',
		4: 'Tangente in un punto della circonferenza',
		5: 'Tangenti da un punto esterno',
		6: 'Circonferenza tangente a una retta',
		7: 'Posizione di due circonferenze',
	},
	'parabola-equazione': {
		1: 'Fuoco e direttrice di y = ax²',
		2: 'Vertice, fuoco e direttrice',
		3: "Parabola con asse parallelo all'asse x",
		4: 'Equazione da fuoco e direttrice orizzontale',
		5: 'Equazione da fuoco e direttrice verticale',
		6: 'Equazione da vertice e un punto',
	},
	'parabola-rette': {
		1: 'Posizione di una retta con il discriminante',
		2: 'Il valore di q per cui la retta è tangente',
		3: 'Coefficiente angolare della tangente in un punto',
		4: 'Equazione della tangente in un punto',
		5: 'Tangente parallela a una retta data',
		6: 'Tangenti da un punto esterno',
		7: 'Area del segmento parabolico',
	},
	'ellisse': {
		1: "Semiassi dall'equazione canonica",
		2: "Fuochi dell'ellisse",
		3: 'Equazione da portare in forma canonica',
		4: 'Eccentricità',
		5: 'Retta secante, tangente o esterna',
		6: "Tangente in un punto dell'ellisse",
		7: "Equazione dell'ellisse da due condizioni",
	},
	'iperbole': {
		1: 'Vertici reali',
		2: "Fuochi dell'iperbole",
		3: 'Asintoti',
		4: 'Equazione da portare in forma canonica',
		5: 'Eccentricità',
		6: 'Retta secante, tangente, esterna o parallela a un asintoto',
		7: "Equazione dell'iperbole da due condizioni",
	},
	'iperbole-equilatera': {
		1: 'Fuochi di x² − y² = ±a²',
		2: 'Vertice di xy = k',
		3: 'Fuoco di xy = k',
		4: 'Asintoti e centro di una funzione omografica',
		5: 'Centro con le frazioni',
		6: 'Funzione omografica dagli asintoti e da un punto',
	},
	'funzioni-esponenziali': {
		1: 'Calcolare i valori di aˣ',
		2: 'Crescente o decrescente dalla base',
		3: 'Confrontare potenze con la stessa base',
		4: 'Trovare la base da un punto',
		5: 'Asintoto e immagine di un grafico spostato',
		6: 'Dalla funzione al grafico',
		7: 'Dal grafico alla funzione',
		8: 'Dominio con un esponenziale',
		9: 'Crescita e decadimento',
	},
	'equazioni-esponenziali': {
		1: 'Equazione elementare',
		2: 'Stessa base, esponente di primo grado',
		3: 'Basi potenze dello stesso numero',
		4: 'Esponente di secondo grado',
		5: 'Raccogliere la potenza comune',
		6: 'Sostituzione t = aˣ',
		7: 'Esponenti opposti',
	},
	'disequazioni-esponenziali': {
		1: 'Elementare con base maggiore di 1',
		2: 'Base tra 0 e 1: il verso si inverte',
		3: 'Secondo membro negativo o nullo',
		4: 'Stessa base, esponente di primo grado',
		5: 'Esponente di secondo grado',
		6: 'Raccoglimento con fattore negativo',
		7: 'Sostituzione t = aˣ',
	},
	'logaritmi-proprieta': {
		1: 'Logaritmo con la definizione',
		2: 'Base e argomento potenze dello stesso numero',
		3: "Trovare l'argomento o la base",
		4: 'Calcolare con le proprietà',
		5: 'Sviluppare un logaritmo',
		6: 'Scrivere come un solo logaritmo',
		7: 'Cambiamento di base',
	},
	'funzioni-logaritmiche': {
		1: 'Un punto del grafico',
		2: 'Il segno di un logaritmo',
		3: 'Ordinare tre logaritmi',
		4: 'Tra quali interi sta un logaritmo',
		5: 'Dominio con argomento di primo grado',
		6: 'Dominio con argomento di secondo grado o fratto',
		7: 'Grafico traslato: asintoto e zero',
	},
	'equazioni-logaritmiche': {
		1: 'Un logaritmo uguale a un numero',
		2: 'Argomento di secondo grado',
		3: 'Due logaritmi con la stessa base',
		4: 'Equazioni con le proprietà',
		5: 'Equazioni con una sostituzione',
		6: 'Esponenziali con i logaritmi',
		7: 'Esponenziali con sostituzione e logaritmo',
	},
	'disequazioni-logaritmiche': {
		1: 'Un logaritmo e un numero, base maggiore di 1',
		2: 'Un logaritmo e un numero, base minore di 1',
		3: 'Argomento di secondo grado',
		4: 'Due logaritmi con la stessa base',
		5: 'Disequazioni con le proprietà',
		6: 'Disequazioni con una sostituzione',
		7: 'Esponenziali con i logaritmi',
	},
	'distribuzioni-doppie': {
		1: 'I totali di riga e di colonna',
		2: 'Percentuale su tutti',
		3: 'Percentuale dentro un gruppo',
		4: 'La media di un gruppo',
		5: 'La frequenza teorica',
		6: 'La contingenza di una casella',
	},
	'regressione-correlazione': {
		1: 'La covarianza',
		2: 'Il coefficiente angolare dai dati',
		3: 'La retta dagli indici',
		4: 'Stimare con la retta',
		5: 'r dagli indici',
		6: 'r dai dati, al centesimo',
		7: 'Che cosa dice r',
	},
	'circonferenza-lunghezza-area': {
		1: 'Circonferenza e area',
		2: 'Formule inverse con π',
		3: 'Con π ≈ 3,14',
		4: "Lunghezza dell'arco",
		5: 'Area del settore',
		6: 'Corona circolare',
		7: 'Segmento circolare',
		8: 'Figure composte',
	},
	'teorema-di-pitagora': {
		1: "L'ipotenusa dai cateti",
		2: "Un cateto dall'ipotenusa",
		3: 'Radicali da semplificare',
		4: "L'inverso di Pitagora",
		5: 'I teoremi di Euclide',
		6: 'Quadrato, equilatero, 45° e 30°-60°',
		7: 'Problemi con i quadrilateri',
	},
	'triangolo-rettangolo-trigonometria': {
		1: 'Seno, coseno e tangente dai lati',
		2: 'I valori per 30, 45 e 60 gradi',
		3: 'Da un valore agli altri due',
		4: 'Un lato con i valori esatti',
		5: 'Un lato con la calcolatrice',
		6: "L'angolo da due lati",
		7: 'Problemi',
	},
	'similitudine': {
		1: 'Rettangoli simili',
		2: 'Due angoli e i vertici corrispondenti',
		3: 'Parallela a un lato e ombre',
		4: 'Secondo e terzo criterio',
		5: 'Lati omologhi',
		6: 'Le diagonali del trapezio',
		7: 'Perimetri, aree e scale',
		8: 'I teoremi di Euclide',
	},
	'poligoni-inscritti': {
		1: 'Angoli del quadrilatero inscritto',
		2: 'Riconoscere il quadrilatero inscrivibile',
		3: 'Il quadrilatero circoscritto',
		4: 'Inscrivibile o circoscrivibile',
		5: 'Angolo al centro ed esagono',
		6: 'Apotema e lato con i radicali',
		7: 'I raggi con Pitagora',
	},
	'equivalenza-aree': {
		1: "L'area delle figure",
		2: 'Unità di misura delle aree',
		3: "Una misura dall'area",
		4: "Le due altezze e l'altezza sull'ipotenusa",
		5: 'Poligoni regolari',
		6: 'Figure composte ed equivalenti',
	},
	'teorema-di-talete': {
		1: 'Il quarto segmento',
		2: 'Il segmento intero e i decimali',
		3: "Un'incognita in due segmenti",
		4: 'La parallela a un lato',
		5: 'Il teorema inverso',
		6: 'Il teorema della bisettrice',
		7: 'Il segmento dei punti medi',
		8: 'Parti proporzionali',
	},
	'inf-informazione-dati': {
		1: 'Dati e informazioni',
		2: 'Codificare con una tabella',
		3: 'Decodificare una sequenza',
		4: 'Quante sequenze con n bit',
		5: 'Quanti bit servono',
		6: 'Analogico o digitale',
	},
	'hardware-software': {
		1: 'Hardware o software',
		2: 'Software di base o applicativo',
		3: 'Sistema operativo, driver, firmware, applicazione',
		4: 'Guasto hardware o problema software',
		5: 'Vero o falso su hardware e software',
	},
	'inf-bit-byte': {
		1: 'Bit e byte',
		2: 'Multipli decimali',
		3: 'Multipli binari',
		4: 'Quanti valori con n bit',
		5: 'Tempo di scaricamento',
		6: 'Dati, minuti e velocità',
	},
	'inf-sistemi-posizionali': {
		1: 'Numeri romani',
		2: 'Le cifre di una base',
		3: 'Il valore di una cifra',
		4: 'La forma polinomiale',
		5: 'Da una base alla base dieci',
	},
	'inf-binario-decimale': {
		1: 'Da binario a decimale',
		2: 'Binario fino a 10 bit',
		3: 'Da decimale a binario',
		4: 'Decimale fino a 1023',
		5: 'Quanti bit servono',
	},
	'inf-esadecimale': {
		1: 'Da esadecimale a decimale',
		2: 'Da decimale a esadecimale',
		3: 'Da binario a esadecimale',
		4: 'Da esadecimale a binario',
		5: "L'ottale",
		6: 'I colori',
	},
	'inf-aritmetica-binaria': {
		1: 'Addizioni con il riporto',
		2: 'Riporti in catena',
		3: 'Il traboccamento',
		4: 'Per una potenza di due',
		5: 'Moltiplicazioni in colonna',
	},
	'inf-interi-segno': {
		1: 'Leggere modulo e segno',
		2: 'Intervallo dei valori e bit necessari',
		3: 'Leggere il complemento a due',
		4: 'Scrivere in complemento a due',
		5: 'Somma e traboccamento',
	},
	'inf-virgola-mobile': {
		1: 'Dal binario con la virgola al decimale',
		2: 'Dal decimale al binario con la virgola',
		3: 'Numeri esatti e numeri arrotondati',
		4: "L'esponente in base due",
		5: "Il campo dell'esponente a 32 bit",
	},
	'inf-codifica-caratteri': {
		1: 'Il codice ASCII di un carattere',
		2: 'Dal codice al carattere',
		3: 'Maiuscole e minuscole',
		4: 'Quanti byte occupa un testo',
		5: 'Un testo con gli accenti in UTF-8',
		6: 'I byte di un carattere in UTF-8',
	},
	'inf-codifica-immagini': {
		1: "Quanti pixel ha un'immagine",
		2: 'Colori e bit per pixel',
		3: 'Riconoscere un colore RGB',
		4: 'La dimensione in byte',
		5: 'La dimensione in kB, MB, KiB, MiB',
		6: 'Foto in una memoria e bit per pixel',
	},
	'inf-codifica-suoni': {
		1: 'Quanti campioni',
		2: 'La regola del campionamento',
		3: 'Livelli e bit per campione',
		4: 'La dimensione in byte, un canale',
		5: 'Stereo, minuti e multipli del byte',
		6: 'Bit al secondo e durata in una memoria',
	},
	'inf-von-neumann': {
		1: 'A quale blocco appartiene',
		2: 'Il compito di ogni blocco',
		3: 'Il viaggio di un dato',
		4: 'Il programma memorizzato',
		5: "L'ordine dei passi",
	},
	'inf-cpu': {
		1: 'Le parti della CPU',
		2: "L'accumulatore alla fine",
		3: 'Contatore di programma e registro istruzioni',
		4: 'Una cella che cambia',
		5: 'Istruzioni al secondo',
		6: 'Tempo e core',
	},
	'memoria-storage': {
		1: 'Quale memoria per quale uso',
		2: 'Che cosa si perde senza corrente',
		3: 'Celle e indirizzi',
		4: 'Capacità con i multipli',
		5: 'La gerarchia delle memorie',
	},
	'inf-bus-periferiche': {
		1: 'Ingresso o uscita',
		2: 'Quale bus e in quale verso',
		3: 'Dalle linee alle celle',
		4: 'Dalle celle alle linee',
		5: 'La memoria indirizzabile',
	},
	'inf-tipi-computer': {
		1: 'Quale computer per quale lavoro',
		2: 'Embedded o no',
		3: 'Che cosa cambia e che cosa resta',
		4: 'I blocchi in un sistema embedded',
	},
	'inf-funzioni-so': {
		1: 'I compiti del sistema operativo',
		2: 'Le cinque funzioni',
		3: 'Il modello a strati',
		4: 'Vero o falso sul sistema operativo',
	},
	'inf-avvio-interfacce': {
		1: "Le fasi dell'avvio",
		2: "L'ordine delle fasi",
		3: "Vero o falso sull'avvio",
		4: "Gli elementi dell'interfaccia",
		5: 'Riga di comando o grafica',
	},
	'processi-thread': {
		1: 'Lo stato di un processo',
		2: 'Uno stato, un evento',
		3: 'Una sequenza di eventi',
		4: 'I turni del round robin',
		5: "L'istante di fine",
		6: 'Il tempo in coda',
	},
	'inf-gestione-memoria': {
		1: 'Quante pagine: divisione esatta',
		2: 'Quante pagine: arrotondare per eccesso',
		3: 'Quante pagine: dai mebibyte',
		4: 'Memoria assegnata e inutilizzata',
		5: 'RAM piena: swap e frame liberi',
		6: 'Vero o falso sulla memoria',
	},
	'inf-file-system': {
		1: 'Nomi ed estensioni',
		2: "Dall'albero al percorso",
		3: 'Da relativo ad assoluto',
		4: 'Risalire con i due punti',
		5: 'Copiare, spostare, rinominare',
		6: 'La dimensione dei file',
	},
	'excel': {
		1: 'Celle e intervalli',
		2: 'Una formula con i riferimenti',
		3: 'Le precedenze',
		4: 'Parentesi e potenze',
		5: 'Il ricalcolo',
		6: 'Gli errori',
	},
	'inf-riferimenti-celle': {
		1: 'Copiare lungo la colonna',
		2: "Copiare in un'altra colonna",
		3: 'Riferimenti assoluti',
		4: 'Riferimenti misti',
		5: 'Il valore dopo la copia',
		6: 'Quale formula scrivere',
	},
	'inf-funzioni-foglio': {
		1: 'SOMMA e MEDIA',
		2: 'MIN, MAX e CONTA.NUMERI',
		3: 'Celle vuote e testo',
		4: 'Più argomenti',
		5: 'ARROTONDA',
		6: 'Funzioni annidate',
	},
	'inf-funzioni-logiche': {
		1: 'Confronti: VERO o FALSO',
		2: 'La funzione SE',
		3: 'SE annidati: le fasce',
		4: 'E, O, NON',
		5: 'CONTA.SE',
		6: 'SOMMA.SE',
	},
	'inf-grafici-dati': {
		1: 'Serie, categorie e legenda',
		2: 'Il grafico giusto',
		3: 'Il grafico sbagliato',
		4: "L'asse tagliato",
	},
	'inf-analisi-dati': {
		1: 'Ordinare su una colonna',
		2: 'Ordinare su due livelli',
		3: 'Filtrare',
		4: 'Due filtri insieme',
		5: 'I subtotali',
		6: 'La tabella pivot',
	},
	'word': {
		1: 'Contenuto o formattazione',
		2: "L'area del testo",
		3: 'I caratteri non stampabili',
		4: 'Invii o interruzione di pagina',
		5: 'Il formato del file',
	},
	'inf-stili-indici': {
		1: 'Lo stile giusto',
		2: 'Modificare uno stile',
		3: "Le voci dell'indice",
		4: "L'indice dopo una modifica",
		5: 'La numerazione automatica',
		6: 'Le celle di una tabella',
	},
	'powerpoint': {
		1: 'Lo scopo in una frase',
		2: 'Quante slide',
		3: "Un'idea per slide",
		4: 'Apertura, sviluppo, chiusura',
		5: 'Il tempo di ogni parte',
		6: "L'ordine della scaletta",
	},
	'creare-slide': {
		1: 'La regola non rispettata',
		2: 'La slide che rispetta le regole',
		3: "L'immagine o il grafico giusto",
		4: "I pixel di un'immagine",
		5: 'Schema, slide, animazione, transizione',
		6: 'Le fonti delle immagini',
	},
	'internet': {
		1: 'Reti locali e reti geografiche',
		2: 'Le parole delle reti',
		3: 'Il Wi-Fi non è Internet',
		4: 'Quanti pacchetti',
		5: 'Che cosa decide un protocollo',
		6: 'Vero o falso su Internet',
	},
	'inf-client-server': {
		1: 'Chi è il client, chi è il server',
		2: 'Richiesta e risposta',
		3: 'I compiti del client e del server',
		4: 'Un messaggio passa dal server',
		5: 'Client-server o peer-to-peer',
		6: 'Vero o falso sul client-server',
	},
	'inf-indirizzi-domini': {
		1: 'Riconoscere un indirizzo IP',
		2: 'I byte di un indirizzo',
		3: 'Quanti indirizzi con n bit',
		4: 'I livelli di un nome di dominio',
		5: 'Di chi è il sito',
		6: 'Il DNS',
	},
	'http-html': {
		1: 'Le parole del web',
		2: 'Le parti di un URL',
		3: 'Stesso sito o un altro sito',
		4: 'Richieste e codici di stato',
		5: 'Quante richieste per una pagina',
		6: 'Vero o falso sul web',
	},
	'inf-servizi-internet': {
		1: 'Le parti di un indirizzo',
		2: 'Il viaggio di un messaggio',
		3: 'A, Cc o Ccn',
		4: 'Chi riceve e chi vede',
		5: 'Quale servizio usare',
		6: 'Vero o falso sui servizi di rete',
	},
	'inf-ricerca-informazioni': {
		1: 'Come lavora un motore di ricerca',
		2: 'Dalla domanda alle parole chiave',
		3: 'Scrivere la ricerca con un operatore',
		4: 'Che cosa trova una ricerca',
		5: 'Le quattro domande su una fonte',
		6: 'Confrontare e citare le fonti',
	},
	'cloud': {
		1: 'Che cos\'è il cloud',
		2: 'Quanto spazio serve',
		3: 'Che cosa fa la sincronizzazione',
		4: 'Scegliere il permesso',
		5: 'Invito o link',
		6: 'Lavorare insieme nel cloud',
	},
	'virus-malware': {
		1: 'Come si diffonde un malware',
		2: 'Che cosa fa un malware',
		3: 'L\'estensione vera di un file',
		4: 'Che cosa fare',
		5: 'Vero o falso sui malware',
	},
	'password-sicure': {
		1: 'I fattori di autenticazione',
		2: 'Quante password possibili',
		3: 'Più lunga o più varia',
		4: 'Il tempo per provarle tutte',
		5: 'La difesa giusta',
		6: 'Le abitudini che contano',
	},
	'inf-phishing': {
		1: 'I segnali in un messaggio',
		2: 'Il dominio che conta',
		3: 'Di chi è questo indirizzo',
		4: 'Che cosa fare',
		5: 'Vero o falso sul phishing',
	},
	'inf-privacy': {
		1: 'È un dato personale?',
		2: 'Interessato e titolare',
		3: 'Le regole di chi tratta i dati',
		4: 'I tuoi diritti',
		5: 'I permessi di un\'app',
		6: 'Vero o falso sulla privacy',
	},
	'inf-diritto-autore': {
		1: 'Che cosa protegge il diritto d\'autore',
		2: 'Citazione, plagio o permesso',
		3: 'Leggere una sigla Creative Commons',
		4: 'Scegliere la licenza',
		5: 'Le licenze del software',
		6: 'In una ricerca o in una presentazione',
	},
	'algoritmi': {
		1: 'Le proprietà di un algoritmo',
		2: 'Eseguire un algoritmo',
		3: 'Un algoritmo che sceglie o ripete',
		4: 'Algoritmo, esecutore, programma',
		5: 'Scegliere il diagramma giusto',
		6: 'Costruire il diagramma',
	},
	'inf-problema-algoritmo': {
		1: 'Dati di ingresso e di uscita',
		2: 'Il risultato atteso',
		3: 'Il caso di prova che trova l\'errore',
		4: 'Dal problema al diagramma',
		5: 'Un problema con una ripetizione',
		6: 'Costruire il diagramma di un problema',
	},
	'diagrammi-flusso': {
		1: 'I blocchi e le frecce',
		2: 'Leggere una sequenza',
		3: 'Leggere una selezione',
		4: 'Leggere una ripetizione',
		5: 'Dal diagramma al programma',
		6: 'Costruire un diagramma',
	},
	'inf-pseudocodice': {
		1: 'Le parole dello pseudocodice',
		2: 'Quoziente e resto: div e mod',
		3: 'Dal blocco alla riga',
		4: 'Contare il rientro',
		5: 'Un rientro sbagliato',
		6: 'Dallo pseudocodice al diagramma',
	},
	'inf-bohm-jacopini': {
		1: 'Riconoscere la struttura',
		2: 'Selezione o iterazione?',
		3: 'Una struttura dentro l\'altra',
		4: 'Il teorema di Böhm-Jacopini',
		5: 'Togliere i salti',
		6: 'Costruire il diagramma senza salti',
	},
	'scratch': {
		1: 'Blocchi ed errori',
		2: 'Il "ripeti" con il contatore',
		3: 'Un errore logico',
		4: 'Dai blocchi al diagramma',
		5: 'Costruire il diagramma di un programma a blocchi',
	},
	'inf-linguaggi-programmazione': {
		1: 'Linguaggio macchina e alto livello',
		2: 'Le parole della traduzione',
		3: 'Compilatore o interprete',
		4: 'Un nome scritto male',
		5: 'Vero o falso sui traduttori',
	},
	'inf-input-output': {
		1: 'Testi e conti da stampare',
		2: 'Che cosa stampa dopo una lettura',
		3: 'Quale programma stampa',
		4: 'Costruire il diagramma',
		5: 'Scrivere il programma',
	},
	'inf-variabili-tipi': {
		1: 'Seguire gli assegnamenti',
		2: 'Scambiare due variabili',
		3: 'Il tipo giusto per un dato',
		4: 'Sommare numeri, unire testi',
		5: 'Costruire il diagramma di un calcolo',
		6: 'Scrivere il programma di un calcolo',
	},
	'inf-espressioni': {
		1: 'L\'ordine dei calcoli',
		2: 'Quoziente o resto',
		3: 'Spezzare un numero in parti',
		4: 'La divisione in Python e in C++',
		5: 'Costruire il diagramma di un conto',
		6: 'Scrivere il programma di un conto',
	},
	'inf-errori-debug': {
		1: 'Che tipo di errore è',
		2: 'Leggere un messaggio di errore',
		3: 'Trovare l\'errore in un programma',
		4: 'Trovare l\'errore in un diagramma',
		5: 'Correggere un diagramma',
		6: 'Correggere un programma',
	},
	'inf-condizioni': {
		1: 'Vera o falsa',
		2: 'Le parole del confine',
		3: 'Il rombo in un diagramma',
		4: 'Confronti che ingannano',
		5: 'Costruire il diagramma con una condizione',
		6: 'Scrivere la condizione',
	},
	'inf-selezione-due-vie': {
		1: 'Che cosa scrive un if',
		2: 'Che cosa scrive un if-else',
		3: 'Dalla consegna al programma',
		4: 'Dal programma al diagramma',
		5: 'Costruire il diagramma di una selezione',
		6: 'Scrivere una selezione',
	},
	'inf-operatori-logici': {
		1: 'Tabelle di verità',
		2: 'Che cosa scrive con E, O, NON',
		3: 'Dentro o fuori da un intervallo',
		4: 'Negare una condizione',
		5: 'Costruire il diagramma di una condizione composta',
		6: 'Scrivere una condizione composta',
	},
	'inf-selezione-multipla': {
		1: 'Due selezioni annidate',
		2: 'Una cascata con le soglie',
		3: 'L\'ordine delle condizioni',
		4: 'Dalla consegna alla cascata',
		5: 'Completare il diagramma con due selezioni',
		6: 'Scrivere una cascata',
	},
	'inf-ciclo-while': {
		1: 'Che cosa scrive un ciclo',
		2: 'Quanti giri fa un ciclo',
		3: 'Dal diagramma al programma',
		4: 'Dal programma al diagramma',
		5: 'Costruire il diagramma di un ciclo',
		6: 'Scrivere un ciclo',
	},
	'inf-ciclo-for': {
		1: 'Che cosa scrive un for',
		2: 'Il passo e il conto alla rovescia',
		3: 'Quanti giri fa un for',
		4: 'Dal while al for',
		5: 'Costruire il diagramma di un for',
		6: 'Scrivere un ciclo for',
	},
	'inf-contatori-accumulatori': {
		1: 'Contare i dati che interessano',
		2: 'Sommare i dati',
		3: 'Il prodotto parte da 1',
		4: 'Un errore nel programma',
		5: 'Costruire il diagramma di un totale',
		6: 'Scrivere un ciclo che conta o somma',
	},
	'inf-cicli-annidati': {
		1: 'Quante volte gira il corpo interno',
		2: 'Che cosa scrive un ciclo doppio',
		3: 'Il ciclo interno che dipende da quello esterno',
		4: 'Le righe di un disegno',
		5: 'I due cicli di una tabella',
		6: 'Scrivere due cicli annidati',
	},
	'inf-massimo-minimo-media': {
		1: 'Il più grande e il più piccolo',
		2: 'Partire da 0 è un errore',
		3: 'Una sequenza chiusa da un valore',
		4: 'La media',
		5: 'Costruire il diagramma del massimo',
		6: 'Scrivere il programma di una sequenza',
	},
	'inf-definire-funzioni': {
		1: 'Seguire una chiamata',
		2: 'Contare le chiamate',
		3: 'Quale programma scrive questo',
		4: 'Una funzione con un parametro',
		5: 'Scrivere una funzione',
	},
	'inf-parametri-ritorno': {
		1: 'Argomenti e parametri',
		2: 'Il risultato in un conto',
		3: 'Stampare o restituire',
		4: "Una funzione ne chiama un'altra",
		5: 'Quale funzione restituisce questo',
		6: 'Scrivere una funzione con return',
	},
	'inf-visibilita': {
		1: 'Dove esiste una variabile',
		2: 'Due variabili con lo stesso nome',
		3: 'Una variabile globale',
		4: 'Senza variabili globali',
		5: 'Scrivi la funzione',
	},
	'inf-passaggio-parametri': {
		1: 'Il parametro è una copia',
		2: 'La variabile di chi chiama cambia',
		3: 'Una funzione che modifica un vettore',
		4: 'Quale funzione lo fa',
		5: 'Scrivi la funzione',
	},
	'inf-top-down': {
		1: 'Riconoscere i sottoproblemi',
		2: 'Che cosa riceve e restituisce',
		3: 'Funzioni ancora vuote',
		4: 'Seguire il programma scomposto',
		5: 'Riempire la funzione vuota',
		6: 'Scrivere la funzione che manca',
	},
	'inf-vettori': {
		1: 'Indici ed elementi',
		2: 'Leggere e scrivere un elemento',
		3: 'Scorrere un vettore',
		4: 'Quale ciclo fa questo',
		5: 'Un vettore in una funzione',
		6: 'Scrivere un programma con un vettore',
	},
	'inf-ricerca-sequenziale': {
		1: 'Contare i confronti',
		2: 'Che cosa scrive la ricerca',
		3: 'Quale funzione cerca bene',
		4: 'Caso migliore, peggiore e medio',
		5: 'Scrivere la ricerca',
	},
	'inf-matrici': {
		1: 'Un elemento, due indici',
		2: 'Una riga o una colonna',
		3: 'Due cicli annidati',
		4: 'Scegliere i cicli giusti',
		5: 'Le due diagonali',
		6: 'Scrivere i cicli',
	},
	'inf-stringhe': {
		1: 'Lunghezza e caratteri',
		2: 'Contare con un ciclo',
		3: 'Costruire una stringa',
		4: 'Confrontare due stringhe',
		5: 'Scegliere la funzione giusta',
		6: 'Scrivere il ciclo',
	},
	'inf-ricerca-binaria': {
		1: 'Un giro della ricerca',
		2: 'Che cosa scrive la ricerca',
		3: 'Contare i confronti',
		4: 'Il corpo del ciclo',
		5: 'Scrivere la ricerca binaria',
	},
	'inf-selection-sort': {
		1: 'Trovare il minimo',
		2: 'Lo scambio',
		3: "Un giro dell'ordinamento",
		4: 'Confronti e scambi',
		5: 'Il corpo del giro',
		6: "Scrivere l'ordinamento",
	},
	'inf-bubble-sort': {
		1: 'Un giro delle bolle',
		2: 'Confronti e scambi',
		3: 'Che cosa scrive il programma',
		4: 'Quale ciclo interno ordina',
		5: "Scrivere l'ordinamento a bolle",
	},
	'inf-insertion-sort': {
		1: 'Inserire un elemento',
		2: 'Confronti e spostamenti',
		3: 'Che cosa scrive il programma',
		4: 'Quale ciclo ordina',
		5: "Scrivere l'inserimento",
	},
	'inf-confronto-algoritmi': {
		1: 'Contare i confronti',
		2: 'Caso migliore e caso peggiore',
		3: 'Quando n raddoppia',
		4: 'Dove va il contatore',
		5: 'Quanto lavoro, quanto tempo',
		6: 'Scrivere un programma che conta',
	},
	'inf-file-testo': {
		1: 'Leggere le righe',
		2: 'I numeri di un file',
		3: 'Che cosa resta nel file',
		4: 'Quale programma',
		5: 'Scrivere e rileggere un file',
	},
	'inf-file-csv': {
		1: 'I campi di una riga',
		2: 'Leggere la tabella',
		3: 'Calcolare su una colonna',
		4: 'Quale programma',
		5: 'Scrivere un file CSV',
		6: 'Leggere righe con i campi',
	},
	'inf-xml-json': {
		1: "Leggere l'albero di un XML",
		2: 'XML ben formato',
		3: 'Leggere un JSON',
		4: 'JSON valido',
		5: "Da un formato all'altro",
	},
	'formati-multimediali': {
		1: "Che cosa c'è nel file",
		2: 'Il nome o il contenuto',
		3: 'Il formato con queste proprietà',
		4: 'Il formato per lo scopo',
		5: 'Contenitori, codec, formati aperti',
	},
	'inf-bitmap-vettoriale': {
		1: 'Bitmap o vettoriale',
		2: 'Leggere un SVG',
		3: 'I pixel per la stampa',
		4: 'Quanto viene grande la stampa',
		5: 'Che cosa succede ai pixel',
	},
	'inf-compressione': {
		1: 'Che compressione è',
		2: 'RLE a mano',
		3: 'Quanti byte, e conviene?',
		4: 'Il rapporto di compressione',
		5: 'Codici di lunghezza diversa',
		6: 'Comprimere due volte',
	},
	'inf-audio-video': {
		1: 'Il bitrate di un suono',
		2: 'Dal bitrate alla dimensione',
		3: 'Un video non compresso',
		4: 'Fotogrammi chiave e differenze',
		5: 'Streaming, codec e contenitore',
	},
	'inf-font': {
		1: 'Carattere, glifo o font',
		2: 'Un font bitmap',
		3: 'Le famiglie di caratteri',
		4: 'Corpo e interlinea',
		5: 'Quale font usa il browser',
	},
	'inf-markup': {
		1: 'Le parti di un elemento',
		2: 'Tag chiusi e annidati',
		3: "L'albero degli elementi",
		4: 'Struttura, aspetto e istruzioni',
		5: 'Da Markdown a HTML',
	},
	'inf-html-struttura': {
		1: 'Lo scheletro della pagina',
		2: 'Titoli e paragrafi',
		3: 'Le parti della pagina',
		4: "L'albero del documento",
		5: 'Commenti ed errori',
	},
	'inf-html-testo-link': {
		1: 'Enfasi e a capo',
		2: 'Dove porta un link',
		3: 'Scrivere un percorso relativo',
		4: 'Altri siti e punti della pagina',
		5: 'Le immagini',
	},
	'inf-html-elenchi-tabelle': {
		1: 'Puntato o numerato',
		2: 'Elenchi annidati',
		3: 'Righe e colonne',
		4: 'Scrivere una tabella',
		5: 'Celle larghe: colspan',
		6: 'Celle alte: rowspan',
	},
	'inf-html-moduli': {
		1: 'Il campo giusto',
		2: 'Etichetta e campo',
		3: 'Che cosa viene inviato',
		4: 'Caselle, pallini e menu',
		5: 'GET e POST',
		6: 'I controlli del browser',
	},
	'inf-css-regole': {
		1: 'Scrivere una regola',
		2: 'Che cosa prende un selettore',
		3: 'Scegliere il selettore',
		4: 'Il colore ereditato',
		5: 'Quale regola vince',
	},
	'inf-css-box': {
		1: 'Le parti della scatola',
		2: 'Scritture brevi',
		3: 'Quanto è larga una scatola',
		4: 'Con border-box',
		5: 'Trovare la width',
		6: 'Blocchi, righe e margini',
	},
	'inf-css-layout': {
		1: 'Contenitore ed elementi',
		2: 'Direzione e assi',
		3: 'Lo spazio che avanza',
		4: 'Andare a capo',
		5: 'Impaginare la pagina',
	},
	'inf-responsive': {
		1: 'Unità relative',
		2: 'Quale regola è attiva',
		3: 'Prima il telefono',
		4: 'Immagini che si adattano',
		5: 'Il contrasto',
		6: 'Una pagina accessibile',
	},
	'inf-script-client': {
		1: 'Dove gira lo script',
		2: 'Che cosa scrive la console',
		3: 'Selezione e confronti',
		4: 'Cicli e funzioni',
		5: 'Da Python a JavaScript',
	},
	'inf-dom-eventi': {
		1: 'Quale elemento prende il selettore',
		2: 'Che cosa cambia nella pagina',
		3: 'Dopo il clic',
		4: 'Registrare un ascoltatore',
		5: 'Creare elementi',
	},
	'inf-validazione-moduli': {
		1: 'Leggere un campo',
		2: 'Quale valore passa il controllo',
		3: 'Quale messaggio compare',
		4: 'Il modulo parte?',
		5: 'Scrivere il controllo',
	},
};

/** The name of a level, or null when it has none. */
export const levelName = (generator: string, level: number): string | null => levelNames[generator]?.[level] ?? null;
