/**
 * What each exercise level adds, in the student's words: the names of the nodes on a lesson's exercise path.
 * Written from specs/exercises/*.md; keyed by generator id, then by level.
 */
export const levelNames: Record<string, Record<number, string>> = {
	'prime-definizioni': {
		1: 'Riconoscere un insieme',
		2: 'Appartiene o no: ∈ e ∉',
		3: 'Appartiene a ℕ, a ℤ o a ℚ',
		4: "Trovare l'insieme vuoto",
		5: "Quanti elementi ha l'insieme",
		6: 'Finito o infinito',
	},
	'insiemi-rappresentazione': {
		1: "Dalla proprietà all'elenco",
		2: 'Pari, multipli, divisori e lo zero',
		3: 'Numeri negativi: in ℕ o in ℤ',
		4: 'Condizioni con un calcolo',
		5: "Dall'elenco alla proprietà",
	},
	'sottoinsiemi-ugualianza': {
		1: 'Vero o falso: A ⊆ B',
		2: 'Appartenenza o inclusione: ∈ e ⊆',
		3: 'Inclusione stretta: ⊂ e ⊆',
		4: 'Sottoinsiemi propri e quanti sono',
		5: 'Quando due insiemi sono uguali',
	},
	'insiemi-unione': {
		1: 'Unione di due insiemi',
		2: 'Insiemi descritti a parole',
		3: 'Unione di tre insiemi',
		4: "Le proprietà dell'unione",
		5: "Contare gli elementi dell'unione",
		6: 'Problemi con due gruppi',
	},
	'insiemi-operazioni': {
		1: "L'intersezione: gli elementi comuni",
		2: "La differenza, dove conta l'ordine",
		3: 'Il complementare in U',
		4: 'Il prodotto cartesiano',
		5: 'Espressioni e leggi di De Morgan',
		6: 'Problemi con il diagramma',
	},
	'numeri-naturali-operazioni': {
		1: 'Quale proprietà è stata usata',
		2: 'Lo zero e la divisione con resto',
		3: 'Espressioni senza parentesi',
		4: 'Con le parentesi tonde',
		5: 'Con tonde e quadre',
		6: 'Con tonde, quadre e graffe',
		7: 'Problemi con le quattro operazioni',
	},
	'numeri-naturali-mcm-mcd': {
		1: 'I criteri di divisibilità',
		2: 'Scomporre in fattori primi',
		3: 'MCD e MCM di due numeri',
		4: 'MCD e MCM di tre numeri',
		5: "L'algoritmo di Euclide",
		6: 'Problemi con MCD e MCM',
	},
	'numeri-naturali-potenze': {
		1: 'Il valore di una potenza',
		2: 'Proprietà con la stessa base',
		3: 'Proprietà con lo stesso esponente',
		4: 'Riportare alla stessa base',
		5: 'Espressioni con le potenze',
	},
	'numeri-naturali-divisibilita': {
		1: 'Divisibile o no: fai la divisione',
		2: 'Un criterio alla volta',
		3: 'Tutti i criteri su un numero',
		4: 'Primo o composto',
		5: 'Scomporre in fattori primi',
		6: 'Divisori dalla scomposizione',
	},
	'numeri-interi-valore-assoluto': {
		1: 'Segno e appartenenza a ℕ e ℤ',
		2: 'Opposto e valore assoluto',
		3: 'Confrontare due interi',
		4: 'Ordinare gli interi',
		5: 'Ordinare opposti e valori assoluti',
		6: 'Gli interi tra due estremi',
	},
	'numeri-interi-operazioni': {
		1: 'Addizione di due interi',
		2: 'Sottrazione di due interi',
		3: 'Somma algebrica con più termini',
		4: 'Togliere le parentesi',
		5: 'La regola dei segni',
		6: 'Espressioni con tutte le operazioni',
	},
	'numeri-interi-potenze': {
		1: 'Potenze con base negativa',
		2: 'Il meno fuori e le potenze di −1',
		3: 'Una proprietà con base negativa',
		4: 'Basi opposte o stesso esponente',
		5: 'Espressioni con le potenze',
		6: 'Espressioni con le parentesi',
	},
	'numeri-razionali-frazioni': {
		1: 'La frazione di un numero',
		2: "Dalla parte all'intero",
		3: 'Propria, impropria o apparente',
		4: 'Frazioni equivalenti',
		5: 'Ridurre ai minimi termini',
		6: 'Ridurre con il segno meno',
	},
	'numeri-razionali-confronto-frazioni': {
		1: 'Frazioni equivalenti',
		2: 'Con lo stesso denominatore',
		3: 'Con lo stesso numeratore',
		4: 'Con il denominatore comune',
		5: 'Con le frazioni negative',
		6: 'Ordinare più frazioni',
	},
	'numeri-razionali-operazioni': {
		1: 'Somme con lo stesso denominatore',
		2: 'Somme con denominatori diversi',
		3: 'Frazioni negative e numeri interi',
		4: 'Il prodotto di due frazioni',
		5: 'La divisione tra frazioni',
		6: 'Due operazioni insieme',
		7: 'Problemi con le frazioni',
	},
	'numeri-razionali-potenze': {
		1: 'La potenza di una frazione',
		2: 'Base negativa e meno davanti',
		3: 'Esponente 0 ed esponente 1',
		4: "L'esponente negativo",
		5: 'Le proprietà delle potenze',
		6: 'Espressioni con le potenze',
	},
	'numeri-razionali-conversione': {
		1: 'Da decimale limitato a frazione',
		2: 'Da periodico semplice a frazione',
		3: 'Da periodico misto a frazione',
		4: 'Prevedere il tipo di decimale',
		5: 'Da frazione a decimale',
	},
	'numeri-razionali-espressioni': {
		1: "L'ordine delle operazioni",
		2: 'Una parentesi e i segni meno',
		3: 'Potenze con esponenti negativi',
		4: 'Frazioni di frazioni',
		5: 'Frazioni di frazioni con decimali',
		6: 'Tonde, quadre e graffe',
	},
	'numeri-razionali-proporzioni': {
		1: 'Il rapporto tra due numeri',
		2: 'Trovare la x con numeri interi',
		3: 'Con frazioni, decimali o negativi',
		4: 'Parte, percentuale e totale',
		5: 'Aumenti e sconti',
		6: "Variazioni una dopo l'altra",
		7: 'Problemi con le proporzioni',
	},
	'monomi-grado': {
		1: 'Grado rispetto a una lettera',
		2: 'Il grado complessivo',
		3: 'Quando il grado è zero',
		4: 'Una potenza nel coefficiente',
		5: 'Prima ridurre a forma normale',
		6: "Il grado dopo un'operazione",
	},
	'monomi-operazioni': {
		1: 'Sommare monomi simili',
		2: 'Somme con coefficienti frazionari',
		3: 'Somme con monomi non simili',
		4: 'Il prodotto di monomi',
		5: 'Il quoziente di monomi',
		6: 'La potenza di un monomio',
	},
	'monomi-mcm-mcd': {
		1: 'Due monomi con le stesse lettere',
		2: 'Lettere non in comune',
		3: 'Coefficienti negativi',
		4: 'Con tre monomi',
		5: 'Coefficienti frazionari',
	},
	'monomi-espressioni': {
		1: 'Prima moltiplica o dividi, poi somma',
		2: 'Prodotti e quozienti in fila',
		3: 'Con le potenze',
		4: 'Una parentesi con una somma',
		5: 'Tonde, quadre e graffe',
	},
	'equazioni-primo-grado': {
		1: 'Un solo termine con la x',
		2: 'La x in tutti e due i membri',
		3: 'Con le parentesi',
		4: 'La soluzione è una frazione',
		5: 'Con i denominatori',
		6: 'Impossibili e indeterminate',
		7: "Dal problema all'equazione",
	},
	'equazioni-secondo-grado': {
		1: 'Equazioni pure e spurie',
		2: 'Coefficiente di x² uguale a 1',
		3: 'Coefficiente di x² diverso da 1',
		4: 'Il delta non è un quadrato',
		5: 'Termini in tutti e due i membri',
		6: 'Il delta è zero o negativo',
	},
	'funzioni-iniettive-suriettive-biettive': {
		1: "L'immagine di una funzione",
		2: 'Funzioni date elemento per elemento',
		3: 'Funzioni date con una formula',
		4: 'Funzioni su ℝ e su [0, +∞)',
		5: 'Funzioni su ℤ, ℚ, ℕ e ℝ ∖ {0}',
		6: 'La funzione inversa',
	},
	// Chemistry: the names of the Python generators' levels (scripts/chimica/esercizi/).
	'mole-massa-molare': {
		1: 'La formula dal disegno',
		2: 'La massa molare',
		3: 'Dalla massa alle moli',
		4: 'Molecole e atomi',
		5: 'Composizione percentuale',
	},
	'geometria-molecolare-vsepr': {
		1: 'Senza coppie solitarie',
		2: 'Con coppie solitarie',
		3: 'Legami doppi e tripli',
		4: "L'angolo di legame",
		5: 'Polare o apolare',
	},
	'alcani-nomenclatura': {
		1: 'Un solo metile',
		2: 'Più metili',
		3: 'Sostituenti diversi',
		4: 'La catena nascosta',
		5: 'Tutto insieme',
	},
	'isomeria': {
		1: 'Isomeri o no',
		2: "Che relazione c'è",
		3: 'Carboni chirali',
		4: 'E o Z',
		5: 'R o S',
	},
	'gruppi-funzionali': {
		1: 'Un gruppo solo',
		2: 'Trova il gruppo',
		3: 'I gruppi che si confondono',
		4: 'Molecole vere',
		5: 'Tutti i gruppi',
	},
	'amminoacidi-legame-peptidico': {
		1: 'Le parti di un amminoacido',
		2: 'Le catene laterali',
		3: 'Il dipeptide giusto',
		4: 'Contare i legami peptidici',
		5: 'La forma a pH 7',
	},
};

/** The name of a level, or null when it has none. */
export const levelName = (generator: string, level: number): string | null => levelNames[generator]?.[level] ?? null;
