/**
 * What each exercise level adds, in the student's words: the names of the nodes on a lesson's exercise path.
 * Written from specs/exercises/*.md; keyed by generator id, then by level.
 */
export const levelNames: Record<string, Record<number, string>> = {
	'prime-definizioni': {
		1: 'Riconoscere un insieme',
		2: 'Appartiene o no: ∈ e ∉',
		3: 'Appartiene a ℕ, a ℤ o a ℚ',
		4: "Trovare l'insieme vuoto",
		5: "Quanti elementi ha l'insieme",
		6: 'Finito o infinito',
	},
	'insiemi-rappresentazione': {
		1: "Dalla proprietà all'elenco",
		2: 'Pari, multipli, divisori e lo zero',
		3: 'Numeri negativi: in ℕ o in ℤ',
		4: 'Condizioni con un calcolo',
		5: "Dall'elenco alla proprietà",
	},
	'sottoinsiemi-ugualianza': {
		1: 'Vero o falso: A ⊆ B',
		2: 'Appartenenza o inclusione: ∈ e ⊆',
		3: 'Inclusione stretta: ⊂ e ⊆',
		4: 'Sottoinsiemi propri e quanti sono',
		5: 'Quando due insiemi sono uguali',
	},
	'insiemi-unione': {
		1: 'Unione di due insiemi',
		2: 'Insiemi descritti a parole',
		3: 'Unione di tre insiemi',
		4: "Le proprietà dell'unione",
		5: "Contare gli elementi dell'unione",
		6: 'Problemi con due gruppi',
	},
	'insiemi-operazioni': {
		1: "L'intersezione: gli elementi comuni",
		2: "La differenza, dove conta l'ordine",
		3: 'Il complementare in U',
		4: 'Il prodotto cartesiano',
		5: 'Espressioni e leggi di De Morgan',
		6: 'Problemi con il diagramma',
	},
	'numeri-naturali-operazioni': {
		1: 'Quale proprietà è stata usata',
		2: 'Lo zero e la divisione con resto',
		3: 'Espressioni senza parentesi',
		4: 'Con le parentesi tonde',
		5: 'Con tonde e quadre',
		6: 'Con tonde, quadre e graffe',
		7: 'Problemi con le quattro operazioni',
	},
	'numeri-naturali-mcm-mcd': {
		1: 'I criteri di divisibilità',
		2: 'Scomporre in fattori primi',
		3: 'MCD e MCM di due numeri',
		4: 'MCD e MCM di tre numeri',
		5: "L'algoritmo di Euclide",
		6: 'Problemi con MCD e MCM',
	},
	'numeri-naturali-potenze': {
		1: 'Il valore di una potenza',
		2: 'Proprietà con la stessa base',
		3: 'Proprietà con lo stesso esponente',
		4: 'Riportare alla stessa base',
		5: 'Espressioni con le potenze',
	},
	'numeri-naturali-divisibilita': {
		1: 'Divisibile o no: fai la divisione',
		2: 'Un criterio alla volta',
		3: 'Tutti i criteri su un numero',
		4: 'Primo o composto',
		5: 'Scomporre in fattori primi',
		6: 'Divisori dalla scomposizione',
	},
	'numeri-interi-valore-assoluto': {
		1: 'Segno e appartenenza a ℕ e ℤ',
		2: 'Opposto e valore assoluto',
		3: 'Confrontare due interi',
		4: 'Ordinare gli interi',
		5: 'Ordinare opposti e valori assoluti',
		6: 'Gli interi tra due estremi',
	},
	'numeri-interi-operazioni': {
		1: 'Addizione di due interi',
		2: 'Sottrazione di due interi',
		3: 'Somma algebrica con più termini',
		4: 'Togliere le parentesi',
		5: 'La regola dei segni',
		6: 'Espressioni con tutte le operazioni',
	},
	'numeri-interi-potenze': {
		1: 'Potenze con base negativa',
		2: 'Il meno fuori e le potenze di −1',
		3: 'Una proprietà con base negativa',
		4: 'Basi opposte o stesso esponente',
		5: 'Espressioni con le potenze',
		6: 'Espressioni con le parentesi',
	},
	'numeri-razionali-frazioni': {
		1: 'La frazione di un numero',
		2: "Dalla parte all'intero",
		3: 'Propria, impropria o apparente',
		4: 'Frazioni equivalenti',
		5: 'Ridurre ai minimi termini',
		6: 'Ridurre con il segno meno',
	},
	'numeri-razionali-confronto-frazioni': {
		1: 'Frazioni equivalenti',
		2: 'Con lo stesso denominatore',
		3: 'Con lo stesso numeratore',
		4: 'Con il denominatore comune',
		5: 'Con le frazioni negative',
		6: 'Ordinare più frazioni',
	},
	'numeri-razionali-operazioni': {
		1: 'Somme con lo stesso denominatore',
		2: 'Somme con denominatori diversi',
		3: 'Frazioni negative e numeri interi',
		4: 'Il prodotto di due frazioni',
		5: 'La divisione tra frazioni',
		6: 'Due operazioni insieme',
		7: 'Problemi con le frazioni',
	},
	'numeri-razionali-potenze': {
		1: 'La potenza di una frazione',
		2: 'Base negativa e meno davanti',
		3: 'Esponente 0 ed esponente 1',
		4: "L'esponente negativo",
		5: 'Le proprietà delle potenze',
		6: 'Espressioni con le potenze',
	},
	'numeri-razionali-conversione': {
		1: 'Da decimale limitato a frazione',
		2: 'Da periodico semplice a frazione',
		3: 'Da periodico misto a frazione',
		4: 'Prevedere il tipo di decimale',
		5: 'Da frazione a decimale',
	},
	'numeri-razionali-espressioni': {
		1: "L'ordine delle operazioni",
		2: 'Una parentesi e i segni meno',
		3: 'Potenze con esponenti negativi',
		4: 'Frazioni di frazioni',
		5: 'Frazioni di frazioni con decimali',
		6: 'Tonde, quadre e graffe',
	},
	'numeri-razionali-proporzioni': {
		1: 'Il rapporto tra due numeri',
		2: 'Trovare la x con numeri interi',
		3: 'Con frazioni, decimali o negativi',
		4: 'Parte, percentuale e totale',
		5: 'Aumenti e sconti',
		6: "Variazioni una dopo l'altra",
		7: 'Problemi con le proporzioni',
	},
	'monomi-grado': {
		1: 'Grado rispetto a una lettera',
		2: 'Il grado complessivo',
		3: 'Quando il grado è zero',
		4: 'Una potenza nel coefficiente',
		5: 'Prima ridurre a forma normale',
		6: "Il grado dopo un'operazione",
	},
	'monomi-operazioni': {
		1: 'Sommare monomi simili',
		2: 'Somme con coefficienti frazionari',
		3: 'Somme con monomi non simili',
		4: 'Il prodotto di monomi',
		5: 'Il quoziente di monomi',
		6: 'La potenza di un monomio',
	},
	'monomi-mcm-mcd': {
		1: 'Due monomi con le stesse lettere',
		2: 'Lettere non in comune',
		3: 'Coefficienti negativi',
		4: 'Con tre monomi',
		5: 'Coefficienti frazionari',
	},
	'monomi-espressioni': {
		1: 'Prima moltiplica o dividi, poi somma',
		2: 'Prodotti e quozienti in fila',
		3: 'Con le potenze',
		4: 'Una parentesi con una somma',
		5: 'Tonde, quadre e graffe',
	},
	'equazioni-primo-grado': {
		1: 'Un solo termine con la x',
		2: 'La x in tutti e due i membri',
		3: 'Con le parentesi',
		4: 'La soluzione è una frazione',
		5: 'Con i denominatori',
		6: 'Impossibili e indeterminate',
		7: "Dal problema all'equazione",
	},
	'equazioni-secondo-grado': {
		1: 'Equazioni pure e spurie',
		2: 'Coefficiente di x² uguale a 1',
		3: 'Coefficiente di x² diverso da 1',
		4: 'Il delta non è un quadrato',
		5: 'Termini in tutti e due i membri',
		6: 'Il delta è zero o negativo',
	},
	'funzioni-iniettive-suriettive-biettive': {
		1: "L'immagine di una funzione",
		2: 'Funzioni date elemento per elemento',
		3: 'Funzioni date con una formula',
		4: 'Funzioni su ℝ e su [0, +∞)',
		5: 'Funzioni su ℤ, ℚ, ℕ e ℝ ∖ {0}',
		6: 'La funzione inversa',
	},
	// Physics, first year: from the "Nomi dei livelli" of specs/exercises/<id>.md.
	'fis-metodo-sperimentale': {
		1: 'Le fasi del metodo',
		2: 'Le variabili',
		3: 'Le prove da confrontare',
		4: "I dati e l'ipotesi",
	},
	'fis-grandezze-si': {
		1: 'Unità e prefissi',
		2: "Un prefisso e l'unità",
		3: 'Notazione scientifica',
		4: 'Tra due prefissi',
		5: 'Ore, minuti e km/h',
		6: 'Ordine di grandezza',
	},
	'fis-grandezze-derivate': {
		1: 'Unità di area e volume',
		2: 'Il volume dai dati',
		3: 'La densità',
		4: 'Densità e unità',
		5: 'Massa e volume dalla densità',
		6: 'Riconoscere il materiale',
	},
	'fis-strumenti-misura': {
		1: 'Portata e sensibilità',
		2: 'Scrivere e scegliere',
		3: 'Righello e cilindro',
		4: 'Calibro decimale',
		5: 'Calibro ventesimale',
	},
	'fis-errori-misura': {
		1: 'Casuale o sistematico',
		2: 'Correggere lo zero',
		3: 'Il bersaglio',
		4: 'Precisione e accuratezza',
		5: 'Come rimediare',
	},
	'fis-valore-medio': {
		1: 'Il valore medio',
		2: 'La semidispersione',
		3: 'Scrivere il risultato',
		4: 'Incertezza e sensibilità',
		5: 'Una misura da scartare',
		6: 'Misure compatibili',
	},
	'fis-incertezza-relativa': {
		1: 'Incertezza relativa',
		2: "Dalla relativa all'assoluta",
		3: 'Somme e differenze',
		4: 'Prodotti e quozienti',
		5: 'Potenze e numeri esatti',
		6: 'Formule con più passaggi',
	},
	'fis-cifre-significative': {
		1: 'Contare le cifre',
		2: 'Arrotondare',
		3: 'Somme e differenze',
		4: 'Prodotti e quozienti',
		5: 'Numeri esatti e più passaggi',
	},
	'fis-relazione-laboratorio': {
		1: 'Le parti della relazione',
		2: 'La tabella dei dati',
		3: 'Confronto con il valore atteso',
		4: 'Quale misura migliorare',
		5: "Cercare l'errore sistematico",
	},
	'fis-tabelle-grafici': {
		1: 'Leggere un punto del grafico',
		2: 'Scegliere la scala di un asse',
		3: 'Leggere tra i punti sulla retta',
		4: 'La misura da rifare',
	},
	'fis-proporzionalita-diretta': {
		1: 'La costante con la sua unità',
		2: 'Prevedere un valore',
		3: 'La pendenza dal grafico',
		4: 'Riconoscere il legame',
		5: 'Il termine noto',
	},
	'fis-proporzionalita-inversa': {
		1: 'La costante inversa con la sua unità',
		2: 'Prevedere con la proporzionalità inversa',
		3: 'Prevedere con la proporzionalità quadratica',
		4: 'Riconoscere la legge dalla tabella',
		5: 'Riconoscere la legge dal grafico',
	},
	'fis-scalari-vettori': {
		1: 'Scalare o vettoriale',
		2: 'Vettori uguali e opposti',
		3: 'La scala di un disegno',
		4: 'Distanza e spostamento su una retta',
		5: 'Lo spostamento sulla griglia',
	},
	'fis-operazioni-vettori': {
		1: 'Vettori sulla stessa retta',
		2: 'Il prodotto per un numero',
		3: 'Vettori perpendicolari',
		4: 'La somma sulla griglia',
		5: 'La differenza sulla griglia',
		6: 'Tre forze sulla griglia',
	},
	'fis-seno-coseno': {
		1: "Le componenti con l'angolo dall'asse x",
		2: "L'angolo dall'asse y",
		3: 'I segni nei quattro quadranti',
		4: 'Dalle componenti al vettore',
		5: "L'angolo negli altri quadranti",
		6: 'La somma per componenti',
	},
	'forze': {
		1: 'Leggere il dinamometro',
		2: 'Portata e sensibilità',
		3: 'Forze sulla stessa retta',
		4: 'Forze perpendicolari',
		5: 'Più forze su due direzioni',
	},
	'fis-forza-peso': {
		1: 'Il peso dalla massa',
		2: 'La massa dal dinamometro',
		3: 'La massa in grammi',
		4: 'Il peso su un altro corpo celeste',
		5: 'Da un corpo celeste a un altro',
	},
	'fis-forza-elastica': {
		1: 'La forza dalla legge di Hooke',
		2: "L'allungamento dalla forza",
		3: 'Centimetri e metri',
		4: 'Lunghezza e allungamento',
		5: 'La costante da una tabella',
		6: 'Una massa appesa',
	},
	'fis-attrito': {
		1: "L'attrito dinamico",
		2: 'Il coefficiente di attrito',
		3: "Quanto vale l'attrito",
		4: 'La forza premente non è il peso',
		5: 'Un libro contro la parete',
	},
	'fis-equilibrio-punto': {
		1: "La reazione del piano d'appoggio",
		2: 'La forza equilibrante',
		3: 'Due fili con lo stesso angolo',
		4: 'Un filo orizzontale e uno inclinato',
		5: 'Due fili con angoli diversi',
		6: 'Quanto si può tendere un filo',
	},
	'fis-equilibrio-piano-inclinato': {
		1: 'Le componenti del peso',
		2: 'Altezza e lunghezza',
		3: "L'inclinazione dalla forza",
		4: "L'angolo limite",
		5: 'Fermo o scivola',
	},
	'fis-momento-forza': {
		1: 'Il momento con il braccio',
		2: 'Dal momento alla forza o al braccio',
		3: 'Il momento di una forza obliqua',
		4: 'Il momento totale con il segno',
		5: 'Il momento di una coppia',
	},
	'fis-equilibrio-corpo-rigido': {
		1: "L'asta sul fulcro",
		2: 'La reazione del fulcro',
		3: "L'asta con il suo peso",
		4: 'La trave su due appoggi',
		5: 'La trave con il suo peso',
	},
	'fis-leve': {
		1: 'Il genere della leva',
		2: 'Vantaggiosa o svantaggiosa',
		3: 'La forza motrice',
		4: 'Il braccio e il fulcro',
		5: 'Le carrucole',
	},
	'fis-baricentro': {
		1: 'Il baricentro di due corpi',
		2: 'Il baricentro di tre corpi',
		3: 'Stabile, instabile o indifferente',
		4: "L'angolo di ribaltamento",
		5: 'Quanto può sporgere',
	},
	'fis-pressione': {
		1: "La pressione dalla forza e dall'area",
		2: "L'area in centimetri quadrati",
		3: 'Il peso come forza premente',
		4: "La forza o l'area dalla pressione",
		5: 'Il blocco appoggiato su una faccia',
	},
	'fis-legge-pascal': {
		1: 'La pressione trasmessa',
		2: 'La forza sul pistone grande',
		3: 'La forza per reggere un carico',
		4: 'I diametri dei pistoni',
		5: 'Gli spostamenti dei pistoni',
	},
	'fis-legge-stevino': {
		1: 'La pressione idrostatica',
		2: 'Profondità in centimetri',
		3: 'La pressione totale',
		4: 'La profondità dalla superficie',
		5: 'La profondità dalla pressione',
		6: 'Il tubo a U',
	},
	'fis-pressione-atmosferica': {
		1: 'Le unità della pressione',
		2: 'Millimetri di mercurio ed ettopascal',
		3: "La forza dell'aria su una superficie",
		4: 'La colonna di un barometro',
		5: 'La ventosa e gli emisferi',
	},
	'fis-archimede': {
		1: 'La spinta su un corpo immerso',
		2: 'Il peso apparente',
		3: 'Dalle letture dei due dinamometri',
		4: 'La parte immersa di un corpo che galleggia',
		5: 'La densità dalla linea di galleggiamento',
		6: 'Il carico massimo',
	},
	'ottica-geometrica': {
		1: 'Il tempo della luce',
		2: 'Chilometri e minuti',
		3: "L'anno luce",
		4: "L'ombra di un cartoncino",
		5: 'La camera oscura',
		6: "L'ombra al contrario",
	},
	'riflessione': {
		1: "L'angolo tra i due raggi",
		2: "Dall'angolo con lo specchio",
		3: "L'immagine nello specchio piano",
		4: 'Lo specchio per vedersi per intero',
		5: 'Due specchi ad angolo',
	},
	'fis-specchi-sferici': {
		1: 'Il fuoco e il raggio di curvatura',
		2: "L'immagine reale di uno specchio concavo",
		3: "Altezza e verso dell'immagine",
		4: "L'immagine virtuale dello specchio concavo",
		5: 'Lo specchio convesso',
		6: "La distanza focale dall'immagine",
	},
	'fis-rifrazione': {
		1: "L'indice e la velocità della luce",
		2: "L'angolo di rifrazione",
		3: "L'indice dagli angoli",
		4: 'Verso un mezzo meno rifrangente',
		5: "L'angolo limite",
		6: 'Esce o si riflette tutto?',
	},
	'fis-dispersione': {
		1: 'I colori nel prisma',
		2: 'Il colore dei corpi in luce colorata',
		3: 'La sintesi additiva',
		4: 'La sintesi sottrattiva',
		5: 'Corpi gialli, ciano e magenta',
		6: 'Di quanto si separano i colori',
	},
	'fis-lenti': {
		1: 'Il potere diottrico',
		2: "L'immagine reale",
		3: "L'ingrandimento",
		4: "L'immagine virtuale",
		5: 'La lente divergente',
		6: 'Dalle distanze alla distanza focale',
	},
	'fis-strumenti-ottici': {
		1: 'Cannocchiale e microscopio',
		2: 'Le lenti per la miopia',
		3: "Le lenti per l'ipermetropia",
		4: 'La macchina fotografica',
		5: "La lente d'ingrandimento",
		6: "Il potere dell'occhio",
	},
	// Physics, second year.
	'fis-punto-materiale': {
		1: 'Lo spostamento',
		2: "L'intervallo di tempo",
		3: 'Andata e ritorno',
		4: 'La tabella della legge oraria',
	},
	'velocita': {
		1: 'La velocità media',
		2: "Chilometri all'ora e metri al secondo",
		3: 'Distanza e tempo',
		4: 'Velocità media e velocità scalare media',
		5: 'Un viaggio in due tratti',
	},
	'fis-moto-rettilineo-uniforme': {
		1: 'La legge oraria',
		2: "L'istante di arrivo",
		3: 'Il grafico spazio-tempo',
		4: "L'area sotto il grafico velocità-tempo",
		5: "L'incontro",
	},
	'fis-accelerazione': {
		1: "L'accelerazione media",
		2: "Con i chilometri all'ora",
		3: 'La frenata',
		4: 'Velocità finale e tempo',
		5: "Il segno dell'accelerazione",
	},
	'moto-uniforme-accelerato': {
		1: 'La velocità dopo un tempo',
		2: 'Partenza da fermo',
		3: 'La legge oraria',
		4: 'Senza il tempo',
		5: 'La frenata',
		6: 'Lo spazio di arresto',
	},
	'fis-grafico-velocita-tempo': {
		1: "L'accelerazione dalla pendenza",
		2: "Lo spostamento dall'area",
		3: 'Un viaggio a tratti',
		4: 'Le aree con il segno',
		5: 'La velocità media',
	},
	'fis-caduta-libera': {
		1: 'Dal tempo di caduta',
		2: 'Il tempo di caduta',
		3: "La velocità d'arrivo",
		4: "Il lancio verso l'alto",
		5: 'La velocità con il segno',
		6: 'Il lancio da un balcone',
	},
	'fis-spostamento-velocita-piano': {
		1: 'Lo spostamento dalle coordinate',
		2: 'La velocità media',
		3: 'Velocità media e velocità scalare media',
		4: 'Le componenti della velocità',
		5: 'Lo spostamento in un intervallo',
	},
	'fis-composizione-moti': {
		1: 'Velocità nella stessa direzione',
		2: 'Con la corrente e contro',
		3: 'Velocità perpendicolari',
		4: 'Attraversare il fiume',
		5: 'La prua controcorrente',
	},
	'fis-moto-circolare-uniforme': {
		1: 'Periodo e frequenza',
		2: 'La velocità tangenziale',
		3: 'La velocità angolare',
		4: 'Velocità tangenziale e angolare',
		5: 'Due punti sulla stessa ruota',
	},
	'fis-accelerazione-centripeta': {
		1: 'Dalla velocità e dal raggio',
		2: 'Con la velocità in km/h',
		3: 'Dal periodo',
		4: 'La velocità massima in curva',
		5: "Come cambia l'accelerazione",
	},
	'fis-moto-armonico': {
		1: 'Ampiezza e periodo',
		2: 'La posizione a un istante',
		3: 'La velocità massima',
		4: "L'accelerazione massima",
		5: "Dalla velocità e dall'accelerazione massime",
	},
	'fis-primo-principio': {
		1: 'Velocità costante in verticale',
		2: "L'attrito a velocità costante",
		3: 'La maniglia inclinata',
		4: 'Due funi perpendicolari',
	},
	'leggi-newton': {
		1: "L'accelerazione",
		2: 'La forza o la massa',
		3: 'Due forze opposte',
		4: 'Due forze perpendicolari',
		5: "Con l'attrito",
		6: 'Forza e velocità',
	},
	'fis-terzo-principio': {
		1: 'Azione e reazione',
		2: 'Stessa forza, accelerazioni diverse',
		3: "Dall'accelerazione di uno a quella dell'altro",
		4: "L'accelerazione della Terra",
		5: 'Il razzo',
	},
	'fis-diagramma-corpo-libero': {
		1: 'Quante forze',
		2: 'La fune inclinata',
		3: 'La reazione del pavimento',
		4: "La fune inclinata con l'attrito",
		5: 'Quanto segna la bilancia',
		6: "L'accelerazione dell'ascensore",
	},
	'fis-piano-inclinato': {
		1: "L'accelerazione senza attrito",
		2: 'Tempo e velocità in fondo',
		3: "L'accelerazione con l'attrito",
		4: 'Il lancio in salita',
		5: "In salita con l'attrito",
	},
	'fis-corpi-collegati': {
		1: "L'accelerazione di due carrelli",
		2: 'La tensione tra i carrelli',
		3: 'Il pesetto e la carrucola',
		4: 'La tensione del filo appeso',
		5: "Con l'attrito sul tavolo",
		6: 'La macchina di Atwood',
	},
	'fis-moto-proiettili': {
		1: 'Il tempo di volo',
		2: 'La gittata',
		3: 'Il problema inverso',
		4: "La velocità all'arrivo",
		5: "L'angolo all'arrivo",
	},
	'fis-forza-centripeta': {
		1: 'La forza centripeta',
		2: 'Dal periodo',
		3: "L'auto in curva",
		4: 'Il disco e il pesetto',
		5: 'In cima al giro',
	},
	'fis-pendolo-molla': {
		1: 'Il periodo della molla',
		2: 'Il periodo del pendolo',
		3: 'Che cosa cambia il periodo',
		4: 'Dal periodo alla molla o al filo',
		5: 'Misurare g',
	},
	'lavoro': {
		1: 'Forza e spostamento paralleli',
		2: 'La forza inclinata',
		3: 'Il segno del lavoro',
		4: 'Il lavoro totale',
		5: "La fune inclinata con l'attrito",
		6: "L'area sotto il grafico",
	},
	'fis-potenza': {
		1: 'Lavoro e tempo',
		2: 'Sollevare un carico',
		3: 'Potenza e velocità',
		4: 'La velocità in km/h',
		5: 'Il kilowattora',
	},
	'fis-energia-cinetica': {
		1: "L'energia cinetica",
		2: 'La velocità in km/h',
		3: "La velocità dall'energia",
		4: "Il teorema dell'energia cinetica",
		5: 'Lo spazio di frenata',
	},
	'fis-energia-potenziale': {
		1: "L'energia potenziale gravitazionale",
		2: 'Il livello di riferimento',
		3: 'Il lavoro del peso',
		4: "L'energia potenziale elastica",
		5: "La deformazione dall'energia",
	},
	'energia': {
		1: 'La caduta libera',
		2: "L'altezza massima",
		3: "Da un punto all'altro della pista",
		4: 'La molla che lancia un blocco',
		5: 'La molla e la salita',
	},
	'fis-energia-totale': {
		1: "Il lavoro dell'attrito",
		2: 'La velocità dopo un tratto con attrito',
		3: "L'energia dissipata",
		4: "La rampa con l'attrito",
		5: 'Il rendimento',
		6: "L'energia spesa",
	},
	'fis-temperatura': {
		1: 'Celsius e kelvin',
		2: 'Le differenze di temperatura',
		3: 'Da Celsius a Fahrenheit',
		4: 'Da Fahrenheit a Celsius',
		5: 'La taratura del termometro',
	},
	'fis-dilatazione-termica': {
		1: "L'allungamento",
		2: 'La temperatura finale',
		3: 'Il coefficiente di dilatazione',
		4: 'Un liquido che trabocca',
		5: 'Il volume di un solido',
	},
	'calore': {
		1: "Scaldare l'acqua",
		2: 'Altre sostanze, anche che si raffreddano',
		3: 'La temperatura finale',
		4: 'Il calore specifico da una misura',
		5: "La pentola e l'acqua",
		6: 'Le calorie',
	},
	'fis-equilibrio-termico': {
		1: 'Il calore scambiato',
		2: 'Acqua calda e acqua fredda',
		3: "Un metallo nell'acqua",
		4: 'Il dato mancante',
		5: 'Il calore specifico',
		6: "L'equivalente in acqua",
	},
	'fis-propagazione-calore': {
		1: 'Il calore che passa ogni secondo',
		2: 'Le unità da convertire',
		3: 'Il calore in un tempo',
		4: 'Lo spessore o la conducibilità',
		5: 'Due strati a confronto',
	},
	'fis-passaggi-stato': {
		1: 'Il calore latente',
		2: 'La massa dal calore',
		3: 'Due tappe',
		4: 'Tre tappe',
		5: 'Il grafico temperatura-calore',
		6: "Ghiaccio nell'acqua",
	},
	// Chemistry, first two years: generators in TypeScript (docs/lezioni/chimica/README.md, "Il biennio").
	'chim-grandezze-si': {
		1: 'Unità e simboli',
		2: "Un prefisso e l'unità",
		3: 'Notazione scientifica',
		4: 'Tra due prefissi',
		5: 'I volumi',
		6: 'Densità e concentrazioni',
	},
	'chim-massa-volume-densita': {
		1: 'La densità',
		2: 'Massa o volume',
		3: 'Unità diverse',
		4: 'La pesata per differenza',
		5: 'Il volume per immersione',
		6: 'Galleggia o affonda',
	},
	'chim-temperatura-calore': {
		1: 'Celsius e kelvin',
		2: 'Differenze di temperatura',
		3: 'Il calore',
		4: 'La temperatura finale',
		5: 'Il calorimetro',
		6: "L'equilibrio termico",
	},
	'chim-errori-cifre-significative': {
		1: 'Contare le cifre',
		2: 'Arrotondare',
		3: 'Valore medio e incertezza',
		4: 'Somme e differenze',
		5: 'Prodotti e quozienti',
		6: "L'incertezza relativa",
	},
	'chim-stati-aggregazione': {
		1: 'Le proprietà dei tre stati',
		2: 'Lo stato a una temperatura',
		3: 'La temperatura in kelvin',
		4: 'Quale sostanza',
		5: 'Il volume cambia con lo stato',
	},
	'chim-modello-particellare': {
		1: 'Le particelle nei tre stati',
		2: 'Spiegare un fenomeno',
		3: 'Dai gradi Celsius ai kelvin',
		4: 'Chi si agita di più',
	},
	'chim-sostanze-miscugli': {
		1: 'Sostanza pura o miscuglio',
		2: 'Omogeneo o eterogeneo',
		3: 'Le particelle',
		4: 'La prova della fusione',
		5: 'Fasi e componenti',
	},
	'chim-soluzioni-percentuale': {
		1: 'La percentuale in massa',
		2: 'Soluto e solvente',
		3: 'Massa su volume',
		4: 'La percentuale in volume',
		5: 'Quanto soluto serve',
		6: 'La solubilità',
	},
	'chim-separazione-miscugli': {
		1: 'Il metodo giusto',
		2: 'La proprietà sfruttata',
		3: 'La distillazione',
		4: 'Il fattore di ritenzione',
		5: 'Separare in più passi',
	},
	'chim-passaggi-stato': {
		1: 'Il nome del passaggio',
		2: 'Assorbire o cedere calore',
		3: 'Lo stato a una temperatura',
		4: "Da una temperatura a un'altra",
		5: 'Evaporazione, ebollizione e pressione',
	},
	'chim-curve-riscaldamento': {
		1: 'Le soste termiche',
		2: "Che cosa c'è nel recipiente",
		3: 'Sostanza pura o miscuglio',
		4: 'Riconoscere la sostanza',
		5: 'La curva di raffreddamento',
		6: 'La durata della sosta',
	},
	'chim-trasformazioni-fisiche-chimiche': {
		1: 'Fisica o chimica',
		2: 'Reagenti e prodotti',
		3: 'Gli indizi',
		4: "L'indizio non basta",
	},
	'chim-elementi-composti': {
		1: 'I simboli chimici',
		2: 'Elemento o composto',
		3: 'Elemento, composto o miscuglio',
		4: 'Gli elementi di una formula',
	},
	'chim-legge-lavoisier': {
		1: 'Reagenti e prodotto',
		2: 'La massa mancante',
		3: 'Il recipiente aperto',
		4: 'Il becher e il vetrino',
		5: 'Il reagente che avanza',
	},
	'chim-legge-proust': {
		1: 'Il rapporto di combinazione',
		2: 'La massa che si combina',
		3: 'La composizione percentuale',
		4: 'Il reagente in eccesso',
		5: 'Il composto con un reagente in eccesso',
	},
	'chim-legge-proporzioni-multiple': {
		1: 'La stessa massa',
		2: 'Masse diverse',
		3: 'Dalla massa del composto',
		4: 'Dalle percentuali',
		5: 'La formula del secondo',
	},
	'chim-teoria-atomica-dalton': {
		1: 'I postulati',
		2: 'Quale legge',
		3: 'Che cosa resta oggi',
		4: 'Contare gli atomi',
		5: 'Le masse relative',
	},
	'chim-atomi-molecole-ioni': {
		1: 'Atomo, molecola o ione',
		2: "Dall'atomo allo ione",
		3: 'Gli elettroni di uno ione',
		4: 'Il nome dello ione',
		5: 'Di che particelle è fatta',
	},
	'chim-formula-chimica': {
		1: 'Leggere gli indici',
		2: 'Tutti gli atomi',
		3: 'Il coefficiente',
		4: 'Le parentesi',
		5: 'Gli idrati',
		6: 'La formula dagli ioni',
	},
	'chim-teoria-cinetica': {
		1: 'Celsius e kelvin',
		2: 'Le ipotesi del modello',
		3: 'Temperatura ed energia',
		4: 'Particelle leggere e pesanti',
		5: 'Quale campione',
	},
	'chim-pressione-gas': {
		1: "Da un'unità all'altra",
		2: 'Millimetri di mercurio e kilopascal',
		3: 'Forza e pressione sul pistone',
		4: 'Il manometro a tubo aperto',
		5: 'Pressione assoluta e relativa',
	},
	'chim-legge-boyle': {
		1: 'La pressione finale',
		2: 'Il volume finale',
		3: 'Unità diverse',
		4: 'Dal grafico pressione-volume',
		5: 'La bolla del sub',
		6: 'Di quanto per cento',
	},
	'chim-legge-charles-gay-lussac': {
		1: 'Charles, in kelvin',
		2: 'Charles, in gradi Celsius',
		3: 'Gay-Lussac',
		4: 'La temperatura finale',
		5: 'Dal grafico volume-temperatura',
	},
	'chim-equazione-generale-gas': {
		1: 'Quale legge',
		2: 'Cambia tutto',
		3: 'Gradi Celsius e millilitri',
		4: 'La temperatura finale',
		5: 'Le condizioni normali',
	},
	'chim-principio-avogadro': {
		1: 'I volumi nelle reazioni',
		2: 'Stesso volume, stesse particelle',
		3: 'La massa delle molecole',
		4: 'Quale gas è',
		5: 'La formula dai volumi',
	},
	'chim-formula-minima': {
		1: 'Dalla formula molecolare',
		2: 'La percentuale in massa',
		3: 'Dalla composizione alla formula minima',
		4: 'Quando serve moltiplicare',
		5: 'La formula molecolare',
	},
	'chim-volume-molare': {
		1: 'Moli e volume',
		2: 'Massa e volume',
		3: 'Molecole e atomi in un volume',
		4: 'La densità di un gas',
		5: 'La formula di un gas',
	},
	'gas-ideali': {
		1: 'Il volume di un gas',
		2: 'La pressione da una massa',
		3: 'Con le unità del SI',
		4: 'La temperatura',
		5: 'La massa molare',
		6: 'La densità di un gas',
	},
	'chim-pressioni-parziali': {
		1: 'La legge di Dalton',
		2: 'La frazione molare',
		3: "Con l'equazione di stato",
		4: 'Una miscela in grammi',
		5: "Un gas raccolto sopra l'acqua",
	},
	'chim-natura-elettrica': {
		1: 'Attrazione e repulsione',
		2: 'Conduttori e isolanti',
		3: 'Lo strofinio',
		4: 'Contare gli elettroni',
		5: 'Due sfere a contatto',
	},
	'particelle-fondamentali': {
		1: 'Le tre particelle',
		2: 'Chi e quando',
		3: 'La carica di un gruppo di particelle',
		4: 'Le masse',
		5: 'Le gocce di Millikan',
	},
	'chim-thomson-rutherford': {
		1: 'I modelli atomici',
		2: "La lamina d'oro",
		3: 'Atomo e nucleo',
		4: 'Il modello in scala',
		5: 'Il volume del nucleo',
	},
	'numero-massa': {
		1: "Le particelle dell'atomo",
		2: 'Il simbolo',
		3: 'Gli ioni',
		4: 'Gli isotopi',
		5: 'La massa atomica media',
		6: "L'abbondanza di un isotopo",
	},
	'chim-tavola-mendeleev': {
		1: 'Storia e struttura della tavola',
		2: 'Una massa che manca',
		3: 'Massa e numero atomico',
		4: 'Formule per analogia',
	},
	'chim-acqua-molecola': {
		1: 'La composizione',
		2: "L'acqua dal suo elemento",
		3: 'Forma e polarità',
		4: 'Chi forma legami a idrogeno',
		5: 'Che cosa si rompe',
	},
	'chim-acqua-proprieta': {
		1: 'La proprietà giusta',
		2: 'Il volume del ghiaccio',
		3: 'Il ghiaccio che galleggia',
		4: "Scaldare l'acqua",
		5: 'Lo stesso calore',
	},
	'chim-acqua-solvente': {
		1: "Che cosa succede nell'acqua",
		2: 'Gli ioni di un sale',
		3: 'Le moli di ioni',
		4: 'Quanto se ne scioglie',
		5: 'La cristallizzazione',
		6: "La durezza dell'acqua",
	},
	'chim-acqua-acidi-basi': {
		1: 'Che cosa dice la prova',
		2: 'Acidi e basi secondo Arrhenius',
		3: 'La scala del pH',
		4: 'Dieci volte per unità',
		5: 'La diluizione',
		6: 'Gli indicatori',
	},
	// Chemistry: the names of the Python generators' levels (scripts/chimica/esercizi/).

	'mole-massa-molare': {
		1: 'La formula dal disegno',
		2: 'La massa molare',
		3: 'Dalla massa alle moli',
		4: 'Molecole e atomi',
		5: 'Composizione percentuale',
	},
	'geometria-molecolare-vsepr': {
		1: 'Senza coppie solitarie',
		2: 'Con coppie solitarie',
		3: 'Legami doppi e tripli',
		4: "L'angolo di legame",
		5: 'Polare o apolare',
	},
	'alcani-nomenclatura': {
		1: 'Un solo metile',
		2: 'Più metili',
		3: 'Sostituenti diversi',
		4: 'La catena nascosta',
		5: 'Tutto insieme',
	},
	'isomeria': {
		1: 'Isomeri o no',
		2: "Che relazione c'è",
		3: 'Carboni chirali',
		4: 'E o Z',
		5: 'R o S',
	},
	'gruppi-funzionali': {
		1: 'Un gruppo solo',
		2: 'Trova il gruppo',
		3: 'I gruppi che si confondono',
		4: 'Molecole vere',
		5: 'Tutti i gruppi',
	},
	'amminoacidi-legame-peptidico': {
		1: 'Le parti di un amminoacido',
		2: 'Le catene laterali',
		3: 'Il dipeptide giusto',
		4: 'Contare i legami peptidici',
		5: 'La forma a pH 7',
	},
	'monomi': {
		1: 'Coefficiente e parte letterale',
		2: 'Monomio o no',
		3: 'Forma normale con gli interi',
		4: 'Forma normale con frazioni e potenze',
		5: 'Valore numerico con gli interi',
		6: 'Valore numerico con le frazioni',
	},
	'polinomi': {
		1: 'Ridurre in una lettera',
		2: 'Ridurre in due lettere',
		3: 'Ridurre con le frazioni',
		4: 'Il grado di un polinomio',
		5: 'Il grado dopo la riduzione',
		6: 'Ordinato, completo, omogeneo',
		7: 'Valore numerico',
	},
	'polinomi-operazioni': {
		1: 'Somma di due polinomi',
		2: 'Differenza di due polinomi',
		3: 'Somme con le frazioni',
		4: 'Monomio per polinomio',
		5: 'Binomio per binomio',
		6: 'Polinomio per polinomio',
		7: 'Polinomio diviso un monomio',
	},
	'polinomi-prodotti-notevoli': {
		1: 'Somma per differenza con un numero',
		2: 'Somma per differenza con i monomi',
		3: 'Quadrato di un binomio con un numero',
		4: 'Quadrato di un binomio con i monomi',
		5: 'Quadrato di un trinomio',
		6: 'Cubo di un binomio',
		7: 'Il triangolo di Tartaglia',
	},
	'polinomi-espressioni': {
		1: 'Prodotti e somme',
		2: 'Prodotti notevoli con un segno davanti',
		3: 'Due lettere o gradi più alti',
		4: 'Con le frazioni',
		5: 'Cubi e potenze nei prodotti',
		6: 'Prodotti notevoli da riconoscere',
		7: 'Tonde, quadre e graffe',
	},
	'polinomi-divisione': {
		1: 'Divisore di primo grado',
		2: 'Dividendo di terzo grado',
		3: 'Dividendo incompleto',
		4: 'Divisore di secondo grado',
		5: 'Quoziente con le frazioni',
		6: 'Divisore incompleto',
	},
	'polinomi-ruffini': {
		1: 'Ruffini con x − a',
		2: 'Dividendo incompleto',
		3: 'Ruffini con x + a',
		4: 'Ruffini con le frazioni',
		5: 'Il teorema del resto',
		6: 'Divisibile o no',
		7: 'Trovare il parametro k',
	},
	'scomposizione-raccoglimento': {
		1: 'Raccogliere un numero o una lettera',
		2: 'Raccogliere un monomio',
		3: 'Raccogliere il segno meno',
		4: 'Raccogliere una parentesi',
		5: 'Raccoglimento parziale',
		6: 'Riordinare prima di raccogliere',
	},
	'scomposizione-prodotti-notevoli': {
		1: 'Differenza di quadrati',
		2: 'Quadrato di un binomio',
		3: 'Somma e differenza di cubi',
		4: 'Cubo o quadrato di un trinomio',
		5: 'Prima raccogli, poi il prodotto notevole',
		6: 'Scomposizioni in più passi',
	},
	'scomposizione-trinomio': {
		1: 'Somma e prodotto positivi',
		2: 'Somma e prodotto con i segni',
		3: 'Prima raccogli, poi scomponi',
		4: 'Si scompone o no',
		5: 'Primo coefficiente diverso da 1',
		6: 'Trinomi in due lettere',
		7: 'Trinomi di quarto grado',
	},
	'scomposizione-ruffini': {
		1: 'Trovare uno zero',
		2: 'Zero 1 o −1, poi il trinomio',
		3: 'Una potenza mancante',
		4: 'Uno zero frazionario',
		5: 'Quarto grado, due volte Ruffini',
		6: 'Raccoglimento, Ruffini e trinomio',
	},
	'polinomi-mcd-mcm': {
		1: 'Due polinomi',
		2: 'Esponenti diversi',
		3: 'Tre polinomi',
		4: 'Fattori opposti',
		5: 'Due lettere',
		6: 'Cubi e falso quadrato',
		7: 'Con le frazioni',
	},
	'insiemi-prodotto-cartesiano': {
		1: 'Coppie ordinate uguali o no',
		2: 'Elencare le coppie del prodotto',
		3: 'Quante coppie ha il prodotto',
		4: 'Dalla tabella e dalle coppie agli insiemi',
		5: 'Insiemi descritti con una proprietà',
		6: 'Coppie con una condizione',
	},
	'dominio-codominio-immagine': {
		1: 'Trovare le controimmagini',
		2: "L'insieme immagine",
		3: 'Immagine e controimmagine con una formula',
		4: 'Il dominio: polinomi e frazioni',
		5: 'Denominatori da scomporre',
		6: 'I casi scomodi del dominio',
	},
	'relazioni-binarie': {
		1: 'Dalla proprietà alle coppie',
		2: 'La coppia sta nella relazione?',
		3: 'Leggere la tabella a doppia entrata',
		4: 'Dalle coppie alla proprietà',
		5: 'Relazione in un insieme: i cappi',
		6: 'La relazione inversa',
	},
	'definizione-funzione': {
		1: 'È una funzione? Guarda le coppie',
		2: 'Il valore in un numero intero',
		3: 'Con il quadrato di un negativo',
		4: 'Il valore in una frazione',
		5: 'Completare la tabella di valori',
		6: 'Al posto di x una lettera',
	},
	'equazioni-problemi': {
		1: 'Numeri ed età: anni fa',
		2: 'Aree e lati che cambiano',
		3: 'Sconti e percentuali sul resto',
		4: 'Incontri e inseguimenti',
		5: 'Miscele e diluizioni',
		6: 'Lavorare insieme: ore e minuti',
		7: 'La soluzione è accettabile?',
	},
	'equazioni-fratte': {
		1: 'Una frazione per membro',
		2: 'Denominatori con la x e numeri',
		3: 'Un denominatore da scomporre',
		4: 'Denominatori opposti',
		5: 'Quando x² si cancella',
		6: 'Soluzioni escluse, impossibili e indeterminate',
	},
	'composizione-di-funzioni': {
		1: 'Comporre seguendo le frecce',
		2: 'La composta in un numero',
		3: 'La formula con due funzioni lineari',
		4: 'La formula con un quadrato',
		5: "Trovare l'inversa",
		6: "L'inversa con le frazioni",
		7: "Quando c'è l'inversa e il suo grafico",
	},
	'frazioni-algebriche-semplificazione': {
		1: 'Denominatore monomio',
		2: 'Un fattore comune sopra e sotto',
		3: 'Quando resta 1 o un polinomio',
		4: 'Fattori opposti: 2 − x e x − 2',
		5: 'Due lettere e raccoglimento parziale',
		6: 'Cubi e regola di Ruffini',
	},
	'frazioni-algebriche-esistenza': {
		1: 'Il valore di una frazione, se esiste',
		2: 'C.E. con un denominatore di primo grado',
		3: 'C.E. con un monomio o un raccoglimento',
		4: 'C.E. con differenza di quadrati o quadrato',
		5: 'C.E. con un trinomio',
		6: 'C.E. in più passi e fattori mai nulli',
		7: 'C.E. di più frazioni insieme',
	},
	'relazioni-equivalenza-ordine': {
		1: 'Una proprietà alla volta',
		2: 'Le quattro proprietà insieme',
		3: 'Relazioni in ℕ e ℤ a parole',
		4: 'Classi e insieme quoziente',
		5: 'Stesso resto nella divisione',
		6: 'Ordine largo o stretto, totale o parziale',
		7: 'Le coppie da aggiungere',
	},
	'funzioni-lineari': {
		1: 'Diretta, inversa o lineare?',
		2: 'Il valore che manca nella tabella',
		3: 'La formula da una tabella',
		4: 'Il tipo da una tabella',
		5: 'Trovare m e q',
		6: 'Problemi diretti e inversi',
		7: 'Problemi in due tempi e col quadrato',
	},
	'equazioni-letterali': {
		1: 'Coefficiente numerico, niente da discutere',
		2: 'Il parametro nel coefficiente: a = 0',
		3: 'Raccogliere la x: il caso indeterminato',
		4: 'Tre casi: determinata, impossibile, indeterminata',
		5: 'Denominatori e coefficiente con il meno',
		6: 'Formule inverse',
		7: 'Formule inverse con i numeri',
	},
	'frazioni-algebriche-operazioni': {
		1: 'Stesso denominatore',
		2: 'Denominatori di primo grado',
		3: 'Denominatori da scomporre',
		4: 'Il prodotto',
		5: 'Il quoziente e le sue C.E.',
		6: 'Una parentesi divisa per una frazione',
		7: 'Potenza, quoziente e somma',
	},
	'geometria-enti': {
		1: 'Segmenti e punto medio',
		2: 'Che tipo di angolo è',
		3: 'Gradi e primi',
		4: 'Complementare e supplementare',
		5: 'Complementare e supplementare con i primi',
		6: 'Opposti al vertice e bisettrici',
		7: "Problemi con un'equazione",
	},
	'statistica-variabilita': {
		1: 'Il campo di variazione',
		2: 'Gli scarti dalla media',
		3: 'Lo scarto semplice medio',
		4: 'Scarto quadratico medio esatto',
		5: 'Arrotondare σ al centesimo',
		6: 'Da una tabella di frequenze',
		7: 'Chi ha i dati più dispersi',
	},
	'statistica-medie': {
		1: 'Media di una lista di numeri',
		2: 'Media ponderata dei voti',
		3: 'Media da una tabella di frequenze',
		4: 'Mediana di dati non ordinati',
		5: 'Mediana e moda da una tabella',
		6: 'Media o mediana? Valori anomali',
		7: 'Media di dati in classi',
	},
	'statistica-dati': {
		1: 'Popolazione, campione e unità',
		2: 'Che tipo di carattere',
		3: 'Contare le frequenze',
		4: 'Cumulate: al massimo, almeno',
		5: 'Dati in classi e il dato sul confine',
		6: "Gli angoli dell'aerogramma",
		7: 'Dagli angoli alle frequenze',
	},
	'geometria-punti-notevoli': {
		1: 'Riconoscere il punto notevole',
		2: 'Baricentro: la regola del 2 : 1',
		3: 'Dove cadono ortocentro e circocentro',
		4: 'Il triangolo rettangolo',
		5: "L'angolo tra due bisettrici",
		6: "L'angolo tra due altezze",
		7: 'I raggi del triangolo equilatero',
	},
	'geometria-perpendicolari-parallele': {
		1: 'I nomi delle coppie di angoli',
		2: 'Gli otto angoli con due parallele',
		3: 'Parallele o no',
		4: "Le ampiezze con un'equazione",
		5: 'Gli angoli del triangolo',
		6: "L'angolo esterno",
		7: 'Gli angoli dei poligoni',
	},
	'disequazioni-primo-grado': {
		1: 'Leggere gli intervalli',
		2: 'Coefficiente positivo',
		3: 'Quando il verso cambia',
		4: 'Con le parentesi',
		5: 'Con i denominatori',
		6: 'Sempre vere o impossibili',
		7: 'Dal problema alla disequazione',
	},
	'angoli-e-lati-dei-triangoli': {
		1: 'Classificare un triangolo',
		2: 'Lati e angoli corrispondenti',
		3: 'Quale criterio di congruenza',
		4: 'Completare una dimostrazione',
		5: 'Esiste il triangolo?',
		6: 'Il terzo angolo',
		7: 'Gli angoli del triangolo isoscele',
	},
	'disequazioni-razionali': {
		1: 'Prodotto di due fattori',
		2: 'Estremi compresi',
		3: 'Un fattore come 3 − x',
		4: 'Tre fattori',
		5: 'Frazione e zero',
		6: 'Frazione e numero',
		7: 'Due frazioni',
	},
	'sistemi-di-disequazioni': {
		1: 'Disequazioni già quasi risolte',
		2: 'Con un cambio di verso',
		3: 'Tre disequazioni, con i denominatori',
		4: 'Impossibile o con un solo punto',
		5: 'Una disequazione sempre o mai vera',
		6: 'Doppia disequazione, x al centro',
		7: 'Doppia disequazione, x in due membri',
	},
	'geometria-quadrilateri': {
		1: 'Angoli del parallelogramma',
		2: 'Lati, perimetro e diagonali',
		3: 'Angoli con le diagonali',
		4: 'Angoli dei trapezi',
		5: 'Riconoscere il quadrilatero',
		6: 'Vero o falso sulle famiglie',
		7: 'Giustificare un passo',
	},
	'insiemi-differenza': {
		1: 'La differenza di due insiemi',
		2: 'Differenza di insiemi descritti',
		3: 'Contare gli elementi della differenza',
		4: 'Il complementare in U',
		5: 'Le leggi di De Morgan',
		6: 'Problemi con due gruppi',
		7: 'Problemi con tre gruppi',
	},
	'insiemi-intersezione': {
		1: 'Gli elementi in comune',
		2: 'Multipli, divisori e condizioni',
		3: "Le proprietà dell'intersezione",
		4: 'Intersezione di tre insiemi',
		5: 'Contare gli elementi comuni',
		6: 'Il minimo e il massimo',
	},
	'logica-proposizioni': {
		1: 'Riconoscere una proposizione',
		2: 'Un connettivo alla volta',
		3: 'Calcolare su una riga',
		4: 'Tavola con due lettere',
		5: 'Tavola con tre lettere',
		6: 'Tautologie ed equivalenze',
		7: 'Negare con De Morgan',
	},
	'logica-implicazione': {
		1: 'Vero o falso: se… allora',
		2: 'Inversa, contraria, contronominale',
		3: "La tavola dell'implicazione",
		4: 'Ragionamenti ed equivalenze',
		5: 'Necessaria o sufficiente',
		6: 'Implicazione e insiemi di verità',
		7: "Negare un'implicazione",
	},
	'logica-quantificatori': {
		1: 'Enunciato aperto o proposizione',
		2: "L'insieme di verità",
		3: 'Per ogni ed esiste: il controesempio',
		4: 'Vero in ℕ, in ℤ o in ℚ',
		5: 'Dalle parole ai simboli',
		6: 'Negare "tutti" e "qualche"',
		7: "Due quantificatori: conta l'ordine",
	},
	'numeri-reali-irrazionali': {
		1: 'Radici razionali o irrazionali',
		2: 'Irrazionale dal decimale',
		3: 'Approssimare una radice',
		4: 'Approssimare −√n',
		5: 'Confrontare due numeri reali',
		6: 'Mettere in ordine',
		7: 'Conti con le radici: razionale o no',
	},
	'sistemi-cramer': {
		1: 'Il determinante di una matrice 2 × 2',
		2: 'La regola di Cramer',
		3: 'Prima la forma normale',
		4: 'D = 0: impossibile o indeterminato',
		5: 'Sistemi con un parametro k',
		6: 'Il determinante 3 × 3 con Sarrus',
		7: 'Tre equazioni in tre incognite',
	},
	'radicali-esponente-razionale': {
		1: 'Da potenza a radicale e ritorno',
		2: 'Calcolare una potenza con la frazione',
		3: 'Esponente negativo o decimale',
		4: 'Un solo radicale da due',
		5: 'Tre potenze alla stessa base',
		6: 'Lettere e radicali annidati',
		7: 'Radicandi negativi e razionalizzazione',
	},
	'sistemi-di-equazioni': {
		1: 'Quale coppia è la soluzione',
		2: 'Metodo di sostituzione',
		3: 'Metodo del confronto',
		4: 'Metodo di riduzione',
		5: 'Con denominatori e parentesi',
		6: 'Una, nessuna o infinite soluzioni',
		7: 'Sistemi fratti',
	},
	'numeri-reali-radici': {
		1: 'Calcolare una radice',
		2: 'Quando esiste il radicale',
		3: 'La radice di x²: il valore assoluto',
		4: 'Semplificare un radicale',
		5: 'Semplificare con le lettere',
		6: 'Portare allo stesso indice',
		7: 'Qual è il più grande',
	},
	'sistemi-problemi': {
		1: 'Due numeri: somma, differenza, rapporto',
		2: 'Biglietti e monete, anche impossibili',
		3: 'Le età di genitori e figli',
		4: 'Rettangoli e triangoli isosceli',
		5: 'Le cifre di un numero',
		6: 'Sconti e miscele',
		7: 'Barche, aerei e tre incognite',
	},
	'equazioni-parametriche': {
		1: "Quando l'equazione è di primo grado",
		2: 'Soluzioni distinte o coincidenti',
		3: 'Una soluzione è data',
		4: 'Soluzioni opposte, reciproche o nulle',
		5: 'Somma o prodotto dati',
		6: 'Somma dei quadrati',
	},
	'equazioni-secondo-grado-relazioni': {
		1: 'Somma e prodotto dai coefficienti',
		2: "Trovare l'altra soluzione",
		3: "L'equazione con soluzioni date",
		4: 'Due numeri di somma e prodotto dati',
		5: 'Scomporre il trinomio con le soluzioni',
		6: 'Il segno delle soluzioni',
		7: 'Espressioni simmetriche delle soluzioni',
	},
	'radicali-operazioni': {
		1: 'Prodotto e quoziente di radicali',
		2: 'Portare fuori un fattore',
		3: 'Portare fuori con le lettere',
		4: 'Portare dentro e confrontare',
		5: 'Indici diversi, potenze e radici',
		6: 'Sommare radicali simili',
		7: 'Prodotti notevoli con i radicali',
	},
	'equazioni-secondo-grado-problemi': {
		1: 'Problemi sui numeri',
		2: 'Una, due o nessuna risposta',
		3: 'Aree di rettangoli e triangoli',
		4: 'Lati irrazionali o impossibili',
		5: 'Cornici e teorema di Pitagora',
		6: 'Moto e lavoro: equazioni fratte',
		7: 'Due aumenti o due sconti uguali',
	},
	'numeri-reali-espressioni': {
		1: 'Semplificare prima di sommare',
		2: 'Prodotti notevoli con i radicali',
		3: 'Radice al denominatore',
		4: 'Denominatore binomio: il coniugato',
		5: 'Radicali con indici diversi',
		6: 'Equazioni con i radicali',
		7: 'Disequazioni: il segno del coefficiente',
	},
	'radicali-razionalizzazione': {
		1: 'Una radice quadrata sotto',
		2: 'Prima semplifica la radice',
		3: 'Radici cubiche e oltre',
		4: 'Due fattori sotto la radice',
		5: 'Il coniugato',
		6: 'Coniugati con le trappole',
		7: 'Coniugato con le lettere',
	},
	'il-coefficiente-angolare': {
		1: 'La pendenza da due punti',
		2: 'Punti con le frazioni',
		3: 'La pendenza dalla forma implicita',
		4: 'Retta per un punto',
		5: 'Retta per un punto in forma implicita',
		6: 'Retta per due punti',
		7: 'Tre punti allineati',
	},
	'rette-parallele-tra-loro': {
		1: 'Parallele, perpendicolari o incidenti',
		2: "L'antireciproco",
		3: 'Trovare il parametro k',
		4: 'Retta per un punto, parallela o perpendicolare',
		5: 'La retta in forma implicita o parallela a un asse',
		6: "L'asse di un segmento",
		7: 'La proiezione di un punto su una retta',
	},
	'distanza-punto-retta': {
		1: 'Rette parallele agli assi',
		2: 'La formula della distanza',
		3: 'Dalla forma esplicita',
		4: "Coefficienti frazionari e l'origine",
		5: 'Distanza tra due parallele',
		6: 'Altezza e area di un triangolo',
	},
	'intersezione-tra-due-rette': {
		1: 'Due rette in forma esplicita',
		2: 'Forma implicita e rette x = h, y = k',
		3: 'Incidenti, parallele o coincidenti',
		4: 'I vertici di un triangolo',
		5: "L'area con un lato su un asse",
		6: 'Tre rette per lo stesso punto',
	},
	'funzioni-quadratiche': {
		1: 'Concavità e apertura',
		2: "Il vertice e l'asse",
		3: 'Il vertice con le frazioni',
		4: 'Un punto sulla parabola',
		5: "Dove incontra l'asse x",
		6: 'Sopra, sotto o tangente',
		7: 'La parabola per tre punti',
	},
	'retta-fasci': {
		1: 'La retta del fascio per un punto',
		2: 'La parallela per un punto',
		3: 'Il centro di un fascio con k',
		4: 'La retta esclusa',
		5: 'Fascio improprio: il k senza retta',
		6: 'La retta del fascio per un punto dato',
		7: 'Parallela o perpendicolare nel fascio',
	},
	'il-piano-cartesiano': {
		1: 'In quale quadrante sta il punto',
		2: 'Distanza in orizzontale e in verticale',
		3: 'La formula della distanza',
		4: 'Punti di un asse a distanza data',
		5: 'Punto medio ed estremo',
		6: 'Simmetrici e baricentro',
		7: 'Triangoli e parallelogrammi',
	},
	'equazione-di-una-retta': {
		1: 'Parallele agli assi e bisettrici',
		2: "Dalla forma implicita all'esplicita",
		3: 'Forma implicita con coefficienti interi',
		4: 'Il punto sta sulla retta?',
		5: 'Dove la retta taglia gli assi',
		6: 'Rette con a = 0, b = 0 o c = 0',
		7: 'Il parametro k',
	},
	'disequazioni-secondo-grado-fratte': {
		1: 'Un fattore e un trinomio',
		2: 'Trinomio sempre positivo',
		3: 'Con un quadrato',
		4: 'Frazione con un trinomio',
		5: 'Frazione da ridurre',
		6: 'Sistema di secondo grado',
		7: "Problema con un'area",
	},
	'disequazioni-secondo-grado': {
		1: 'Valori interni o esterni',
		2: 'Coefficiente di x² maggiore di 1',
		3: 'a negativo o termini nei due membri',
		4: 'Soluzioni con i radicali',
		5: 'Delta uguale a zero',
		6: 'Delta negativo',
		7: 'Pure e spurie',
	},
	'concetti-probabilita': {
		1: 'Dado e urna numerata',
		2: 'Certo, impossibile, compatibili',
		3: 'Monete: gli esiti in ordine',
		4: 'Urna con più colori',
		5: 'Una carta dal mazzo di 40',
		6: 'La somma di due dadi',
		7: 'Frequenza relativa e stima',
	},
	'leggi-probabilita': {
		1: 'Evento contrario',
		2: 'Almeno uno',
		3: 'Unione di eventi incompatibili',
		4: 'Unione di eventi compatibili',
		5: 'Unione con due dadi',
		6: 'Tabella a doppia entrata',
	},
	'equazioni-binomie-trinomie': {
		1: 'Raccoglimento totale',
		2: 'Raccoglimento parziale',
		3: 'Regola di Ruffini',
		4: 'Equazioni binomie',
		5: 'Equazioni biquadratiche',
		6: 'Trinomie di sesto grado',
		7: 'Disequazioni scomponibili',
	},
	'valore-assoluto-equazioni': {
		1: 'Valore assoluto uguale a un numero',
		2: 'Argomento di secondo grado',
		3: 'Due valori assoluti uguali',
		4: 'Secondo membro con la x',
		5: 'Secondo membro con la x, secondo grado',
		6: 'Più valori assoluti',
		7: 'Disequazioni con un numero',
		8: 'Disequazioni di secondo grado',
		9: 'Disequazioni con la x a secondo membro',
	},
	'equazioni-irrazionali': {
		1: 'Radice uguale a un numero',
		2: "Radice uguale a un'espressione",
		3: 'Prima si isola il radicale',
		4: 'La condizione sul secondo membro',
		5: 'Due radicali',
		6: 'Radici cubiche',
		7: 'Disequazioni con un numero',
		8: "Radice minore di un'espressione",
		9: "Radice maggiore di un'espressione",
	},
	'sistemi-secondo-grado': {
		1: 'Sostituzione con xy = p',
		2: 'Sostituzione con i quadrati',
		3: 'Retta e parabola',
		4: 'Sistemi simmetrici',
		5: 'Somma dei quadrati',
		6: 'Problemi',
	},
	'circonferenza-cerchio': {
		1: 'Punti interni ed esterni',
		2: 'Retta e circonferenza',
		3: 'Due circonferenze',
		4: 'Corda, distanza e raggio',
		5: 'Angolo al centro e alla circonferenza',
		6: 'Le tangenti da un punto esterno',
		7: 'Il triangolo nella semicirconferenza',
	},
	'trasformazioni-geometriche': {
		1: 'Traslazione di un punto',
		2: 'Simmetrici nel piano cartesiano',
		3: 'Omotetia di centro O',
		4: 'Retta traslata',
		5: 'Retta simmetrica od omotetica',
		6: 'Dalle equazioni alla trasformazione',
		7: 'Composizioni',
	},
	'circonferenza-lunghezza-area': {
		1: 'Circonferenza e area',
		2: 'Formule inverse con π',
		3: 'Con π ≈ 3,14',
		4: "Lunghezza dell'arco",
		5: 'Area del settore',
		6: 'Corona circolare',
		7: 'Segmento circolare',
		8: 'Figure composte',
	},
	'teorema-di-pitagora': {
		1: "L'ipotenusa dai cateti",
		2: "Un cateto dall'ipotenusa",
		3: 'Radicali da semplificare',
		4: "L'inverso di Pitagora",
		5: 'I teoremi di Euclide',
		6: 'Quadrato, equilatero, 45° e 30°-60°',
		7: 'Problemi con i quadrilateri',
	},
	'triangolo-rettangolo-trigonometria': {
		1: 'Seno, coseno e tangente dai lati',
		2: 'I valori per 30, 45 e 60 gradi',
		3: 'Da un valore agli altri due',
		4: 'Un lato con i valori esatti',
		5: 'Un lato con la calcolatrice',
		6: "L'angolo da due lati",
		7: 'Problemi',
	},
	'similitudine': {
		1: 'Rettangoli simili',
		2: 'Due angoli e i vertici corrispondenti',
		3: 'Parallela a un lato e ombre',
		4: 'Secondo e terzo criterio',
		5: 'Lati omologhi',
		6: 'Le diagonali del trapezio',
		7: 'Perimetri, aree e scale',
		8: 'I teoremi di Euclide',
	},
	'poligoni-inscritti': {
		1: 'Angoli del quadrilatero inscritto',
		2: 'Riconoscere il quadrilatero inscrivibile',
		3: 'Il quadrilatero circoscritto',
		4: 'Inscrivibile o circoscrivibile',
		5: 'Angolo al centro ed esagono',
		6: 'Apotema e lato con i radicali',
		7: 'I raggi con Pitagora',
	},
	'equivalenza-aree': {
		1: "L'area delle figure",
		2: 'Unità di misura delle aree',
		3: "Una misura dall'area",
		4: "Le due altezze e l'altezza sull'ipotenusa",
		5: 'Poligoni regolari',
		6: 'Figure composte ed equivalenti',
	},
	'teorema-di-talete': {
		1: 'Il quarto segmento',
		2: 'Il segmento intero e i decimali',
		3: "Un'incognita in due segmenti",
		4: 'La parallela a un lato',
		5: 'Il teorema inverso',
		6: 'Il teorema della bisettrice',
		7: 'Il segmento dei punti medi',
		8: 'Parti proporzionali',
	},
};

/** The name of a level, or null when it has none. */
export const levelName = (generator: string, level: number): string | null => levelNames[generator]?.[level] ?? null;
