import dynamic from 'next/dynamic';
import type { ComponentType } from 'react';

/**
 * The inputs of each tool, by slug. Loaded one per page, so a tool's page ships only its own code; rendered on the
 * server too, so the example and its steps are in the HTML.
 */
export const TOOL_COMPONENTS: Record<string, ComponentType> = {
	'calcolo-percentuale': dynamic(() => import('./PercentualeTool').then((m) => m.PercentualeTool)),
	'calcolo-mcm': dynamic(() => import('./McmMcdTool').then((m) => m.McmTool)),
	'calcolo-mcd': dynamic(() => import('./McmMcdTool').then((m) => m.McdTool)),
	'scomposizione-in-fattori-primi': dynamic(() => import('./ScomposizioneTool').then((m) => m.ScomposizioneTool)),
	'calcolatrice-frazioni': dynamic(() => import('./FrazioniTool').then((m) => m.FrazioniTool)),
	'calcolo-espressioni': dynamic(() => import('./EspressioniTool').then((m) => m.EspressioniTool)),
	'calcolo-potenze': dynamic(() => import('./PotenzeTool').then((m) => m.PotenzeTool)),
	'calcolo-radice-quadrata': dynamic(() => import('./RadiceTool').then((m) => m.RadiceTool)),
	'calcolo-proporzioni': dynamic(() => import('./ProporzioniTool').then((m) => m.ProporzioniTool)),
	'equazioni-primo-grado': dynamic(() => import('./EquazioniPrimoGradoTool').then((m) => m.EquazioniPrimoGradoTool)),
	'equazioni-secondo-grado': dynamic(() => import('./EquazioniSecondoGradoTool').then((m) => m.EquazioniSecondoGradoTool)),
	'area-perimetro-quadrato': dynamic(() => import('./GeometriaTool').then((m) => m.QuadratoTool)),
	'area-perimetro-rettangolo': dynamic(() => import('./GeometriaTool').then((m) => m.RettangoloTool)),
	'area-perimetro-triangolo': dynamic(() => import('./GeometriaTool').then((m) => m.TriangoloTool)),
	'area-perimetro-trapezio': dynamic(() => import('./GeometriaTool').then((m) => m.TrapezioTool)),
	'area-perimetro-rombo': dynamic(() => import('./GeometriaTool').then((m) => m.RomboTool)),
	'area-perimetro-parallelogramma': dynamic(() => import('./GeometriaTool').then((m) => m.ParallelogrammaTool)),
	'area-circonferenza-cerchio': dynamic(() => import('./GeometriaTool').then((m) => m.CerchioTool)),
	'teorema-di-pitagora': dynamic(() => import('./PitagoraTool').then((m) => m.PitagoraTool)),
	'media-mediana-moda': dynamic(() => import('./MediaMedianaModaTool').then((m) => m.MediaMedianaModaTool)),
	'gradi-radianti': dynamic(() => import('./GradiRadiantiTool').then((m) => m.GradiRadiantiTool)),
	'equivalenze': dynamic(() => import('./EquivalenzeTool').then((m) => m.EquivalenzeTool)),
	'convertitore-temperatura': dynamic(() => import('./TemperaturaTool').then((m) => m.TemperaturaTool)),
	'convertitore-binario': dynamic(() => import('./BinarioTool').then((m) => m.BinarioTool)),
	'calcolo-media-voti': dynamic(() => import('./MediaVotiTool').then((m) => m.MediaVotiTool)),
	'numeri-primi': dynamic(() => import('./PrimiTool').then((m) => m.PrimiTool)),
	'notazione-scientifica': dynamic(() => import('./NotazioneScientificaTool').then((m) => m.NotazioneScientificaTool)),
	'arrotondamento': dynamic(() => import('./ArrotondamentoTool').then((m) => m.ArrotondamentoTool)),
	'frazione-generatrice': dynamic(() => import('./FrazioneGeneratriceTool').then((m) => m.FrazioneGeneratriceTool)),
	'numeri-romani': dynamic(() => import('./NumeriRomaniTool').then((m) => m.NumeriRomaniTool)),
	'sistemi-lineari-2x2': dynamic(() => import('./SistemiLineariTool').then((m) => m.Sistemi2x2Tool)),
	'sistemi-lineari-3x3': dynamic(() => import('./SistemiLineariTool').then((m) => m.Sistemi3x3Tool)),
	'disequazioni-primo-grado': dynamic(() => import('./DisequazioniTool').then((m) => m.DisequazioniPrimoGradoTool)),
	'disequazioni-secondo-grado': dynamic(() => import('./DisequazioniTool').then((m) => m.DisequazioniSecondoGradoTool)),
	'prodotti-notevoli': dynamic(() => import('./PolinomiTool').then((m) => m.ProdottiNotevoliTool)),
	'divisione-polinomi': dynamic(() => import('./PolinomiTool').then((m) => m.DivisionePolinomiTool)),
	'regola-di-ruffini': dynamic(() => import('./PolinomiTool').then((m) => m.RuffiniTool)),
	'scomposizione-polinomi': dynamic(() => import('./PolinomiTool').then((m) => m.ScomposizionePolinomiTool)),
	'superficie-volume-cubo': dynamic(() => import('./SolidiTool').then((m) => m.CuboTool)),
	'superficie-volume-parallelepipedo': dynamic(() => import('./SolidiTool').then((m) => m.ParallelepipedoTool)),
	'superficie-volume-prisma': dynamic(() => import('./SolidiTool').then((m) => m.PrismaTool)),
	'superficie-volume-piramide': dynamic(() => import('./SolidiTool').then((m) => m.PiramideTool)),
	'superficie-volume-cilindro': dynamic(() => import('./SolidiTool').then((m) => m.CilindroTool)),
	'superficie-volume-cono': dynamic(() => import('./SolidiTool').then((m) => m.ConoTool)),
	'superficie-volume-sfera': dynamic(() => import('./SolidiTool').then((m) => m.SferaTool)),
	'area-perimetro-poligoni-regolari': dynamic(() => import('./PoligoniRegolariTool').then((m) => m.PoligoniRegolariTool)),
	'distanza-tra-due-punti': dynamic(() => import('./CartesianoTool').then((m) => m.DistanzaTool)),
	'punto-medio-segmento': dynamic(() => import('./CartesianoTool').then((m) => m.PuntoMedioTool)),
	'retta-passante-per-due-punti': dynamic(() => import('./CartesianoTool').then((m) => m.RettaTool)),
	'parabola-vertice-fuoco-direttrice': dynamic(() => import('./CartesianoTool').then((m) => m.ParabolaTool)),
	'seno-coseno-tangente': dynamic(() => import('./GoniometriaTool').then((m) => m.SenoCosenoTool)),
	'risoluzione-triangolo-rettangolo': dynamic(() => import('./TriangoliTool').then((m) => m.TriangoloRettangoloTool)),
	'risoluzione-triangolo-qualsiasi': dynamic(() => import('./TriangoliTool').then((m) => m.TriangoloQualsiasiTool)),
	'gradi-primi-secondi': dynamic(() => import('./GradiSessagesimaliTool').then((m) => m.GradiSessagesimaliTool)),
	'calcolo-varianza-deviazione-standard': dynamic(() => import('./VarianzaTool').then((m) => m.VarianzaTool)),
	'calcolo-fattoriale': dynamic(() => import('./CombinatoriaTool').then((m) => m.FattorialeTool)),
	'calcolo-combinatorio': dynamic(() => import('./CombinatoriaTool').then((m) => m.CombinatoriaTool)),
	'distribuzione-binomiale': dynamic(() => import('./BinomialeTool').then((m) => m.BinomialeTool)),
	'convertitore-velocita': dynamic(() => import('./ConversioniUnitaTool').then((m) => m.VelocitaTool)),
	'convertitore-energia': dynamic(() => import('./ConversioniUnitaTool').then((m) => m.EnergiaTool)),
	'convertitore-potenza': dynamic(() => import('./ConversioniUnitaTool').then((m) => m.PotenzaTool)),
	'convertitore-kw-cv': dynamic(() => import('./ConversioniUnitaTool').then((m) => m.KwCvTool)),
	'convertitore-pressione': dynamic(() => import('./ConversioniUnitaTool').then((m) => m.PressioneTool)),
	'pollici-centimetri': dynamic(() => import('./ConversioniUnitaTool').then((m) => m.PolliciTool)),
	'tabelle-di-verita': dynamic(() => import('./TabelleVeritaTool').then((m) => m.TabelleVeritaTool)),
	'complemento-a-due': dynamic(() => import('./ComplementoADueTool').then((m) => m.ComplementoADueTool)),
	'convertitore-ascii': dynamic(() => import('./AsciiTool').then((m) => m.AsciiTool)),
	'calcolo-crediti-scolastici': dynamic(() => import('./CreditiScolasticiTool').then((m) => m.CreditiScolasticiTool)),
	'calcolo-voto-maturita': dynamic(() => import('./VotoMaturitaTool').then((m) => m.VotoMaturitaTool)),
	'conversione-voti': dynamic(() => import('./ConversioneVotiTool').then((m) => m.ConversioneVotiTool)),
	'moto-rettilineo-uniforme': dynamic(() => import('./FisicaTool').then((m) => m.MotoUniformeTool)),
	'moto-uniformemente-accelerato': dynamic(() => import('./FisicaTool').then((m) => m.MotoAcceleratoTool)),
	'calcolo-densita': dynamic(() => import('./FisicaTool').then((m) => m.DensitaTool)),
	'calcolo-energia-cinetica': dynamic(() => import('./FisicaTool').then((m) => m.EnergiaCineticaTool)),
	'calcolo-energia-potenziale': dynamic(() => import('./FisicaTool').then((m) => m.EnergiaPotenzialeTool)),
	'legge-di-ohm': dynamic(() => import('./FisicaTool').then((m) => m.OhmTool)),
	'calcolo-massa-molare': dynamic(() => import('./ChimicaTool').then((m) => m.MassaMolareTool)),
	'calcolo-moli': dynamic(() => import('./ChimicaTool').then((m) => m.MoliTool)),
	'calcolo-molarita': dynamic(() => import('./ChimicaTool').then((m) => m.MolaritaTool)),
	'calcolo-diluizione': dynamic(() => import('./ChimicaTool').then((m) => m.DiluizioneTool))
};
